return {
	config=
	{
		[1]=
		{
			id = 1,
			task_id = 21921,
			task_txt = "/",
			award_txt = "10元JD卡",
			award_img = "ty_icon_jdek10",
			cost = 10,
			condi_show = "xsjkd_all_v1",
			condi_exchange = "actp_own_task_p_xsjdk_all_v1",
			exchange_vip = 1,
			limit_txt = "终身1次",
			all_num = "/",
		},
		[2]=
		{
			id = 2,
			task_id = 21922,
			task_txt = "/",
			award_txt = "20元JD卡",
			award_img = "ty_icon_jdek20",
			cost = 20,
			condi_show = "xsjkd_all_v1",
			condi_exchange = "actp_own_task_p_xsjdk_all_v2",
			exchange_vip = 2,
			limit_txt = "终身1次",
			all_num = "/",
		},
		[3]=
		{
			id = 3,
			task_id = 21923,
			task_txt = "任意游戏累计消耗100万鲸币",
			award_txt = "100元JD卡",
			award_img = "ty_icon_jdek100",
			cost = 100,
			condi_show = "xsjkd_all_v2",
			condi_exchange = "actp_own_task_p_xsjdk_all_v5",
			exchange_vip = 5,
			limit_txt = "每日1次",
			all_num = 5,
		},
		[4]=
		{
			id = 4,
			task_id = 21924,
			task_txt = "任意游戏累计消耗100万鲸币",
			award_txt = "100元JD卡",
			award_img = "ty_icon_jdek100",
			cost = 100,
			condi_show = "xsjkd_all_v3",
			condi_exchange = "actp_own_task_p_xsjdk_all_v6",
			exchange_vip = 6,
			limit_txt = "每日1次",
			all_num = 10,
		},
		[5]=
		{
			id = 5,
			task_id = 21925,
			task_txt = "任意游戏累计消耗100万鲸币",
			award_txt = "100元JD卡",
			award_img = "ty_icon_jdek100",
			cost = 100,
			condi_show = "xsjkd_all_v5",
			condi_exchange = "actp_own_task_p_xsjdk_all_v8",
			exchange_vip = 8,
			limit_txt = "每日1次",
			all_num = 20,
		},
		[6]=
		{
			id = 6,
			task_id = 21926,
			task_txt = "任意游戏累计消耗200万鲸币",
			award_txt = "200元JD卡",
			award_img = "ty_icon_jdek200",
			cost = 200,
			condi_show = "xsjkd_all_v3",
			condi_exchange = "actp_own_task_p_xsjdk_all_v5",
			exchange_vip = 5,
			limit_txt = "每日1次",
			all_num = 5,
		},
		[7]=
		{
			id = 7,
			task_id = 21927,
			task_txt = "任意游戏累计消耗200万鲸币",
			award_txt = "200元JD卡",
			award_img = "ty_icon_jdek200",
			cost = 200,
			condi_show = "xsjkd_nor_v6",
			condi_exchange = "actp_own_task_p_xsjdk_nor_v8",
			exchange_vip = 8,
			limit_txt = "每日1次",
			all_num = 10,
		},
		[8]=
		{
			id = 8,
			task_id = 21928,
			task_txt = "任意游戏累计消耗200万鲸币",
			award_txt = "200元JD卡",
			award_img = "ty_icon_jdek200",
			cost = 200,
			condi_show = "xsjkd_all_v8",
			condi_exchange = "actp_own_task_p_xsjdk_all_v10",
			exchange_vip = 10,
			limit_txt = "每日1次",
			all_num = 20,
		},
		[9]=
		{
			id = 9,
			task_id = 21929,
			task_txt = "任意游戏累计消耗200万鲸币",
			award_txt = "300元JD卡",
			award_img = "ty_icon_jdek300",
			cost = 300,
			condi_show = "xsjkd_all_v4",
			condi_exchange = "actp_own_task_p_xsjdk_all_v5",
			exchange_vip = 5,
			limit_txt = "每日1次",
			all_num = 5,
		},
		[10]=
		{
			id = 10,
			task_id = 21930,
			task_txt = "任意游戏累计消耗200万鲸币",
			award_txt = "300元JD卡",
			award_img = "ty_icon_jdek300",
			cost = 300,
			condi_show = "xsjkd_nor_v7",
			condi_exchange = "actp_own_task_p_xsjdk_nor_v8",
			exchange_vip = 8,
			limit_txt = "每日1次",
			all_num = 10,
		},
		[11]=
		{
			id = 11,
			task_id = 21931,
			task_txt = "任意游戏累计消耗200万鲸币",
			award_txt = "300元JD卡",
			award_img = "ty_icon_jdek300",
			cost = 300,
			condi_show = "xsjkd_nor_v9",
			condi_exchange = "actp_own_task_p_xsjdk_nor_v10",
			exchange_vip = 10,
			limit_txt = "每日3次",
			all_num = 20,
		},
	},
}