return {
    gift = {
        [1] = {
            index = 1,
            gift_id = 10897,
            price = 3,
            old_price = 7,
            award_name = {"5福卡赛门票", "猪头表情"},
            award_num = {"x8", "x2"},
            award_icon = {"com_award_icon_5ys", "pay_icon_pig"},
        },
        [2] = {
            index = 2,
            gift_id = 10277,
            price = 6,
            old_price = 12.5,
            award_name = {"20福卡赛门票", "5福卡赛门票", "记牌器"},
            award_num = {"x1", "x10", "3天"},
            award_icon = {"com_award_icon_20ys", "com_award_icon_5ys", "com_award_icon_jipaiqi"},
        },
        [3] = {
            index = 3,
            gift_id = 10898,
            price = 9,
            old_price = 18,
            award_name = {"20福卡赛门票", "记牌器", "猪头表情"},
            award_num = {"x4", "4天", "x3"},
            award_icon = {"com_award_icon_20ys", "com_award_icon_jipaiqi", "pay_icon_pig"},
        },
        [4] = {
            index = 4,
            gift_id = 10899,
            price = 15,
            old_price = 29,
            award_name = {"50福卡赛门票", "记牌器", "猪头表情"},
            award_num = {"x4", "6天", "x4"},
            award_icon = {"com_award_icon_50ys", "com_award_icon_jipaiqi", "pay_icon_pig"},
        },
        [5] = {
            index = 5,
            gift_id = 10278,
            price = 25,
            old_price = 51,
            award_name = {"50福卡赛门票", "20福卡赛门票", "千元赛门票", "记牌器"},
            award_num = {"x2", "x5", "x2", "4天"},
            award_icon = {"com_award_icon_50ys", "com_award_icon_20ys", "com_award_icon_qys", "com_award_icon_jipaiqi"},
        },
        [6] = {
            index = 6,
            gift_id = 10900,
            price = 30,
            old_price = 68,
            award_name = {"100福卡赛门票", "千元赛门票","记牌器", "猪头表情"},
            award_num = {"x2", "x1", "8天", "x15"},
            award_icon = {"com_award_icon_100ys", "com_award_icon_qys", "com_award_icon_jipaiqi", "pay_icon_pig"},
        },
        [7] = {
            index = 7,
            gift_id = 10279,
            price = 50,
            old_price = 100,
            award_name = {"100福卡赛门票", "50福卡赛门票", "千元赛门票", "记牌器"},
            award_num = {"x2", "x5", "x3", "10天"},
            award_icon = {"com_award_icon_100ys", "com_award_icon_50ys", "com_award_icon_qys", "com_award_icon_jipaiqi"},
        },
    }
}