return {
	base=
	{
		[1]=
		{
			index = 1,
			exchange_key = "exchange_yghhl",
			exchange_name = "阳光换好礼",
			type = 2,
			start_time = 1611617400,
			end_time = 1612195199,
			item_key = "prop_048_xxlqd_sunshine",
			item_name = "阳光",
			panel_txt_fmt = {"EAF2FF",},
			item_name_fmt = {"F9FFFF","5927CD",},
			item_comsume_fmt = {"5927CD",},
			exchange_ids = {1,2,3,4,5,},
			isOnOff = 0,
		},
		[2]=
		{
			index = 2,
			exchange_key = "exchange_xnhl",
			exchange_name = "新年好礼",
			type = 1,
			exchange_type = 27,
			start_time = 1612827000,
			end_time = 1613404799,
			item_key = "prop_fish_drop_act_0",
			item_name = "压岁钱",
			panel_txt_fmt = {"fff9b1","ae0d0d",},
			item_name_fmt = {"ae003a",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {6,7,8,9,10,11,12,13,14,},
			isOnOff = 0,
			help_info = {"1.活动时间：2月9日7:30~2月15日23:59:59",    "2.活动期间街机捕鱼小游戏中可获得压岁钱道具",    "3.活动结束后所有未使用的压岁钱道具将全部清除，请及时兑换",    "4.实物奖励请联系官方QQ公众号：4008882620领取，春节期间实物奖励延迟发放"},
			gotoUI = "game_FishingHall",
		},
		[3]=
		{
			index = 3,
			exchange_key = "exchange_ybdh",
			exchange_name = "元宝兑换",
			type = 1,
			exchange_type = 28,
			style_key = "act_003_ybdh",
			start_time = 1613431800,
			end_time = 1614009599,
			item_key = "prop_fish_drop_act_1",
			item_name = "银元宝",
			panel_txt_fmt = {"fff9b1","ae0d0d",},
			item_name_fmt = {"ae003a",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {15,16,17,18,19,20,21,22,},
			isOnOff = 0,
			gotoUI = "game_FishingHall",
		},
		[4]=
		{
			index = 4,
			exchange_key = "exchange_thsl",
			exchange_name = "桃花送礼",
			type = 1,
			exchange_type = 31,
			style_key = "act_004_thsl",
			start_time = 1615851000,
			end_time = 1616428799,
			item_key = "prop_fish_drop_act_0",
			item_name = "桃花",
			panel_txt_fmt = {"fff9b1","ae0d0d",},
			item_name_fmt = {"ae003a",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {23,24,25,26,27,28,29,30,},
			isOnOff = 0,
			help_info = {"1.活动时间：3月16日7:30~3月22日23:59:59","2.活动结束后所有未使用的桃花道具将全部清除，请及时使用","3.实物奖励请联系客服QQ公众号4008882620领取","4.实物图片仅供参考，请以实际收到的奖励为准",},
			gotoUI = "game_FishingHall",
		},
		[5]=
		{
			index = 5,
			exchange_key = "exchange_qmjz_hldh",
			exchange_name = "好礼兑换",
			type = 1,
			exchange_type = 32,
			style_key = "act_005_hldh",
			start_time = 1617060600,
			end_time = 1617638399,
			item_key = "prop_fish_drop_act_0",
			item_name = "菊花",
			panel_txt_fmt = {"fffff9",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {31,32,33,34,35,36,37,38,},
			isOnOff = 0,
			help_info = {"1.活动时间：3月30日7:30~4月5日23:59:59","2.活动结束后所有未使用的菊花道具将全部清除，请及时使用",},
			gotoUI = "game_FishingHall",
		},
		[6]=
		{
			index = 6,
			exchange_key = "exchange_khqd_hldh",
			exchange_name = "好礼兑换",
			type = 1,
			exchange_type = 33,
			style_key = "act_006_khqd_hldh",
			start_time = 1617665400,
			end_time = 1618243199,
			item_key = "prop_fish_drop_act_0",
			item_name = "气球",
			panel_txt_fmt = {"fffff9",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {39,40,41,42,43,44,45,46,},
			isOnOff = 0,
			help_info = {"1.活动时间：4月6日7:30~4月12日23:59:59","2.活动结束后所有未使用的气球道具将全部清除，请及时使用","3.实物奖励请联系客服QQ公众号4008882620领取","4.实物图片仅供参考，请以实际收到的奖励为准",},
			gotoUI = "game_FishingHall",
		},
		[7]=
		{
			index = 7,
			exchange_key = "exchange_fkxxl_yghhl",
			exchange_name = "阳光换好礼",
			type = 1,
			exchange_type = 34,
			style_key = "act_007_fkxxl_yghhl",
			start_time = 1618875000,
			end_time = 1619452799,
			item_key = "prop_fish_drop_act_0",
			item_name = "阳光",
			panel_txt_fmt = {"fffff9",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {47,48,49,50,51,52,53,54},
			isOnOff = 0,
			help_info = {"1.活动时间：4月20日7:30:00~4月26日23:59:59","2.兑换获得的积分奖励可参与“消消乐达人”活动","3.活动结束后将清除所有阳光道具，请及时使用",},
			gotoUI = "game_MiniGame",
		},
		[8]=
		{
			index = 8,
			exchange_key = "exchange_wykl_lwdh",
			exchange_name = "礼物兑换",
			type = 1,
			exchange_type = 35,
			style_key = "act_008_wykl_lwdh",
			start_time = 1619479800,
			end_time = 1620662399,
			item_key = "prop_fish_drop_act_0",
			item_name = "大红花",
			panel_txt_fmt = {"fffff9",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {55,56,57,58,59,60,61,62,63},
			isOnOff = 0,
			help_info = {"1.活动时间：4月27日7:30:00~5月10日23:59:59","2.兑换获得的积分奖励可参与“劳动模范”活动","3.活动结束后将清除所有红花道具，请及时使用",},
			gotoUI = "game_MiniGame",
		},
		[9]=
		{
			index = 9,
			exchange_key = "exchange_khqd_hldh_02",
			exchange_name = "好礼兑换",
			type = 1,
			exchange_type = 36,
			style_key = "act_032_qfdh",
			start_time = 1649115000,
			end_time = 1649692799,
			item_key = "prop_fish_drop_act_0",
			item_name = "菊花",
			panel_txt_fmt = {"ffffff","c25d20",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {64,65,66,67,68,69,70,71,72,73},
			isOnOff = 1,
			help_info = {"1.活动时间：4月5日7:30~4月11日23:59:59","2.兑换获得的积分奖励可参与“福气榜单”活动","3.所有小游戏均可获得活动道具","4.活动结束后将清除所有道具，请及时使用","5.注：利用游戏漏洞获得的一切奖励将全部被扣除",},
			gotoUI = "game_MiniGame",
		},
		[10]=
		{
			index = 10,
			exchange_key = "exchange_ymkh_jdhhl",
			exchange_name = "金豆换好礼",
			type = 1,
			exchange_type = 38,
			style_key = "act_010_ymkh_jdhhl",
			start_time = 1621899000,
			end_time = 1622476799,
			item_key = "prop_fish_drop_act_0",
			item_name = "金豆",
			panel_txt_fmt = {"fffff9",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {74,75,76,77,78,79,80,81},
			isOnOff = 0,
			help_info = {"1.活动时间：2021年5月25日7:30:00~2021年5月31日23:59:59","2.在街机捕鱼、所有消消乐、热血传奇、龙王争霸、疯狂捕鱼、敲敲乐、弹弹乐和盗墓笔记游戏中每累计消耗2万鲸币可获得1个金豆道具","3.兑换获得的积分奖励可参与“积分排行榜”活动","4.活动结束后将清除所有金豆道具，请及时使用",},
			gotoUI = "game_MiniGame",
		},
		[11]=
		{
			index = 11,
			exchange_key = "exchange_ymkh_jdhhl_tsqd",
			exchange_name = "金豆换好礼",
			type = 1,
			exchange_type = 37,
			style_key = "act_010_ymkh_jdhhl",
			start_time = 1621899000,
			end_time = 1622476799,
			item_key = "prop_fish_drop_act_0",
			item_name = "金豆",
			panel_txt_fmt = {"fffff9",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {74,75,76,77,78,79,80,81},
			isOnOff = 0,
			help_info = {"1.活动时间：2021年5月25日7:30:00~2021年5月31日23:59:59","2.在街机捕鱼、所有消消乐、热血传奇、龙王争霸、疯狂捕鱼、敲敲乐、弹弹乐和盗墓笔记游戏中每累计消耗4万鲸币可获得1个金豆道具","3.兑换获得的积分奖励可参与“积分排行榜”活动","4.活动结束后将清除所有金豆道具，请及时使用",},
			gotoUI = "game_MiniGame",
		},
		[12]=
		{
			index = 12,
			exchange_key = "exchange_etjkl_tkhhl",
			exchange_name = "糖果换好礼",
			type = 1,
			exchange_type = 39,
			style_key = "act_011_etjkl_tghhl",
			start_time = 1622503800,
			end_time = 1623081599,
			item_key = "prop_fish_drop_act_0",
			item_name = "棒棒糖",
			panel_txt_fmt = {"fffff9",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {82,83,84,85,86,87,88,89},
			isOnOff = 0,
			help_info = {"1.活动时间：2021年6月1日7:30:00~2021年6月7日23:59:59","2.在街机捕鱼、所有消消乐、热血传奇、龙王争霸、疯狂捕鱼、敲敲乐、弹弹乐、热血传奇和盗墓笔记游戏中均可获得棒棒糖道具","3.兑换获得的积分奖励可参与“积分排行榜”活动","4.活动结束后将清除所有棒棒糖道具，请及时使用",},
			gotoUI = "game_MiniGame",
		},
		[13]=
		{
			index = 13,
			exchange_key = "exchange_dwjj_xzhhl",
			exchange_name = "香粽换好礼",
			type = 1,
			exchange_type = 40,
			style_key = "act_012_dwjj_xzhhl",
			start_time = 1623108600,
			end_time = 1623686399,
			item_key = "prop_fish_drop_act_0",
			item_name = "粽子",
			panel_txt_fmt = {"fffff9",},
			item_name_fmt = {"fffff9","9c5a0d",},
			item_comsume_fmt = {"ae003a",},
			exchange_ids = {90,91,92,93,94,95,96,97},
			isOnOff = 0,
			help_info = {"1.活动时间：2021年6月8日7:30:00~2021年6月14日23:59:59","2.在街机捕鱼、所有消消乐、热血传奇、龙王争霸、疯狂捕鱼、敲敲乐、弹弹乐、热血传奇和盗墓笔记游戏中均可获得粽子道具","3.兑换获得的积分奖励可参与“积分排行榜”活动","4.活动结束后将清除所有粽子道具，请及时使用",},
			gotoUI = "game_MiniGame",
		},
	},
	exchanges=
	{
		[1]=
		{
			index = 1,
			ID = 1,
			award_name = "1万鲸币",
			price = 0,
			gift_id = 10588,
			award_image = "pay_icon_gold7",
			item_cost_text = 10,
			is_real = 0,
			limit_num = 1,
		},
		[2]=
		{
			index = 2,
			ID = 2,
			award_name = "28万鲸币",
			price = 18,
			gift_id = 10589,
			award_image = "pay_icon_gold8",
			item_cost_text = 200,
			is_real = 0,
			limit_num = 1,
		},
		[3]=
		{
			index = 3,
			ID = 3,
			award_name = "70万鲸币",
			price = 48,
			gift_id = 10590,
			award_image = "pay_icon_gold9",
			item_cost_text = 400,
			is_real = 0,
			limit_num = 3,
		},
		[4]=
		{
			index = 4,
			ID = 4,
			award_name = "145万鲸币",
			price = 98,
			gift_id = 10591,
			award_image = "pay_icon_gold10",
			item_cost_text = 800,
			is_real = 0,
			limit_num = 5,
		},
		[5]=
		{
			index = 5,
			ID = 5,
			award_name = "268万鲸币",
			price = 198,
			gift_id = 10592,
			award_image = "pay_icon_gold11",
			item_cost_text = 1200,
			is_real = 0,
			limit_num = 8,
		},
		[6]=
		{
			index = 6,
			ID = 1,
			award_name = "茅台抽奖券*3",
			award_image = "com_award_icon_dhq",
			item_cost_text = 50,
			is_real = 0,
			limit_num = 1,
			tips = {"茅台抽奖券","可参与“新年送茅台”活动"},
		},
		[7]=
		{
			index = 7,
			ID = 2,
			award_name = "10万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 1500,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[8]=
		{
			index = 8,
			ID = 3,
			award_name = "800话费碎片",
			award_image = "com_award_icon_hfsp2",
			item_cost_text = 2000,
			is_real = 0,
			limit_num = 1,
			tips = {"话费碎片","可兑换手机话费"},
		},
		[9]=
		{
			index = 9,
			ID = 4,
			award_name = "20元充值优惠券",
			award_image = "com_award_icon_czyhq3",
			item_cost_text = 2500,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣20元"},
		},
		[10]=
		{
			index = 10,
			ID = 5,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 7500,
			is_real = 0,
			limit_num = 2,
			tips = {"鲸币","游戏基础货币"},
		},
		[11]=
		{
			index = 11,
			ID = 6,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 8000,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可再兑换商城购买实物"},
		},
		[12]=
		{
			index = 12,
			ID = 7,
			award_name = "食用油",
			award_image = "activity_icon_gift251_jly",
			item_cost_text = 15000,
			is_real = 1,
			limit_num = 1,
			tips = {"食用油","葵花籽食用植物调和油"},
		},
		[13]=
		{
			index = 13,
			ID = 8,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold10",
			item_cost_text = 15000,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[14]=
		{
			index = 14,
			ID = 9,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold11",
			item_cost_text = 30000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[15]=
		{
			index = 15,
			ID = 1,
			award_name = "金元宝*10",
			award_image = "cssl_iocn_jyb",
			item_cost_text = 800,
			is_real = 0,
			limit_num = 3,
			tips = {"金元宝","可参与财神送礼抽奖"},
		},
		[16]=
		{
			index = 16,
			ID = 2,
			award_name = "金元宝*40",
			award_image = "cssl_iocn_jyb_1",
			item_cost_text = 4000,
			is_real = 0,
			tips = {"金元宝","可参与财神送礼抽奖"},
		},
		[17]=
		{
			index = 17,
			ID = 3,
			award_name = "5元充值优惠券",
			award_image = "com_award_icon_czyhq1",
			item_cost_text = 300,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣5元"},
		},
		[18]=
		{
			index = 18,
			ID = 4,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 600,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[19]=
		{
			index = 19,
			ID = 5,
			award_name = "20元充值优惠券",
			award_image = "com_award_icon_czyhq3",
			item_cost_text = 1200,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣20元"},
		},
		[20]=
		{
			index = 20,
			ID = 6,
			award_name = "50元充值优惠券",
			award_image = "com_award_icon_czyhq4",
			item_cost_text = 3000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣50元"},
		},
		[21]=
		{
			index = 21,
			ID = 7,
			award_name = "100元充值优惠券",
			award_image = "com_award_icon_czyhq5",
			item_cost_text = 6000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣100元"},
		},
		[22]=
		{
			index = 22,
			ID = 8,
			award_name = "200元充值优惠券",
			award_image = "com_award_icon_czyhq6",
			item_cost_text = 12000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣200元"},
		},
		[23]=
		{
			index = 23,
			ID = 1,
			award_name = "100话费碎片",
			award_image = "com_award_icon_hfsp2",
			item_cost_text = 500,
			is_real = 0,
			limit_num = 1,
			tips = {"话费碎片","可兑换手机话费"},
		},
		[24]=
		{
			index = 24,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[25]=
		{
			index = 25,
			ID = 3,
			award_name = "10万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 1200,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[26]=
		{
			index = 26,
			ID = 4,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 6000,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[27]=
		{
			index = 27,
			ID = 5,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 8000,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可再兑换商城购买实物"},
		},
		[28]=
		{
			index = 28,
			ID = 6,
			award_name = "大米",
			award_image = "activity_icon_gift269_jly",
			item_cost_text = 10000,
			is_real = 1,
			limit_num = 1,
			tips = {"大米","金龙鱼大米"},
		},
		[29]=
		{
			index = 29,
			ID = 7,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold10",
			item_cost_text = 12000,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[30]=
		{
			index = 30,
			ID = 8,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold11",
			item_cost_text = 24000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[31]=
		{
			index = 31,
			ID = 1,
			award_name = "5元充值优惠券",
			award_image = "com_award_icon_czyhq1",
			item_cost_text = 500,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣5元"},
		},
		[32]=
		{
			index = 32,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[33]=
		{
			index = 33,
			ID = 3,
			award_name = "20元充值优惠券",
			award_image = "com_award_icon_czyhq3",
			item_cost_text = 2000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣20元"},
		},
		[34]=
		{
			index = 34,
			ID = 4,
			award_name = "香*100",
			award_image = "com_award_icon_xiang",
			item_cost_text = 3000,
			is_real = 0,
			tips = {"香","用于参加祭祖祈福活动"},
		},
		[35]=
		{
			index = 35,
			ID = 5,
			award_name = "50元充值优惠券",
			award_image = "com_award_icon_czyhq4",
			item_cost_text = 5000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣50元"},
		},
		[36]=
		{
			index = 36,
			ID = 6,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 6000,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[37]=
		{
			index = 37,
			ID = 7,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold10",
			item_cost_text = 12000,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[38]=
		{
			index = 38,
			ID = 8,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold11",
			item_cost_text = 24000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[39]=
		{
			index = 39,
			ID = 1,
			award_name = "100话费碎片",
			award_image = "com_award_icon_hfsp2",
			item_cost_text = 500,
			is_real = 0,
			limit_num = 1,
			tips = {"话费碎片","可兑换手机话费"},
		},
		[40]=
		{
			index = 40,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[41]=
		{
			index = 41,
			ID = 3,
			award_name = "10万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 1200,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[42]=
		{
			index = 42,
			ID = 4,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold7",
			item_cost_text = 6000,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[43]=
		{
			index = 43,
			ID = 5,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 8000,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[44]=
		{
			index = 44,
			ID = 6,
			award_name = "大米",
			award_image = "activity_icon_gift269_jly",
			item_cost_text = 10000,
			is_real = 1,
			limit_num = 1,
			tips = {"大米","金龙鱼大米"},
		},
		[45]=
		{
			index = 45,
			ID = 7,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 12000,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[46]=
		{
			index = 46,
			ID = 8,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 24000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[47]=
		{
			index = 47,
			ID = 1,
			award_name = "1福卡",
			award_image = "ad_2znjnk_icon_fk1",
			item_cost_text = 120,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[48]=
		{
			index = 48,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[49]=
		{
			index = 49,
			ID = 3,
			award_name = "10万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 1200,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[50]=
		{
			index = 50,
			ID = 4,
			award_name = "20万鲸币",
			award_image = "pay_icon_gold7",
			item_cost_text = 2400,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[51]=
		{
			index = 51,
			ID = 5,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 6000,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[52]=
		{
			index = 52,
			ID = 6,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 8000,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[53]=
		{
			index = 53,
			ID = 7,
			award_name = "小太阳",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 10000,
			is_real = 1,
			limit_num = 1,
			tips = {"小太阳","小太阳一台"},
		},
		[54]=
		{
			index = 54,
			ID = 8,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold11",
			item_cost_text = 12000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[55]=
		{
			index = 55,
			ID = 1,
			award_name = "100话费碎片",
			award_image = "com_award_icon_hfsp2",
			item_cost_text = 500,
			ex_award_num = 5,
			is_real = 0,
			limit_num = 1,
			tips = {"话费碎片","可兑换手机话费"},
		},
		[56]=
		{
			index = 56,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			ex_award_num = 10,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[57]=
		{
			index = 57,
			ID = 3,
			award_name = "10万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 1200,
			ex_award_num = 12,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[58]=
		{
			index = 58,
			ID = 4,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold7",
			item_cost_text = 6000,
			ex_award_num = 60,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[59]=
		{
			index = 59,
			ID = 5,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 8000,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[60]=
		{
			index = 60,
			ID = 6,
			award_name = "大米",
			award_image = "activity_icon_gift269_jly",
			item_cost_text = 10000,
			is_real = 0,
			limit_num = 1,
			tips = {"大米","金龙鱼大米"},
		},
		[61]=
		{
			index = 61,
			ID = 7,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 12000,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[62]=
		{
			index = 62,
			ID = 8,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 24000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[63]=
		{
			index = 63,
			ID = 9,
			award_name = "VIVO z5x",
			award_image = "activity_icon_gift267_sqm",
			item_cost_text = 200000,
			is_real = 0,
			limit_num = 1,
			tips = {"vivo手机","vivo z5x手机一部"},
		},
		[64]=
		{
			index = 64,
			ID = 1,
			award_name = "狂暴卡*1",
			award_image = "by_btn_kb2",
			item_cost_text = 10,
			is_real = 0,
			tips = {"狂暴卡","子弹获得双倍威力，同时会提升消耗，持续15秒。"},
		},
		[65]=
		{
			index = 65,
			ID = 2,
			award_name = "加速卡*1",
			award_image = "by_btn_js2",
			item_cost_text = 10,
			is_real = 0,
			tips = {"加速卡","以1.5倍的速度进行发炮，持续15秒。"},
		},
		[66]=
		{
			index = 66,
			ID = 3,
			award_name = "1福卡",
			award_image = "ad_2znjnk_icon_fk1",
			item_cost_text = 120,
			ex_award_num = 30,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[67]=
		{
			index = 67,
			ID = 4,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			ex_award_num = 200,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[68]=
		{
			index = 68,
			ID = 5,
			award_name = "10万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 1200,
			ex_award_num = 240,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[69]=
		{
			index = 69,
			ID = 6,
			award_name = "20万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 2400,
			ex_award_num = 480,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[70]=
		{
			index = 70,
			ID = 7,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold7",
			item_cost_text = 6000,
			ex_award_num = 1200,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[71]=
		{
			index = 71,
			ID = 8,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk1",
			item_cost_text = 8000,
			ex_award_num = 1600,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[72]=
		{
			index = 72,
			ID = 9,
			award_name = "80万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 10000,
			ex_award_num = 2000,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[73]=
		{
			index = 73,
			ID = 10,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 12000,
			ex_award_num = 2400,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[74]=
		{
			index = 74,
			ID = 1,
			award_name = "100话费碎片",
			award_image = "com_award_icon_hfsp2",
			item_cost_text = 500,
			is_real = 0,
			limit_num = 1,
			tips = {"话费碎片","可兑换手机话费"},
		},
		[75]=
		{
			index = 75,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[76]=
		{
			index = 76,
			ID = 3,
			award_name = "30万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 3500,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[77]=
		{
			index = 77,
			ID = 4,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 6000,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[78]=
		{
			index = 78,
			ID = 5,
			award_name = "矿泉水",
			award_image = "activity_icon_gift229_yb",
			item_cost_text = 8000,
			is_real = 0,
			limit_num = 1,
			tips = {"矿泉水","矿泉水一份"},
		},
		[79]=
		{
			index = 79,
			ID = 6,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 12000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[80]=
		{
			index = 80,
			ID = 7,
			award_name = "太阳眼镜",
			award_image = "activity_icon_gift179_tyj",
			item_cost_text = 14000,
			is_real = 0,
			limit_num = 1,
			tips = {"太阳眼镜","太阳眼镜一副"},
		},
		[81]=
		{
			index = 81,
			ID = 8,
			award_name = "美的风扇",
			award_image = "activity_icon_gift153_fs",
			item_cost_text = 50000,
			is_real = 0,
			limit_num = 1,
			tips = {"美的风扇","美的风扇一个"},
		},
		[82]=
		{
			index = 82,
			ID = 1,
			award_name = "100话费碎片",
			award_image = "com_award_icon_hfsp2",
			item_cost_text = 500,
			is_real = 0,
			limit_num = 1,
			tips = {"话费碎片","可兑换手机话费"},
		},
		[83]=
		{
			index = 83,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[84]=
		{
			index = 84,
			ID = 3,
			award_name = "30万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 3500,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[85]=
		{
			index = 85,
			ID = 4,
			award_name = "旺仔QQ糖",
			award_image = "activity_icon_gift274_sqm",
			item_cost_text = 4000,
			is_real = 0,
			limit_num = 1,
			tips = {"旺仔QQ糖","旺仔QQ糖一份",},
		},
		[86]=
		{
			index = 86,
			ID = 5,
			award_name = "鸭舌帽",
			award_image = "activity_icon_gift276_sqm",
			item_cost_text = 5000,
			is_real = 0,
			limit_num = 1,
			tips = {"鸭舌帽","鸭舌帽一顶",},
		},
		[87]=
		{
			index = 87,
			ID = 6,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 6000,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[88]=
		{
			index = 88,
			ID = 7,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 12000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[89]=
		{
			index = 89,
			ID = 8,
			award_name = "智能手表",
			award_image = "activity_icon_gift275_sqm",
			item_cost_text = 50000,
			is_real = 0,
			limit_num = 1,
			tips = {"智能手表","智能手表一只",},
		},
		[90]=
		{
			index = 90,
			ID = 1,
			award_name = "100话费碎片",
			award_image = "com_award_icon_hfsp2",
			item_cost_text = 500,
			is_real = 0,
			limit_num = 1,
			tips = {"话费碎片","可兑换手机话费"},
		},
		[91]=
		{
			index = 91,
			ID = 2,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 1000,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[92]=
		{
			index = 92,
			ID = 3,
			award_name = "30万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 3500,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[93]=
		{
			index = 93,
			ID = 4,
			award_name = "U型颈枕",
			award_image = "activity_icon_gift233_uxjz",
			item_cost_text = 5000,
			is_real = 0,
			limit_num = 1,
			tips = {"U型颈枕","U型颈枕一个",},
		},
		[94]=
		{
			index = 94,
			ID = 5,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 6000,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[95]=
		{
			index = 95,
			ID = 6,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 12000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[96]=
		{
			index = 96,
			ID = 7,
			award_name = "空调被",
			award_image = "activity_icon_gift181_ktb",
			item_cost_text = 12000,
			is_real = 0,
			limit_num = 1,
			tips = {"空调被","空调被一份"},
		},
		[97]=
		{
			index = 97,
			ID = 8,
			award_name = "美的风扇",
			award_image = "activity_icon_gift153_fs",
			item_cost_text = 50000,
			is_real = 0,
			limit_num = 1,
			tips = {"美的风扇","美的风扇一个"},
		},
		[98]=
		{
			index = 98,
			ID = 1,
			award_name = "冰淇淋道具*10",
			award_image = "fkcdj_icon_bjl",
			item_cost_text = 200,
			is_real = 0,
			limit_num = 1,
			tips = {"冰淇淋道具","用于参加疯狂抽大奖活动"},
		},
		[99]=
		{
			index = 99,
			ID = 2,
			award_name = "初级充值加成卡*1",
			award_image = "czk_icon_l",
			item_cost_text = 1000,
			is_real = 0,
			tips = {"充值加成卡","使用后在充值商城中购买部分商品可获得额外加成，限时1小时。（不能和首冲加赠、充值优惠券同时使用）"},
		},
		[100]=
		{
			index = 100,
			ID = 3,
			award_name = "冰淇淋道具*100",
			award_image = "fkcdj_icon_bjl",
			item_cost_text = 2000,
			is_real = 0,
			tips = {"冰淇淋道具","用于参加疯狂抽大奖活动"},
		},
		[101]=
		{
			index = 101,
			ID = 4,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 12000,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[102]=
		{
			index = 102,
			ID = 5,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 24000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[103]=
		{
			index = 103,
			ID = 1,
			award_name = "1福卡",
			award_image = "ad_2znjnk_icon_fk1",
			item_cost_text = 120,
			ex_award_num = 20,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[104]=
		{
			index = 104,
			ID = 2,
			award_name = "5元充值优惠券",
			award_image = "com_award_icon_czyhq1",
			item_cost_text = 400,
			ex_award_num = 80,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣5元"},
		},
		[105]=
		{
			index = 105,
			ID = 3,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 800,
			ex_award_num = 160,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[106]=
		{
			index = 106,
			ID = 4,
			award_name = "初级充值加成卡*1",
			award_image = "czk_icon_l",
			item_cost_text = 1000,
			ex_award_num = 200,
			is_real = 0,
			tips = {"充值加成卡","使用后在充值商城中购买部分商品可获得额外加成，限时1小时。（不能和首冲加赠、充值优惠券同时使用）"},
		},
		[107]=
		{
			index = 107,
			ID = 5,
			award_name = "20元充值优惠券",
			award_image = "com_award_icon_czyhq3",
			item_cost_text = 1600,
			ex_award_num = 320,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣20元"},
		},
		[108]=
		{
			index = 108,
			ID = 6,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 6000,
			ex_award_num = 1200,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[109]=
		{
			index = 109,
			ID = 7,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk1",
			item_cost_text = 6000,
			ex_award_num = 1200,
			is_real = 0,
			limit_num = 3,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[110]=
		{
			index = 110,
			ID = 8,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 12000,
			ex_award_num = 2400,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[111]=
		{
			index = 111,
			ID = 9,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 24000,
			ex_award_num = 4800,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[112]=
		{
			index = 112,
			ID = 10,
			award_name = "500万鲸币",
			award_image = "pay_icon_gold10",
			item_cost_text = 55000,
			ex_award_num = 11000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[113]=
		{
			index = 113,
			ID = 11,
			award_name = "500福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 55000,
			ex_award_num = 11000,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[114]=
		{
			index = 114,
			ID = 12,
			award_name = "1000福卡",
			award_image = "ad_2znjnk_icon_fk3",
			item_cost_text = 100000,
			ex_award_num = 20000,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[115]=
		{
			index = 115,
			ID = 1,
			award_name = "抽奖券*10",
			award_image = "com_award_icon_dhq",
			item_cost_text = 200,
			ex_award_num = 40,
			is_real = 0,
			limit_num = 10,
			tips = {"抽奖券","用于参加周年抽大奖活动"},
		},
		[116]=
		{
			index = 116,
			ID = 2,
			award_name = "5元充值优惠券",
			award_image = "com_award_icon_czyhq1",
			item_cost_text = 400,
			ex_award_num = 80,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣5元"},
		},
		[117]=
		{
			index = 117,
			ID = 3,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 800,
			ex_award_num = 160,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[118]=
		{
			index = 118,
			ID = 4,
			award_name = "初级充值加成卡*1",
			award_image = "czk_icon_l",
			item_cost_text = 1000,
			ex_award_num = 200,
			is_real = 0,
			tips = {"充值加成卡","使用后在充值商城中购买部分商品可获得额外加成，限时1小时。（不能和首冲加赠、充值优惠券同时使用）"},
		},
		[119]=
		{
			index = 119,
			ID = 5,
			award_name = "20元充值优惠券",
			award_image = "com_award_icon_czyhq3",
			item_cost_text = 1600,
			ex_award_num = 320,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣20元"},
		},
		[120]=
		{
			index = 120,
			ID = 6,
			award_name = "抽奖券*100",
			award_image = "com_award_icon_dhq",
			item_cost_text = 2000,
			ex_award_num = 400,
			is_real = 0,
			tips = {"抽奖券","用于参加周年抽大奖活动"},
		},
		[121]=
		{
			index = 121,
			ID = 7,
			award_name = "50元充值优惠券",
			award_image = "com_award_icon_czyhq4",
			item_cost_text = 4000,
			ex_award_num = 800,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣50元"},
		},
		[122]=
		{
			index = 122,
			ID = 8,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 12000,
			ex_award_num = 2400,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[123]=
		{
			index = 123,
			ID = 9,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 24000,
			ex_award_num = 4800,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[124]=
		{
			index = 124,
			ID = 1,
			award_name = "1福卡",
			award_image = "ad_2znjnk_icon_fk1",
			item_cost_text = 120,
			ex_award_num = 30,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[125]=
		{
			index = 125,
			ID = 2,
			award_name = "5元充值优惠券",
			award_image = "com_award_icon_czyhq1",
			item_cost_text = 400,
			ex_award_num = 80,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣5元"},
		},
		[126]=
		{
			index = 126,
			ID = 3,
			award_name = "10元充值优惠券",
			award_image = "com_award_icon_czyhq2",
			item_cost_text = 800,
			ex_award_num = 160,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣10元"},
		},
		[127]=
		{
			index = 127,
			ID = 4,
			award_name = "10万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 1200,
			ex_award_num = 240,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[128]=
		{
			index = 128,
			ID = 5,
			award_name = "20元充值优惠券",
			award_image = "com_award_icon_czyhq3",
			item_cost_text = 1600,
			ex_award_num = 320,
			is_real = 0,
			tips = {"充值优惠券","商城充值时可抵扣20元"},
		},
		[129]=
		{
			index = 129,
			ID = 6,
			award_name = "高级充值加成卡*1",
			award_image = "czk_icon_h",
			item_cost_text = 2000,
			ex_award_num = 400,
			is_real = 0,
			tips = {"充值加成卡","使用后在充值商城中购买部分商品可获得额外加成，限时1小时。（不能和首冲加赠、充值优惠券同时使用）"},
		},
		[130]=
		{
			index = 130,
			ID = 7,
			award_name = "20万鲸币",
			award_image = "pay_icon_gold6",
			item_cost_text = 2400,
			ex_award_num = 480,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[131]=
		{
			index = 131,
			ID = 8,
			award_name = "护手霜",
			award_image = "activity_icon_gift309_hss",
			item_cost_text = 5000,
			ex_award_num = 1000,
			is_real = 1,
			limit_num = 1,
			tips = {"护手霜","护手霜一份"},
		},
		[132]=
		{
			index = 132,
			ID = 9,
			award_name = "50万鲸币",
			award_image = "pay_icon_gold8",
			item_cost_text = 6000,
			ex_award_num = 1200,
			is_real = 0,
			limit_num = 1,
			tips = {"鲸币","游戏基础货币"},
		},
		[133]=
		{
			index = 133,
			ID = 10,
			award_name = "50福卡",
			award_image = "ad_2znjnk_icon_fk2",
			item_cost_text = 6000,
			ex_award_num = 1200,
			is_real = 0,
			limit_num = 1,
			tips = {"福卡","可在兑换商城购买实物"},
		},
		[134]=
		{
			index = 134,
			ID = 11,
			award_name = "100万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 12000,
			ex_award_num = 2400,
			is_real = 0,
			limit_num = 3,
			tips = {"鲸币","游戏基础货币"},
		},
		[135]=
		{
			index = 135,
			ID = 12,
			award_name = "200万鲸币",
			award_image = "pay_icon_gold9",
			item_cost_text = 24000,
			ex_award_num = 4800,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
		[136]=
		{
			index = 136,
			ID = 13,
			award_name = "500万鲸币",
			award_image = "pay_icon_gold10",
			item_cost_text = 55000,
			ex_award_num = 11000,
			is_real = 0,
			tips = {"鲸币","游戏基础货币"},
		},
	},
}