return {
	config=
	{
		[1]=
		{
			id = 1,
			game_type = "game_DdzFree",
			game_name = "新手场",
			game_id = 1,
			order = 1,
			imageIndex = 1,
			base = 200,
			enterMin = 3000,
			enterMax = 30000,
			min_coin = 3000,
			max_coin = 30000,
			gift_id = 44,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 1,
			image = "hall_imgf_jdddz",
			isOnOff = 1,
			isLock = 0,
			 tag_image = "pp_icon_huob",
			max_rate = 12,
		},
		[2]=
		{
			id = 2,
			game_type = "game_DdzFree",
			game_name = "三星场",
			game_id = 2,
			order = 2,
			imageIndex = 2,
			base = 600,
			enterMin = 20000,
			enterMax = -1,
			min_coin = 20000,
			max_coin = -1,
			gift_id = 45,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 2,
			image = "hall_imgf_jdddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 24,
		},
		[3]=
		{
			id = 3,
			game_type = "game_DdzFreeER",
			game_name = "新手场",
			game_id = 5,
			order = 1,
			imageIndex = 1,
			base = 200,
			enterMin = 5000,
			enterMax = -1,
			min_coin = 5000,
			max_coin = -1,
			gift_id = 46,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 1,
			image = "hall_imgf_erddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 20,
		},
		[4]=
		{
			id = 4,
			game_type = "game_DdzFreeER",
			game_name = "三星场",
			game_id = 6,
			order = 2,
			imageIndex = 2,
			base = 600,
			enterMin = 20000,
			enterMax = -1,
			min_coin = 20000,
			max_coin = -1,
			gift_id = 47,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 2,
			image = "hall_imgf_erddz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 40,
		},
		[5]=
		{
			id = 5,
			game_type = "game_DdzLaizi",
			game_name = "新手场",
			game_id = 9,
			order = 1,
			imageIndex = 1,
			base = 200,
			enterMin = 10000,
			enterMax = -1,
			min_coin = 10000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 1,
			image = "hall_imgf_lz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 48,
		},
		[6]=
		{
			id = 6,
			game_type = "game_DdzLaizi",
			game_name = "三星场",
			game_id = 10,
			order = 2,
			imageIndex = 2,
			base = 800,
			enterMin = 50000,
			enterMax = -1,
			min_coin = 50000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 2,
			image = "hall_imgf_lz",
			isOnOff = 1,
			isLock = 0,
			max_rate = 96,
		},
		[7]=
		{
			id = 7,
			game_type = "game_MjXzER3D",
			game_name = "新手场",
			game_id = 13,
			order = 1,
			imageIndex = 1,
			base = 200,
			enterMin = 5000,
			enterMax = -1,
			min_coin = 5000,
			max_coin = -1,
			gift_id = 48,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 1,
			image = "hall_imgf_ermj",
			isOnOff = 1,
			isLock = 0,
			max_rate = 16,
		},
		[8]=
		{
			id = 8,
			game_type = "game_MjXzER3D",
			game_name = "三星场",
			game_id = 14,
			order = 2,
			imageIndex = 2,
			base = 1000,
			enterMin = 20000,
			enterMax = -1,
			min_coin = 20000,
			max_coin = -1,
			gift_id = 49,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 2,
			image = "hall_imgf_ermj",
			isOnOff = 1,
			isLock = 0,
			max_rate = 32,
		},
		[9]=
		{
			id = 9,
			game_type = "game_Mj3D",
			game_name = "新手场",
			game_id = 17,
			order = 1,
			imageIndex = 1,
			base = 200,
			enterMin = 3000,
			enterMax = 30000,
			min_coin = 3000,
			max_coin = 30000,
			gift_id = 50,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 1,
			image = "hall_imgf_xz",
			isOnOff = 1,
			isLock = 0,
			 tag_image = "pp_icon_huob",
			play_type = "换三张",
			max_rate = 16,
		},
		[10]=
		{
			id = 10,
			game_type = "game_Mj3D",
			game_name = "三星场",
			game_id = 18,
			order = 2,
			imageIndex = 2,
			base = 600,
			enterMin = 20000,
			enterMax = -1,
			min_coin = 20000,
			max_coin = -1,
			gift_id = 51,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 2,
			image = "hall_imgf_xz",
			isOnOff = 1,
			isLock = 0,
			play_type = "换三张",
			max_rate = 32,
		},
		[11]=
		{
			id = 11,
			game_type = "game_DdzFreeTF",
			game_name = "新手场",
			game_id = 21,
			order = 1,
			imageIndex = 1,
			base = 300,
			enterMin = 5000,
			enterMax = -1,
			min_coin = 5000,
			max_coin = -1,
			gift_id = 52,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 1,
			image = "hall_imgf_cy",
			isOnOff = 1,
			isLock = 0,
			max_rate = 32,
		},
		[12]=
		{
			id = 12,
			game_type = "game_DdzFreeTF",
			game_name = "三星场",
			game_id = 22,
			order = 2,
			imageIndex = 2,
			base = 1000,
			enterMin = 30000,
			enterMax = -1,
			min_coin = 30000,
			max_coin = -1,
			gift_id = 53,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 2,
			image = "hall_imgf_cy",
			isOnOff = 1,
			isLock = 0,
			max_rate = 64,
		},
		[13]=
		{
			id = 13,
			game_type = "game_Gobang",
			game_name = "五子棋",
			game_id = 25,
			order = 1,
			imageIndex = 1,
			base = 3000,
			enterMin = 3400,
			enterMax = -1,
			min_coin = 3400,
			max_coin = -1,
			gift_id = 54,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 1,
			image = "hall_imgf_wzq",
			isOnOff = 1,
			isLock = 0,
			max_rate = 1,
		},
		[14]=
		{
			id = 14,
			game_type = "game_MjXl3D",
			game_name = "血流",
			game_id = 29,
			order = 1,
			imageIndex = 1,
			base = 800,
			enterMin = 5000,
			enterMax = -1,
			min_coin = 5000,
			max_coin = -1,
			pay_id = 0,
			diamond_id = 1,
			image = "hall_imgf_xl",
			isOnOff = 1,
			isLock = 0,
			max_rate = 32,
		},
		[15]=
		{
			id = 15,
			game_type = "game_DdzFreeBomb",
			game_name = "新手场",
			game_id = 33,
			order = 1,
			imageIndex = 1,
			base = 100,
			enterMin = 5000,
			enterMax = -1,
			min_coin = 5000,
			max_coin = -1,
			gift_id = 55,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 1,
			image = "hall_imgf_zd",
			isOnOff = 1,
			isLock = 0,
			max_rate = 48,
		},
		[16]=
		{
			id = 16,
			game_type = "game_DdzFreeBomb",
			game_name = "三星场",
			game_id = 34,
			order = 2,
			imageIndex = 2,
			base = 500,
			enterMin = 30000,
			enterMax = -1,
			min_coin = 30000,
			max_coin = -1,
			gift_id = 56,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 2,
			image = "hall_imgf_zd",
			isOnOff = 1,
			isLock = 0,
			max_rate = 96,
		},
		[17]=
		{
			id = 17,
			game_type = "game_DdzPDK",
			game_name = "新手场",
			game_id = 37,
			order = 1,
			imageIndex = 1,
			base = 200,
			enterMin = 3000,
			enterMax = 30000,
			min_coin = 3000,
			max_coin = 30000,
			gift_id = 50,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 1,
			image = "hall_imgf_zd",
			isOnOff = 1,
			isLock = 0,
			max_rate = 48,
		},
		[18]=
		{
			id = 18,
			game_type = "game_DdzPDK",
			game_name = "三星场",
			game_id = 38,
			order = 2,
			imageIndex = 2,
			base = 600,
			enterMin = 20000,
			enterMax = -1,
			min_coin = 20000,
			max_coin = -1,
			gift_id = 47,
			pay_id = 1,
			ios_pay_id = 101,
			diamond_id = 2,
			image = "hall_imgf_zd",
			isOnOff = 1,
			isLock = 0,
			max_rate = 96,
		},
	},
}