--[[
state: 1开启 2未开启 3尽请期待
type:  1斗地主 2麻将
]]--

-- SceneName=场景名称，也就是要跳转的游戏场景
GameSceneCfg = {
	[0] = {ID = 0, PanelName = "HallPanel", SceneName = "game_Hall", GameTitle = "大厅", GameName = "大厅", BtnName = nil, BtnType = "spine", Image = "hall_btn_match"},
	[1] = {ID = 1, PanelName = "HallPanel", SceneName = "game_DdzMatch", GameTitle = "锦标赛", GameName = "斗地主比赛场", BtnName = nil, BtnType = "spine", Image = "hall_btn_match"},
	[2] = {ID = 2, PanelName = "HallPanel", SceneName = "game_DdzFree", GameTitle = "练习场", GameName = "斗地主匹配场", BtnName = nil, BtnType = "", Image = "hall_btn_novice"},
	[3] = {ID = 3, PanelName = "HallPanel", SceneName = "game_DdzMillion", GameTitle = "百万大奖赛", GameName = "百万大奖赛", BtnName = nil, BtnType = "", Image = "hall_btn_million"},

	[4] = {ID = 4, PanelName = "", SceneName = "game_DdzFree", GameTitle = "经典斗地主", GameName = "斗地主匹配场", BtnName = "CenterRect/JDButton", BtnType = "spine", Image = "matching_btn_jd"},
	[5] = {ID = 5, PanelName = "", SceneName = "game_DdzFree", GameTitle = "癞子斗地主", GameName = "癞子斗地主匹配场", BtnName = "CenterRect/LZButton", BtnType = "spine", Image = "matching_btn_lz"},
	[6] = {ID = 6, PanelName = "", SceneName = "game_DdzTy", GameTitle = "听用斗地主", GameName = "斗地主听用场", BtnName = "CenterRect/TYButton", BtnType = "", Image = "matching_btn_ty"},
	[7] = {ID = 7, PanelName = "", SceneName = "game_DdzFree", GameTitle = "练习场", GameName = "斗地主匹配场", BtnName = "CenterRect/LXButton", BtnType = "", Image = "matching_btn_qidai"},
	[8] = {ID = 8, PanelName = "", SceneName = "game_Mj3D", GameTitle = "血战到底", GameName = "麻将匹配场", BtnName = "CenterRect/XZButton", BtnType = "", Image = "matching_btn_xz"},
	[9] = {ID = 9, PanelName = "", SceneName = "game_MjXl3D", GameTitle = "血流到底", GameName = "麻将血流匹配场", BtnName = "CenterRect/XLButton", BtnType = "", Image = "matching_btn_xl"},
	[10] = {ID = 10, PanelName = "", SceneName = "", GameTitle = nil, GameName = "期待", BtnName = nil, BtnType = "", Image = "matching_btn_qidai"},
	[11] = {ID = 11, PanelName = "", SceneName = "", GameTitle = nil, GameName = "期待", BtnName = nil, BtnType = "", Image = "matching_btn_qidai"},
	[12] = {ID = 12, PanelName = "", SceneName = "game_MjXzFK3D", GameTitle = "血战到底房卡场", GameName = "血战到底房卡场", BtnName = nil, BtnType = "", Image = ""},
	[13] = {ID = 13, PanelName = "", SceneName = "game_DdzFK", GameTitle = "斗地主房卡场", GameName = "斗地主房卡场", BtnName = nil, BtnType = "", Image = ""},
	[14] = {ID = 14, PanelName = "HallPanel", SceneName = "game_CityMatch", GameTitle = "鲸鱼杯", GameName = "斗地主鲸鱼杯", BtnName = "@RectLeft/@city_activity_btn", BtnType = "", Image = ""},
	[15] = {ID = 15, PanelName = "HallPanel", SceneName = "game_DdzMatch", GameTitle = "2人斗地主比赛场", GameName = "2人斗地主比赛场", BtnName = "", BtnType = "", Image = ""},
	[16] = {ID = 16, PanelName = "HallPanel", SceneName = "game_MjXzMatchER3D", GameTitle = "4人血战麻将比赛场", GameName = "4人血战麻将比赛场", BtnName = "", BtnType = "", Image = ""},
	[17] = {ID = 17, PanelName = "HallPanel", SceneName = "game_DdzFree", GameTitle = "2人斗地主匹配场", GameName = "2人斗地主匹配场", BtnName = "", BtnType = "", Image = ""},
	[18] = {ID = 18, PanelName = "HallPanel", SceneName = "game_Mj3D", GameTitle = "2人麻将匹配场", GameName = "2人麻将匹配场", BtnName = "", BtnType = "", Image = ""},
	[19] = {ID = 19, PanelName = "HallPanel", SceneName = "game_Free", GameTitle = "匹配界面", GameName = "匹配界面", BtnName = "", BtnType = "", Image = ""},
	[20] = {ID = 20, PanelName = "HallPanel", SceneName = "game_MatchHall", GameTitle = "比赛界面", GameName = "比赛界面", BtnName = "", BtnType = "", Image = ""},
	[21] = {ID = 21, PanelName = "HallPanel", SceneName = "game_DdzMatch", GameTitle = "冠名赛", GameName = "斗地主冠名赛场", BtnName = nil, BtnType = "spine", Image = "hall_btn_match"},
	[22] = {ID = 22, PanelName = "HallPanel", SceneName = "game_MjXzMatchER3D", GameTitle = "血战麻将比赛场", GameName = "血战麻将比赛场", BtnName = "", BtnType = "", Image = ""},
	[23] = {ID = 23, PanelName = "HallPanel", SceneName = "game_DdzFree", GameTitle = "天府斗地主", GameName = "天府斗地主", BtnName = "", BtnType = "", Image = ""},
	[24] = {ID = 24, PanelName = "HallPanel", SceneName = "game_MjXzMatchER3D", GameTitle = "麻将冠名赛场", GameName = "麻将冠名赛场", BtnName = "", BtnType = "", Image = ""},
	[25] = {ID = 25, PanelName = "HallPanel", SceneName = "game_Gobang", GameTitle = "五子棋", GameName = "五子棋", BtnName = "", BtnType = "", Image = ""},
	[26] = {ID = 26, PanelName = "", SceneName = "game_DdzFree", GameTitle = "经典斗地主", GameName = "斗地主匹配场", BtnName = "CenterRect/JDButton", BtnType = "spine", Image = "matching_btn_jd"},
	[27] = {ID = 27, PanelName = "HallPanel", SceneName = "game_Fishing", GameTitle = "捕鱼游戏", GameName = "捕鱼游戏", BtnName = "", BtnType = "", Image = ""},
	[28] = {ID = 28, PanelName = "HallPanel", SceneName = "game_FishingHall", GameTitle = "打鱼大厅", GameName = "打鱼大厅", BtnName = "", BtnType = "", Image = ""},
	[29] = {ID = 29, PanelName = "Eliminate", SceneName = "game_Eliminate", GameTitle = "消消乐", GameName = "消消乐", BtnName = "", BtnType = "", Image = ""},
	[30] = {ID = 30, PanelName = "MiniGameHallPanel", SceneName = "game_MiniGame", GameTitle = "小游戏", GameName = "小游戏", BtnName = "", BtnType = "", Image = ""},
	[31] = {ID = 31, PanelName = "ShatterGoldenEggPanel", SceneName = "game_Zjd", GameTitle = "敲敲乐", GameName = "敲敲乐", BtnName = "", BtnType = "", Image = ""},
	[32] = {ID = 32, PanelName = "HallPanel", SceneName = "game_FishingDR", GameTitle = "疯狂捕鱼", GameName = "疯狂捕鱼", BtnName = "", BtnType = "", Image = ""},
	[33] = {ID = 33, PanelName = "HallPanel", SceneName = "game_FishingMatch", GameTitle = "捕鱼比赛", GameName = "捕鱼比赛", BtnName = "", BtnType = "", Image = ""},
	[34] = {ID = 34, PanelName = "HallPanel", SceneName = "game_EliminateSH", GameTitle = "水浒消消乐", GameName = "水浒消消乐", BtnName = "", BtnType = "", Image = ""},
	[35] = {ID = 35, PanelName = "HallPanel", SceneName = "game_DdzPDK", GameTitle = "跑得快", GameName = "跑得快", BtnName = "", BtnType = "", Image = ""},
	[36] = {ID = 36, PanelName = "HallPanel", SceneName = "game_LHD", GameTitle = "金蛋大乱斗", GameName = "金蛋大乱斗", BtnName = "", BtnType = "", Image = ""},
	[37] = {ID = 37, PanelName = "HallPanel", SceneName = "game_LHDHall", GameTitle = "金蛋大乱斗大厅", GameName = "金蛋大乱斗大厅", BtnName = "", BtnType = "", Image = ""},
	[38] = {ID = 38, PanelName = "HallPanel", SceneName = "game_DdzPDKMatch", GameTitle = "跑得快锦标赛", GameName = "跑得快锦标赛", BtnName = "", BtnType = "", Image = ""},
	[39] = {ID = 39, PanelName = "HallPanel", SceneName = "game_QHB", GameTitle = "抢福卡", GameName = "抢福卡", BtnName = "", BtnType = "", Image = ""},
	[40] = {ID = 40, PanelName = "HallPanel", SceneName = "game_QHBHall", GameTitle = "抢福卡大厅", GameName = "抢福卡", BtnName = "", BtnType = "", Image = ""},
	[41] = {ID = 41, PanelName = "HallPanel", SceneName = "game_Fishing3DHall", GameTitle = "3D打鱼大厅", GameName = "3D打鱼大厅", BtnName = "", BtnType = "", Image = ""},
	[42] = {ID = 42, PanelName = "HallPanel", SceneName = "game_Fishing3D", GameTitle = "3D捕鱼游戏", GameName = "3D捕鱼游戏", BtnName = "", BtnType = "", Image = ""},
	[43] = {ID = 41, PanelName = "HallPanel", SceneName = "game_EliminateCS", GameTitle = "财神消消乐", GameName = "财神消消乐", BtnName = "", BtnType = "", Image = ""},
	[44] = {ID = 44, PanelName = "HallPanel", SceneName = "game_TTL", GameTitle = "弹弹乐", GameName = "弹弹乐", BtnName = "", BtnType = "", Image = ""},
	[45] = {ID = 45, PanelName = "HallPanel", SceneName = "game_ZPG", GameTitle = "苹果大战", GameName = "苹果大战", BtnName = "", BtnType = "", Image = ""},

	[46] = {ID = 46, PanelName = "HallPanel", SceneName = "game_DdzZJF", GameTitle = "二人斗地主自建房", GameName = "二人斗地主自建房", BtnName = "", BtnType = "", Image = ""},
	[47] = {ID = 47, PanelName = "HallPanel", SceneName = "game_DdzZJF", GameTitle = "炸弹斗地主自建房", GameName = "炸弹斗地主自建房", BtnName = "", BtnType = "", Image = ""},
	[48] = {ID = 48, PanelName = "HallPanel", SceneName = "game_ZJF", GameTitle = "自建房匹配界面", GameName = "自建房匹配界面", BtnName = "", BtnType = "", Image = ""},
	[49] = {ID = 49, PanelName = "HallPanel", SceneName = "game_DdzZJF", GameTitle = "经典斗地主自建房", GameName = "经典斗地主自建房", BtnName = "", BtnType = "", Image = ""},
	[50] = {ID = 50, PanelName = "HallPanel", SceneName = "game_DdzZJF", GameTitle = "癞子斗地主自建房", GameName = "癞子斗地主自建房", BtnName = "", BtnType = "", Image = ""},
	[51] = {ID = 51, PanelName = "HallPanel", SceneName = "game_MJXzZJF3D", GameTitle = "麻将血战到底自建房", GameName = "麻将血战到底自建房", BtnName = "", BtnType = "", Image = ""},
	[52] = {ID = 52, PanelName = "HallPanel", SceneName = "game_MJXzZJF3D", GameTitle = "二人麻将自建房", GameName = "二人麻将自建房", BtnName = "", BtnType = "", Image = ""},
	[53] = {ID = 53, PanelName = "HallPanel", SceneName = "game_EliminateXY", GameTitle = "西游消消乐", GameName = "西游消消乐", BtnName = "", BtnType = "", Image = ""},
	[54] = {ID = 54, PanelName = "HallPanel", SceneName = "game_EliminateCJ", GameTitle = "超级消消乐", GameName = "超级消消乐", BtnName = "", BtnType = "", Image = ""},
	[55] = {ID = 55, PanelName = "HallPanel", SceneName = "game_LWZBHall", GameTitle = "龙王争霸大厅", GameName = "龙王争霸大厅", BtnName = "", BtnType = "", Image = ""},
	[56] = {ID = 56, PanelName = "HallPanel", SceneName = "game_LWZB", GameTitle = "龙王争霸", GameName = "龙王争霸", BtnName = "", BtnType = "", Image = ""},
	[57] = {ID = 57, PanelName = "HallPanel", SceneName = "game_DMBJ", GameTitle = "寻龙摸金", GameName = "寻龙摸金", BtnName = "", BtnType = "", Image = ""},
	[58] = {ID = 58, PanelName = "HallPanel", SceneName = "game_RXCQ", GameTitle = "热血传奇", GameName = "热血传奇", BtnName = "", BtnType = "", Image = ""},
	[59] = {ID = 59, PanelName = "HallPanel", SceneName = "game_EliminateSG", GameTitle = "三国消消乐", GameName = "三国消消乐"},
	[60] = {ID = 60, PanelName = "HallPanel", SceneName = "game_EliminateBS", GameTitle = "宝石迷阵", GameName = "宝石迷阵"},
	[61] = {ID = 61, PanelName = "HallPanel", SceneName = "game_EliminateFX", GameTitle = "福星高照", GameName = "福星高照"},

	[100] = {ID = 100, PanelName = "HallPanel", SceneName = "game_FishingTest", GameTitle = "捕鱼调试", GameName = "捕鱼调试", BtnName = "", BtnType = "", Image = ""},
}


-- key=游戏类型名称 value=游戏配置
GameConfigToSceneCfg = {
	game_Hall = GameSceneCfg[0],
	game_DdzMatch = GameSceneCfg[1],
	game_DdzMillion = GameSceneCfg[3],
	game_DdzFree = GameSceneCfg[4],
	game_DdzLaizi = GameSceneCfg[5],
	game_DdzTy = GameSceneCfg[6],

	game_Mj3D = GameSceneCfg[8],
	game_MjXl3D = GameSceneCfg[9],
	game_MjXzFK3D = GameSceneCfg[12],

	game_DdzFK = GameSceneCfg[13],
	game_CityMatch = GameSceneCfg[14],
	game_DdzMatchER = GameSceneCfg[15],
	game_MjXzMatchER3D = GameSceneCfg[16],
	game_DdzFreeER = GameSceneCfg[17],
	game_MjXzER3D = GameSceneCfg[18],
	game_Free = GameSceneCfg[19],
	game_MatchHall = GameSceneCfg[20],
	game_MjXzMatch3D = GameSceneCfg[22],
	game_DdzFreeTF = GameSceneCfg[23],
	game_MjMatchNaming = GameSceneCfg[24],
	game_Gobang = GameSceneCfg[25],
	game_DdzFreeBomb = GameSceneCfg[26],
	game_Fishing = GameSceneCfg[27],
	game_FishingHall = GameSceneCfg[28],
	game_Eliminate = GameSceneCfg[29],
	game_MiniGame = GameSceneCfg[30],
	game_Zjd = GameSceneCfg[31],
	game_FishingDR = GameSceneCfg[32],
	game_FishingMatch = GameSceneCfg[33],
	game_EliminateSH = GameSceneCfg[34],
	game_DdzPDK = GameSceneCfg[35],
	game_LHD = GameSceneCfg[36],
	game_LHDHall = GameSceneCfg[37],
	game_DdzPDKMatch = GameSceneCfg[38],
	game_QHB = GameSceneCfg[39],
	game_QHBHall = GameSceneCfg[40],
	game_Fishing3DHall = GameSceneCfg[41],
	game_Fishing3D = GameSceneCfg[42],
	game_EliminateCS = GameSceneCfg[43],
	game_TTL= GameSceneCfg[44],
	game_ZPG = GameSceneCfg[45],
	game_DdzZJF = GameSceneCfg[49],
	game_ZJF = GameSceneCfg[48],
	game_DdzLaiziZJF = GameSceneCfg[50],
	game_DdzERZJF = GameSceneCfg[46],
	game_DdzBombZJF = GameSceneCfg[47],
	game_Mj3dERZJF = GameSceneCfg[52],
	game_MJXzZJF3D = GameSceneCfg[51],
	game_Mj3dXZDDZJF = GameSceneCfg[51],
	game_EliminateXY = GameSceneCfg[53],
	game_EliminateCJ = GameSceneCfg[54],
	game_LWZBHall = GameSceneCfg[55],
	game_LWZB = GameSceneCfg[56],
	game_DMBJ = GameSceneCfg[57],
	game_RXCQ = GameSceneCfg[58],
	game_EliminateSG = GameSceneCfg[59],
	game_EliminateBS = GameSceneCfg[60],
	game_EliminateFX = GameSceneCfg[61],
	game_FishingTest = GameSceneCfg[100],
}