return {
	Sheet1=
	{
		[1]=
		{
			line = 1,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10338,10339,10340},
			bg_img = "sxlb_bg_1",
			db_img = {"sxlb_bg_4","sxlb_bg_3","sxlb_bg_2",},
			enter_icon = "sxlb_icon_sxlb",
			name_txt = {"18万鲸币","30万鲸币","48万鲸币"},
			is_hz = 1,
			name_c = "FFFAE1FF",
			font_c = "FFFAE1FF",
			outline_c = "DA5C17FF",
			gift_c = "FFF5F5FF",
			pay_name = {"18万鲸币","翻倍铜卡*1","30万鲸币","翻倍银卡*1","48万鲸币","翻倍金卡*1",},
			icon_img = {"pay_icon_gold7","sxlb_icon_tk","pay_icon_gold8","sxlb_icon_yk","pay_icon_gold9","sxlb_icon_jk",},
			isOnOff = 1,
		},
		[2]=
		{
			line = 2,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10341,10342,10343},
			bg_img = "sxlb_bg_1",
			db_img = {"sxlb_bg_4","sxlb_bg_3","sxlb_bg_2",},
			enter_icon = "sxlb_icon_sxlb",
			name_txt = {"48万鲸币","98万鲸币","198万鲸币"},
			is_hz = 1,
			name_c = "FFFAE1FF",
			font_c = "FFFAE1FF",
			outline_c = "DA5C17FF",
			gift_c = "FFF5F5FF",
			pay_name = {"48万鲸币","翻倍铜卡*2","98万鲸币","翻倍银卡*3","198万鲸币","翻倍金卡*4",},
			icon_img = {"pay_icon_gold7","sxlb_icon_tk","pay_icon_gold8","sxlb_icon_yk","pay_icon_gold9","sxlb_icon_jk",},
			isOnOff = 1,
		},
		[3]=
		{
			line = 3,
			gift_key = "gift_cglb",
			temp = "T4",
			gift_id = {10344,10345,10346},
			bg_img = "sxlb_bg_1",
			db_img = {"sxlb_bg_4","sxlb_bg_3","sxlb_bg_2",},
			enter_icon = "sxlb_icon_sxlb",
			name_txt = {"98万鲸币","198万鲸币","498万鲸币"},
			is_hz = 1,
			name_c = "FFFAE1FF",
			font_c = "FFFAE1FF",
			outline_c = "DA5C17FF",
			gift_c = "FFF5F5FF",
			pay_name = {"98万鲸币","翻倍铜卡*5","198万鲸币","翻倍银卡*6","498万鲸币","翻倍金卡*8",},
			icon_img = {"pay_icon_gold7","sxlb_icon_tk","pay_icon_gold8","sxlb_icon_yk","pay_icon_gold9","sxlb_icon_jk",},
			isOnOff = 1,
		},
	},
}