return {
	config=
	{
		[1]=
		{
			line = 1,
			order = 52,
			tag = 1,
			icon = "3dby_icon_yu1",
			name = "蝴蝶鱼",
			scale = 8,
			rotation = {66,0,0},
			rate = "3倍",
			prefab = "Fish3D001",
			tips = "身型小巧，自认为很可爱，常说是海中的小公主。",
		},
		[2]=
		{
			line = 2,
			order = 50,
			tag = 1,
			icon = "3dby_icon_yu2",
			name = "蜻蜓鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "2倍",
			prefab = "Fish3D002",
			tips = "总是成群结队，长得像海草一样的绿色，喜欢躲在草里玩捉迷藏。",
		},
		[3]=
		{
			line = 3,
			order = 48,
			tag = 1,
			icon = "3dby_icon_yu3",
			name = "热带黄鱼",
			scale = 8,
			rotation = {66,0,0},
			rate = "5倍",
			prefab = "Fish3D004",
			tips = "同样喜欢晒太阳，但聪明的她总会选择隐秘的地方享受。",
		},
		[4]=
		{
			line = 4,
			order = 46,
			tag = 1,
			icon = "3dby_icon_yu4",
			name = "大眼金鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "7倍",
			prefab = "Fish3D005",
			tips = "天生长者一对大眼睛，一脸无辜的样子让人不忍心捕捉。",
		},
		[5]=
		{
			line = 5,
			order = 44,
			tag = 1,
			icon = "3dby_icon_yu5",
			name = "狮头鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "8倍",
			prefab = "Fish3D006",
			tips = "骄傲自大，总认为自己是海底的霸主，常常自找苦头。",
		},
		[6]=
		{
			line = 6,
			order = 42,
			tag = 1,
			icon = "3dby_icon_yu6",
			name = "七彩鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "9倍",
			prefab = "Fish3D007",
			tips = "优哉游哉，与世无争，但是聪明过人，只是一点脾气都没有。",
		},
		[7]=
		{
			line = 7,
			order = 40,
			tag = 1,
			icon = "3dby_icon_yu7",
			name = "小丑鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "6倍",
			prefab = "Fish3D008",
			tips = "机智聪明，调皮好动，加上可爱的外表，一直深受大家喜爱。",
		},
		[8]=
		{
			line = 8,
			order = 38,
			tag = 1,
			icon = "3dby_icon_yu8",
			name = "河豚",
			scale = 3,
			rotation = {66,0,0},
			rate = "200倍",
			prefab = "Fish3D009",
			tips = "性格倔强，掉落金币后，会奋发图强，不仅体形会变大，分支也会变高，知道它体力不支为止。",
		},
		[9]=
		{
			line = 9,
			order = 36,
			tag = 1,
			icon = "3dby_icon_yu9",
			name = "孔雀鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "20倍",
			prefab = "Fish3D010",
			tips = "孔雀鱼对于任何事物似乎都不感兴趣，当然这只有在他吃饱以后。",
		},
		[10]=
		{
			line = 10,
			order = 34,
			tag = 1,
			icon = "3dby_icon_yu10",
			name = "小青蛙",
			scale = 5,
			rotation = {66,0,0},
			rate = "10倍",
			prefab = "Fish3D011",
			tips = "小青蛙一直是海里的广播员，只要他知道的事情大家也会第一时间知道。",
		},
		[11]=
		{
			line = 11,
			order = 32,
			tag = 1,
			icon = "3dby_icon_yu11",
			name = "龙虾",
			scale = 3,
			rotation = {0,0,0},
			rate = "68倍",
			prefab = "Fish3D013",
			tips = "适应力非常强，甚至能爬上岸，最大的乐趣就是进行冒险。",
		},
		[12]=
		{
			line = 12,
			order = 30,
			tag = 1,
			icon = "3dby_icon_yu12",
			name = "地鲶鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "35倍",
			prefab = "Fish3D014",
			tips = "出生开始就留着胡子，年龄不大，辈分可不小。",
		},
		[13]=
		{
			line = 13,
			order = 28,
			tag = 1,
			icon = "3dby_icon_yu13",
			name = "寒冰鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "30倍",
			prefab = "Fish3D015",
			tips = "冰冷的外表，不喜欢接触其他人，是个难以靠近的家伙。",
		},
		[14]=
		{
			line = 14,
			order = 26,
			tag = 1,
			icon = "3dby_icon_yu14",
			name = "地狱火鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "15倍",
			prefab = "Fish3D016",
			tips = "脾气暴躁，风风火火，一旦生气不计后果，从来不会顾及身边有谁。",
		},
		[15]=
		{
			line = 15,
			order = 24,
			tag = 1,
			icon = "3dby_icon_yu15",
			name = "剑鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "40倍",
			prefab = "Fish3D017",
			tips = "攻击性很强，一旦加起速赖没有谁能把他拦住。",
		},
		[16]=
		{
			line = 16,
			order = 22,
			tag = 1,
			icon = "3dby_icon_yu16",
			name = "飞鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "18倍",
			prefab = "Fish3D018",
			tips = "擅长跳跃与飞行，梦想是成为一名优雅的水上芭蕾舞者。",
		},
		[17]=
		{
			line = 17,
			order = 20,
			tag = 1,
			icon = "3dby_icon_yu17",
			name = "灯笼鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "58倍",
			prefab = "Fish3D019",
			tips = "喜欢在黑暗中惊吓别人，但捉迷藏从来没有赢过。",
		},
		[18]=
		{
			line = 18,
			order = 18,
			tag = 1,
			icon = "3dby_icon_yu18",
			name = "炸弹鱼",
			scale = 5,
			rotation = {66,0,0},
			rate = "10倍",
			prefab = "Fish3D020",
			tips = "出生开始头顶就有一小团火苗，因此也让他无时无刻焦急不安。",
		},
		[19]=
		{
			line = 19,
			order = 16,
			tag = 1,
			icon = "3dby_icon_yu20",
			name = "魔鬼鱼",
			scale = 3,
			rotation = {66,0,0},
			rate = "60倍",
			prefab = "Fish3D022",
			tips = "外形看起来十分吓人，实际上非常温顺，而且胆子很小。",
		},
		[20]=
		{
			line = 20,
			order = 14,
			tag = 1,
			icon = "3dby_icon_yu21",
			name = "大白鲨",
			scale = 2,
			rotation = {66,0,0},
			rate = "80倍",
			prefab = "Fish3D023",
			tips = "在航洋中相当有地位，行事十分低调，关于他的传奇故事数不胜数。",
		},
		[21]=
		{
			line = 21,
			order = 12,
			tag = 2,
			icon = "3dby_icon_yu22",
			name = "大金鲨",
			scale = 2,
			rotation = {66,0,0},
			rate = "100倍",
			prefab = "Fish3D024",
			tips = "是大白鲨的亲戚，行事却十分高调，喜欢炫耀自己的战绩与收获。",
		},
		[22]=
		{
			line = 22,
			order = 10,
			tag = 1,
			icon = "3dby_icon_yu24",
			name = "虎鲸",
			scale = 1.500000,
			rotation = {66,0,0},
			rate = "90倍",
			prefab = "Fish3D026",
			tips = "体型巨大，晒太阳时总让人以为是座小岛，小鱼也喜欢躲在他肚子下乘凉。",
		},
		[23]=
		{
			line = 23,
			order = 23,
			tag = 2,
			icon = "3dby_icon_yu25",
			name = "金蟾",
			scale = 2,
			rotation = {66,0,0},
			rate = "200倍",
			prefab = "Fish3D027",
			tips = "海底的土豪，从头到脚都有黄金作饰品，以被人围观而感到自豪。",
		},
		[24]=
		{
			line = 24,
			order = 24,
			tag = 2,
			icon = "3dby_icon_yu26",
			name = "深海鲸",
			scale = 0.600000,
			rotation = {66,0,0},
			rate = "400倍",
			prefab = "Fish3D028",
			tips = "深海霸主，体形庞大，听说是身价上亿的海中富豪。",
		},
		[25]=
		{
			line = 25,
			order = 25,
			tag = 3,
			icon = "3dby_icon_yu33",
			name = "美人鱼",
			scale = 1.500000,
			rotation = {66,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D029",
			tips = "体态优美，身型匀称，童话世界中的精灵美人鱼。",
		},
		[26]=
		{
			line = 26,
			order = 26,
			tag = 3,
			icon = "3dby_icon_yu27",
			name = "穿云蟹",
			scale = 3,
			rotation = {0,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D030",
			tips = "深海中神奇的鱼种，难以捕获。被捕获后，可发射“穿云火箭”贯穿全渔场，威力不同凡响。",
		},
		[27]=
		{
			line = 27,
			order = 27,
			tag = 3,
			icon = "3dby_icon_yu32",
			name = "大奖章鱼",
			scale = 2,
			rotation = {66,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D031",
			tips = "手持宝箱，被捕捉后大概率出发“金币大爆炸”，连续多次爆发金币。",
		},
		[28]=
		{
			line = 28,
			order = 28,
			tag = 3,
			icon = "3dby_icon_yu28",
			name = "闪电海鳗",
			scale = 3,
			rotation = {66,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D032",
			tips = "有海中雷震子之称，难以捕获。被捕获后，有几率触发闪电连，附近的小鱼就要遭殃了。",
		},
		[29]=
		{
			line = 29,
			order = 29,
			tag = 3,
			icon = "3dby_icon_yu29",
			name = "电磁蟹",
			scale = 3,
			rotation = {0,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D034",
			tips = "深海中横行无忌的物种，难以捕获。别捕获后，他会交出秘密武器“电磁炮”让你当一回深海霸主。",
		},
		[30]=
		{
			line = 30,
			order = 30,
			tag = 2,
			icon = "3dby_icon_yu30",
			name = "黄金巨龙",
			scale = 1,
			rotation = {0,0,0},
			rate = "500倍",
			prefab = "Fish3D036",
			tips = "传说中的瑞兽，象征着机箱和尊贵，可上天入海，见首不见尾。捕获后最高可获得500倍奖励。",
		},
		[31]=
		{
			line = 31,
			order = 31,
			tag = 3,
			icon = "3dby_icon_yu31",
			name = "奇遇蟹",
			scale = 5,
			rotation = {0,0,0},
			rate = "特殊奖励",
			prefab = "Fish3D041",
			tips = "捕获奇遇蟹，会触发30秒的免费游戏。免费游戏过程还有机会加免费时间，加奖励倍数。",
		},
		[32]=
		{
			line = 32,
			order = 32,
			tag = 2,
			icon = "3dby_icon_yu23",
			name = "黄金锤头鲨",
			scale = 1.500000,
			rotation = {66,0,0},
			rate = "150倍",
			prefab = "Fish3D025",
			tips = "自称素食主义者，喜欢品尝海草和藏在海草里的小鱼。",
		},
		[33]=
		{
			line = 33,
			order = 33,
			tag = 2,
			icon = "3dby_icon_yu20",
			name = "魔鬼王鱼",
			scale = 1,
			rotation = {66,0,0},
			rate = "400倍",
			prefab = "Fish3D043",
		},
		[34]=
		{
			line = 34,
			order = 34,
			tag = 2,
			icon = "3dby_icon_yu19",
			name = "黄金炸弹鱼",
			scale = 3,
			rotation = {66,0,0},
			rate = "55倍",
			prefab = "Fish3D021",
			tips = "个头比一般的炸弹鱼要大，口头禅是人生苦短，常模仿金蟾打扮自己",
		},
		[35]=
		{
			line = 35,
			order = 35,
			tag = 2,
			icon = "3dby_icon_yu34",
			name = "霸王蟹",
			scale = 3,
			rotation = {0,0,0},
			rate = "最高250倍",
			prefab = "Fish3D044",
		},
		[36]=
		{
			line = 36,
			order = 36,
			tag = 3,
			icon = "bk_icon_ywdj",
			name = "一网打尽",
			scale = 1,
			rotation = {0,0,0},
			prefab = "turntable_ywdj",
			tips = "一群命运共同体的鱼，不过任意一条标记有“一网打尽”的鱼，其他的将同时被捕获。",
		},
	},
}