return {
	config=
	{
		[1]=
		{
			id = 1,
			item_id = 1,
			item_key = "cash",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_xj",
			order = 100,
			name = "奖金",
			desc = "微信福卡奖金",
		},
		[2]=
		{
			id = 2,
			item_id = 2,
			item_key = "jipaiqi",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jipaiqi",
			is_show_bag = 1,
			order = 17,
			name = "记牌器",
			desc = "记牌器",
		},
		[3]=
		{
			id = 3,
			item_id = 3,
			item_key = "diamond",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_icon_diamond",
			order = 100,
			name = "钻石",
			desc = "钻石",
		},
		[4]=
		{
			id = 4,
			item_id = 4,
			item_key = "jing_bi",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jingbi",
			order = 100,
			name = "鲸币",
			desc = "鲸币",
		},
		[5]=
		{
			id = 5,
			item_id = 5,
			item_key = "vip",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_btn_close",
			order = 100,
			name = "VIP",
			desc = "vip",
		},
		[6]=
		{
			id = 6,
			item_id = 6,
			item_key = "shop_gold_sum",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money",
			order = 100,
			name = "福卡",
			desc = "福卡",
		},
		[7]=
		{
			id = 7,
			item_id = 7,
			item_key = "shop_gold_sum_limit",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_moneyed",
			order = 100,
			name = "福卡额度",
			desc = "每日福卡额度",
		},
		[8]=
		{
			id = 8,
			item_id = 8,
			item_key = "room_card",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_rc",
			is_show_bag = 1,
			order = 100,
			name = "房卡",
			desc = "创建房卡游戏时使用",
			use_parm = {"roomcard_hall",},
		},
		[9]=
		{
			id = 9,
			item_id = 9,
			item_key = "frame1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz1",
			order = 100,
			name = "Lv.10",
			desc = "等级头像框",
		},
		[10]=
		{
			id = 10,
			item_id = 10,
			item_key = "frame2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz2",
			order = 100,
			name = "Lv.20",
			desc = "等级头像框",
		},
		[11]=
		{
			id = 11,
			item_id = 11,
			item_key = "frame3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz3",
			order = 100,
			name = "Lv.30",
			desc = "等级头像框",
		},
		[12]=
		{
			id = 12,
			item_id = 12,
			item_key = "frame4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz4",
			order = 100,
			name = "Lv.40",
			desc = "等级头像框",
		},
		[13]=
		{
			id = 13,
			item_id = 13,
			item_key = "frame5",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz5",
			order = 100,
			name = "Lv.50",
			desc = "等级头像框",
		},
		[14]=
		{
			id = 14,
			item_id = 14,
			item_key = "frame6",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz6",
			order = 100,
			name = "Lv.60",
			desc = "等级头像框",
		},
		[15]=
		{
			id = 15,
			item_id = 15,
			item_key = "frame7",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz7",
			order = 100,
			name = "Lv.70",
			desc = "等级头像框",
		},
		[16]=
		{
			id = 16,
			item_id = 16,
			item_key = "frame8",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz8",
			order = 100,
			name = "Lv.80",
			desc = "等级头像框",
		},
		[17]=
		{
			id = 17,
			item_id = 17,
			item_key = "frame9",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz9",
			order = 100,
			name = "Lv.90",
			desc = "等级头像框",
		},
		[18]=
		{
			id = 18,
			item_id = 18,
			item_key = "emoticon1",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_water",
			order = 100,
			name = "泼水表情",
			desc = "高级互动表情",
		},
		[19]=
		{
			id = 19,
			item_id = 19,
			item_key = "emoticon2",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_guo",
			order = 100,
			name = "平底锅表情",
			desc = "高级互动表情",
		},
		[20]=
		{
			id = 20,
			item_id = 20,
			item_key = "emoticon3",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_th",
			order = 100,
			name = "戴墨镜表情",
			desc = "高级互动表情",
		},
		[21]=
		{
			id = 21,
			item_id = 21,
			item_key = "emoticon4",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_pig",
			order = 100,
			name = "变猪表情",
			desc = "高级互动表情",
		},
		[22]=
		{
			id = 22,
			item_id = 22,
			item_key = "chat",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhk",
			order = 100,
			name = "方言特色短语",
			desc = "高级快捷短语",
		},
		[23]=
		{
			id = 23,
			item_id = 23,
			item_key = "broadcast",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_gb",
			order = 100,
			name = "登录全服广播",
			desc = "登录时全服播放欢迎广播",
		},
		[24]=
		{
			id = 24,
			item_id = 24,
			item_key = "jipaiqi_free",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jipaiqi",
			order = 100,
			name = "免费记牌器",
			desc = "免费使用记牌器",
		},
		[25]=
		{
			id = 25,
			item_id = 101,
			item_key = "match_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_hxs",
			is_show_bag = 0,
			order = 25,
			name = "比赛券",
			desc = "用于参加比赛场的比赛",
		},
		[26]=
		{
			id = 26,
			item_id = 25,
			item_key = "frame10",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_head_ddz10",
			order = 100,
			name = "Lv.100",
			desc = "等级头像框",
		},
		[27]=
		{
			id = 27,
			item_id = 26,
			item_key = "prop_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 0,
			order = 100,
			name = "比赛场门票",
			desc = "可用于参加所有锦标赛",
			use_parm = {"match_hall","hbs",},
		},
		[28]=
		{
			id = 28,
			item_id = 27,
			item_key = "prop_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_qys",
			is_show_bag = 1,
			order = 18,
			name = "千元赛门票",
			desc = "用于报名千元大奖赛",
			use_parm = {"match_hall","djs",},
		},
		[29]=
		{
			id = 29,
			item_id = 28,
			item_key = "real_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 0,
			order = 100,
			name = "黑锅",
			desc = "黑锅",
			real_object = 1,
		},
		[30]=
		{
			id = 30,
			item_id = 29,
			item_key = "prop_hammer_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz1",
			is_show_bag = 1,
			order = 23,
			name = "玩具锤",
			desc = "内部充气的玩具锤，小朋友们的最爱",
			use_parm = {"hall_egg","prop_hammer_1"},
		},
		[31]=
		{
			id = 31,
			item_id = 30,
			item_key = "prop_hammer_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz2",
			is_show_bag = 1,
			order = 22,
			name = "木锤",
			desc = "看起来似乎不太经用的木头锤子",
			use_parm = {"hall_egg","prop_hammer_2"},
		},
		[32]=
		{
			id = 32,
			item_id = 31,
			item_key = "prop_hammer_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz3",
			is_show_bag = 1,
			order = 21,
			name = "银锤",
			desc = "虽然看起来挺像，不过这可不是那把能放电的锤子",
			use_parm = {"hall_egg","prop_hammer_3"},
		},
		[33]=
		{
			id = 33,
			item_id = 32,
			item_key = "prop_hammer_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz4",
			is_show_bag = 1,
			order = 20,
			name = "金锤",
			desc = "听说下雨天金锤和金蛋更配哦！",
			use_parm = {"hall_egg","prop_hammer_4"},
		},
		[34]=
		{
			id = 34,
			item_id = 33,
			item_key = "expression_54",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_666",
			order = 100,
			name = "666表情",
			desc = "666表情",
		},
		[35]=
		{
			id = 35,
			item_id = 34,
			item_key = "prop_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_wys",
			is_show_bag = 1,
			order = 19,
			name = "万元赛门票",
			desc = "用于报名万元大奖赛",
			use_parm = {"match_hall","hks",},
		},
		[36]=
		{
			id = 36,
			item_id = 35,
			item_key = "prop_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jyhd",
			is_show_bag = 1,
			order = 100,
			name = "企业赛门票",
			desc = "用于报名企业赛",
			use_parm = {"match_hall","hks",},
		},
		[37]=
		{
			id = 37,
			item_id = 36,
			item_key = "prop_5",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_yys",
			is_show_bag = 1,
			order = 19,
			name = "一元赛门票",
			desc = "用于报名一元赛",
			use_parm = {"match_hall","fks",},
		},
		[38]=
		{
			id = 38,
			item_id = 37,
			item_key = "fake1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_moneyywy",
			is_show_bag = 0,
			order = 100,
			name = "千元第一",
			desc = "第一",
		},
		[39]=
		{
			id = 39,
			item_id = 38,
			item_key = "fake2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money300",
			is_show_bag = 0,
			order = 100,
			name = "千元第二",
			desc = "第二",
		},
		[40]=
		{
			id = 40,
			item_id = 39,
			item_key = "fake3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money10000",
			is_show_bag = 0,
			order = 100,
			name = "千元第三",
			desc = "第三",
		},
		[41]=
		{
			id = 41,
			item_id = 40,
			item_key = "obj_qianyuansai_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_qys",
			is_show_bag = 1,
			order = 19,
			name = "千元赛门票",
			desc = "千元赛限时门票，限7天内使用！",
			desc_extra = "<size=40><color=#FF0000FF>限时</color><color=#FFF06E>门票，有效时间</color><color=#FF0000FF>7天</color></size>",
			use_parm = {"match_hall","djs",},
		},
		[42]=
		{
			id = 42,
			item_id = 41,
			item_key = "prop_5y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_5ys",
			is_show_bag = 1,
			order = 19,
			name = "五元赛门票",
			desc = "用于报名五元福卡赛",
			use_parm = {"match_hall","fks",},
		},
		[43]=
		{
			id = 43,
			item_id = 42,
			item_key = "prop_20y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_20ys",
			is_show_bag = 1,
			order = 19,
			name = "二十元赛门票",
			desc = "用于报名二十元福卡赛",
			use_parm = {"match_hall","fks",},
		},
		[44]=
		{
			id = 44,
			item_id = 43,
			item_key = "prop_100y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100ys",
			is_show_bag = 1,
			order = 19,
			name = "百元赛门票",
			desc = "用于报名一百元福卡赛",
			use_parm = {"match_hall","fks",},
		},
		[45]=
		{
			id = 45,
			item_id = 44,
			item_key = "prop_50y",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50ys",
			is_show_bag = 1,
			order = 19,
			name = "五十元赛门票",
			desc = "用于报名五十元福卡赛",
			use_parm = {"match_hall","fks",},
		},
		[46]=
		{
			id = 46,
			item_id = 45,
			item_key = "fish_coin",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_icon_yb",
			is_show_bag = 1,
			order = 2,
			name = "捕鱼币",
			desc = "用于捕鱼消耗",
			use_parm = {"game_FishingHall",},
		},
		[47]=
		{
			id = 47,
			item_id = 46,
			item_key = "prop_fish_frozen",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_bd",
			is_show_bag = 1,
			order = 29,
			name = "冰冻",
			desc = "冰冻全场鱼",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[48]=
		{
			id = 48,
			item_id = 47,
			item_key = "prop_fish_lock",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_sd",
			is_show_bag = 1,
			order = 29,
			name = "锁定",
			desc = "锁定攻击鱼",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[49]=
		{
			id = 49,
			item_id = 48,
			item_key = "expression_57",
			lose_time = -1,
			is_local_icon = 1,
			image = "pay_icon_pig",
			order = 100,
			name = "猪头表情",
			desc = "猪头表情",
		},
		[50]=
		{
			id = 50,
			item_id = 49,
			item_key = "prop_50hf",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50ys",
			is_show_bag = 1,
			order = 27,
			name = "五十话费赛门票",
			desc = "用于报名50元免费话费赛",
			use_parm = {"match_hall","fks",},
		},
		[51]=
		{
			id = 51,
			item_id = 50,
			item_key = "prop_100hf",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100ys",
			is_show_bag = 1,
			order = 28,
			name = "一百话费赛门票",
			desc = "用于报名100元免费话费赛",
			use_parm = {"match_hall","fks",},
		},
		[52]=
		{
			id = 52,
			item_id = 51,
			item_key = "prop_zongzi",
			lose_time = -1,
			is_local_icon = 1,
			image = "bzdh_icon_5",
			is_show_bag = 0,
			order = 100,
			name = "海盗帽",
			desc = "捕鱼收集粽子赢大奖",
		},
		[53]=
		{
			id = 53,
			item_id = 52,
			item_key = "obj_fish_free_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_danmf2",
			is_show_bag = 1,
			order = 30,
			name = "免费时刻",
			desc = "触发免费时刻",
			use_parm = {"game_FishingHall",},
			tag = 7,
		},
		[54]=
		{
			id = 54,
			item_id = 53,
			item_key = "obj_fish_crit_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_sbsk",
			is_show_bag = 1,
			order = 30,
			name = "双倍时刻",
			desc = "触发双倍时刻",
			use_parm = {"game_FishingHall",},
			tag = 7,
		},
		[55]=
		{
			id = 55,
			item_id = 54,
			item_key = "obj_fish_power_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_cjhl",
			is_show_bag = 1,
			order = 30,
			name = "超级火力",
			desc = "触发超级火力",
			use_parm = {"game_FishingHall",},
			tag = 7,
		},
		[56]=
		{
			id = 56,
			item_id = 55,
			item_key = "prop_6",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_mxyqh",
			is_show_bag = 1,
			order = 100,
			name = "明星大奖赛门票",
			desc = "明星大奖赛门票",
			use_parm = {"match_hall","hks",},
		},
		[57]=
		{
			id = 57,
			item_id = 56,
			item_key = "obj_fish_super_bomb",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 31,
			name = "超级全屏炸弹",
			desc = "毁天灭地，却无辐射残留",
			tag = 6,
		},
		[58]=
		{
			id = 58,
			item_id = 57,
			item_key = "obj_fish_secondary_bomb",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 31,
			name = "全屏炸弹",
			desc = "再也不用担心炸弹范围太小了",
			tag = 6,
		},
		[59]=
		{
			id = 59,
			item_id = 58,
			item_key = "obj_fish_super_bolt",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dsd",
			is_show_bag = 1,
			order = 31,
			name = "超级全屏闪电",
			desc = "电闪雷鸣，鱼儿无所遁形",
			tag = 6,
		},
		[60]=
		{
			id = 60,
			item_id = 59,
			item_key = "obj_fish_secondary_bolt",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xsd",
			is_show_bag = 1,
			order = 31,
			name = "全屏闪电",
			desc = "让我看看是谁在电鱼！",
			tag = 6,
		},
		[61]=
		{
			id = 61,
			item_id = 60,
			item_key = "obj_fish_lock",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_sd",
			is_show_bag = 1,
			order = 100,
			name = "锁定（比赛专用）",
			desc = "锁定攻击鱼",
			tag = 6,
		},
		[62]=
		{
			id = 62,
			item_id = 61,
			item_key = "prop_fish",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_bybsq",
			is_show_bag = 1,
			order = 100,
			name = "捕鱼比赛券",
			desc = "用于参加捕鱼赛事",
			use_parm = {"game_FishingHall",},
		},
		[63]=
		{
			id = 63,
			item_id = 62,
			item_key = "obj_qys_match_revive_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_fh2",
			is_show_bag = 1,
			order = 18,
			name = "千元赛复活门票",
			desc = "用于千元赛复活",
		},
		[64]=
		{
			id = 64,
			item_id = 63,
			item_key = "prop_7",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_znq",
			is_show_bag = 1,
			order = 100,
			name = "周年感恩赛门票",
			desc = "该门票可用于2019年9月15日20点30分参加周年感恩赛",
			use_parm = {"match_hall","hks"},
		},
		[65]=
		{
			id = 65,
			item_id = 64,
			item_key = "fake4",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp1",
			is_show_bag = 0,
			order = 100,
			name = "10斤长谷子大米",
			desc = "感恩赛奖励",
		},
		[66]=
		{
			id = 66,
			item_id = 65,
			item_key = "fake5",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp4",
			is_show_bag = 0,
			order = 100,
			name = "金条*5g",
			desc = "感恩赛第一名奖励",
		},
		[67]=
		{
			id = 67,
			item_id = 66,
			item_key = "fake6",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp3",
			is_show_bag = 0,
			order = 100,
			name = "金条*2g",
			desc = "感恩赛第二名奖励",
		},
		[68]=
		{
			id = 68,
			item_id = 67,
			item_key = "fake7",
			lose_time = -1,
			is_local_icon = 1,
			image = "settlement_icon_jp2",
			is_show_bag = 0,
			order = 100,
			name = "金条*1g",
			desc = "感恩赛第三名奖励",
		},
		[69]=
		{
			id = 69,
			item_id = 68,
			item_key = "obj_fish_match",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_bybsq",
			is_show_bag = 1,
			order = 100,
			name = "捕鱼比赛券",
			desc = "用于参加捕鱼赛事",
			use_parm = {"game_FishingHall",},
		},
		[70]=
		{
			id = 70,
			item_id = 69,
			item_key = "prop_jinianbi",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_jnb",
			is_show_bag = 1,
			order = 100,
			name = "纪念币",
			desc = "周年活动纪念币",
		},
		[71]=
		{
			id = 71,
			item_id = 70,
			item_key = "prop_znq_dhq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 1,
			order = 100,
			name = "抽奖券",
			desc = "周年庆活动专用",
		},
		[72]=
		{
			id = 72,
			item_id = 71,
			item_key = "obj_fish_drill_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bytx_zt",
			is_show_bag = 1,
			order = 100,
			name = "钻头弹",
			desc = "威力强大的钻头弹，一发惊天动地。可在捕鱼场中使用。",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[73]=
		{
			id = 73,
			item_id = 72,
			item_key = "obj_fish_pierce_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "bygame_icon_ctgd",
			is_show_bag = 1,
			order = 100,
			name = "穿透钢弹",
			desc = "可以穿透目标鱼的子弹",
			use_parm = {"game_FishingHall",},
			tag = 3,
		},
		[74]=
		{
			id = 74,
			item_id = 73,
			item_key = "prop_fish_summon_fish",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_shendeng",
			is_show_bag = 1,
			order = 29,
			name = "神灯",
			desc = "擦亮神灯，就会召唤黄金鱼",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[75]=
		{
			id = 75,
			item_id = 74,
			item_key = "sczd_achievement",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cjd",
			is_show_bag = 0,
			order = 100,
			name = "成就点",
			desc = "参与推广活动，获得成就点",
			tag = 2,
		},
		[76]=
		{
			id = 76,
			item_id = 75,
			item_key = "prop_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_jbbx",
			is_show_bag = 1,
			order = 100,
			name = "双11宝箱",
			desc = "宝箱可随机开出1000-15万鲸币。使用时间：2019年11月5日7:30至2019年11月11日23:59:59",
			use_parm = {"open_box",},
		},
		[77]=
		{
			id = 77,
			item_id = 76,
			item_key = "prop_11_cjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq2",
			is_show_bag = 1,
			order = 100,
			name = "双11抽奖券",
			desc = "可在双11抽大奖活动中使用此券进行抽奖。",
		},
		[78]=
		{
			id = 78,
			item_id = 78,
			item_key = "fake8",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift67",
			is_show_bag = 0,
			order = 100,
			name = "敦煌有机红枣",
			desc = "感恩赛奖励",
		},
		[79]=
		{
			id = 79,
			item_id = 79,
			item_key = "prop_xycj_coin",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq3",
			is_show_bag = 1,
			order = 100,
			name = "福利券",
			desc = "用于福卡大转盘的抽奖",
			use_parm = {"xycj","panel",1},
		},
		[80]=
		{
			id = 80,
			item_id = 80,
			item_key = "prop_box_stxt_free",
			lose_time = -1,
			is_local_icon = 1,
			image = "stgc_icon_bx1",
			is_show_bag = 1,
			order = 100,
			name = "免费激励宝箱",
			desc = "师傅给与徒弟的免费激励宝箱可随机开出1000-15万鲸币。",
			use_parm = {"open_box","prop_box_stxt_free"},
			box_id = 4,
		},
		[81]=
		{
			id = 81,
			item_id = 81,
			item_key = "prop_box_stxt_small",
			lose_time = -1,
			is_local_icon = 1,
			image = "stgc_icon_bx2",
			is_show_bag = 1,
			order = 100,
			name = "激励宝箱",
			desc = "师傅给与徒弟的激励宝箱可随机开出1000-15万鲸币。",
			use_parm = {"open_box","prop_box_stxt_small"},
			box_id = 5,
		},
		[82]=
		{
			id = 82,
			item_id = 82,
			item_key = "prop_gns_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_csj",
			is_show_bag = 1,
			order = 100,
			name = "美的空调赛门票",
			desc = "该门票可用于2022年3月1日21点00分参加美的空调赛",
			use_parm = {"match_hall","hks"},
		},
		[83]=
		{
			id = 83,
			item_id = 83,
			item_key = "fake9",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift91_gm",
			is_show_bag = 0,
			order = 100,
			name = "鹌鹑蛋面条",
			desc = "年末回馈赛奖励",
		},
		[84]=
		{
			id = 84,
			item_id = 84,
			item_key = "prop_new_year_word_kuai",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_1",
			is_show_bag = 1,
			order = 100,
			name = "快",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[85]=
		{
			id = 85,
			item_id = 85,
			item_key = "prop_new_year_word_le",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_2",
			is_show_bag = 1,
			order = 100,
			name = "乐",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[86]=
		{
			id = 86,
			item_id = 86,
			item_key = "prop_new_year_word_xin",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_3",
			is_show_bag = 1,
			order = 100,
			name = "新",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[87]=
		{
			id = 87,
			item_id = 87,
			item_key = "prop_new_year_word_shu",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_4",
			is_show_bag = 1,
			order = 100,
			name = "鼠",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[88]=
		{
			id = 88,
			item_id = 88,
			item_key = "prop_new_year_word_cai",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_5",
			is_show_bag = 1,
			order = 100,
			name = "财",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[89]=
		{
			id = 89,
			item_id = 89,
			item_key = "prop_new_year_word_nian",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_6",
			is_show_bag = 1,
			order = 100,
			name = "年",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[90]=
		{
			id = 90,
			item_id = 90,
			item_key = "prop_new_year_word_yuan",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_7",
			is_show_bag = 1,
			order = 100,
			name = "元",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[91]=
		{
			id = 91,
			item_id = 91,
			item_key = "prop_new_year_word_fa",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_8",
			is_show_bag = 1,
			order = 100,
			name = "發",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[92]=
		{
			id = 92,
			item_id = 92,
			item_key = "prop_new_year_word_dan",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_9",
			is_show_bag = 1,
			order = 100,
			name = "旦",
			desc = "收集文字，兑换欢庆元旦活动宝箱。",
		},
		[93]=
		{
			id = 93,
			item_id = 93,
			item_key = "prop_box_click_like",
			lose_time = -1,
			is_local_icon = 1,
			image = "bag_icon_dzyl",
			is_show_bag = 1,
			order = 100,
			name = "点赞宝箱",
			desc = "2020年1月24日-2月8日可开启宝箱，最多可获得10万鲸币。",
			use_parm = {"open_box","prop_box_click_like"},
			box_id = 12,
			beginTime = 1579795200,
			endTime = 1581177599,
		},
		[94]=
		{
			id = 94,
			item_id = 94,
			item_key = "fake10",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift128_xsy",
			is_show_bag = 0,
			order = 100,
			name = "洗手液",
			desc = "月末福利赛预约奖励",
		},
		[95]=
		{
			id = 95,
			item_id = 95,
			item_key = "fake11",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift129_jly",
			is_show_bag = 0,
			order = 100,
			name = "食用油",
			desc = "月末福利赛预约奖励",
		},
		[96]=
		{
			id = 96,
			item_id = 96,
			item_key = "prop_web_chip_huafei",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_hfsp",
			is_show_bag = 1,
			order = 1,
			name = "话费碎片",
			desc = "累计一定数量可以兑换话费",
			use_parm = {"duihuan_shop",},
		},
		[97]=
		{
			id = 97,
			item_id = 97,
			item_key = "prop_fish_secondary_bomb_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 25,
			name = "原子弹-浅水湾",
			desc = "原子弹-浅水湾",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 1,
		},
		[98]=
		{
			id = 98,
			item_id = 98,
			item_key = "prop_fish_super_bomb_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 25,
			name = "超级原子弹-浅水湾",
			desc = "超级原子弹-浅水湾",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 1,
		},
		[99]=
		{
			id = 99,
			item_id = 99,
			item_key = "prop_fish_secondary_bomb_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 25,
			name = "原子弹-深海寻宝",
			desc = "原子弹-深海寻宝",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 2,
		},
		[100]=
		{
			id = 100,
			item_id = 100,
			item_key = "prop_fish_super_bomb_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 25,
			name = "超级原子弹-深海寻宝",
			desc = "超级原子弹-深海寻宝",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 2,
		},
		[101]=
		{
			id = 101,
			item_id = 101,
			item_key = "prop_fish_secondary_bomb_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_xbz",
			is_show_bag = 1,
			order = 25,
			name = "原子弹-地底遗迹",
			desc = "原子弹-地底遗迹",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 3,
		},
		[102]=
		{
			id = 102,
			item_id = 102,
			item_key = "prop_fish_super_bomb_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bymatch_game_btn_dbz",
			is_show_bag = 1,
			order = 25,
			name = "超级原子弹-地底遗迹",
			desc = "超级原子弹-地底遗迹",
			use_parm = {"game_FishingHall",},
			tag = 3,
			game_id = 3,
		},
		[103]=
		{
			id = 103,
			item_id = 103,
			item_key = "obj_3d_fish_free_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_1",
			is_show_bag = 1,
			order = 25,
			name = "免费子弹-3D捕鱼",
			desc = "免费子弹-3D捕鱼",
			tag = 8,
		},
		[104]=
		{
			id = 104,
			item_id = 104,
			item_key = "obj_3d_fish_power_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_2",
			is_show_bag = 1,
			order = 25,
			name = "超级火力-3D捕鱼",
			desc = "超级火力-3D捕鱼",
			tag = 8,
		},
		[105]=
		{
			id = 105,
			item_id = 105,
			item_key = "obj_3d_fish_crit_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_3",
			is_show_bag = 1,
			order = 25,
			name = "双倍时刻-3D捕鱼",
			desc = "双倍时刻-3D捕鱼",
			tag = 8,
		},
		[106]=
		{
			id = 106,
			item_id = 106,
			item_key = "obj_3d_fish_quick_shoot",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_4",
			is_show_bag = 1,
			order = 25,
			name = "超速子弹-3D捕鱼",
			desc = "超速子弹-3D捕鱼",
			tag = 8,
		},
		[107]=
		{
			id = 107,
			item_id = 107,
			item_key = "obj_3d_fish_drill_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_icon_zt",
			is_show_bag = 1,
			order = 25,
			name = "钻头弹-3D捕鱼",
			desc = "钻头弹-3D捕鱼",
			tag = 8,
		},
		[108]=
		{
			id = 108,
			item_id = 108,
			item_key = "obj_3d_fish_pierce_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_6",
			is_show_bag = 1,
			order = 25,
			name = "穿透子弹-3D捕鱼",
			desc = "穿透子弹-3D捕鱼",
			tag = 8,
		},
		[109]=
		{
			id = 109,
			item_id = 109,
			item_key = "prop_3d_fish_summon_fish",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_btn_zh",
			is_show_bag = 1,
			order = 25,
			name = "召唤-3D捕鱼",
			desc = "召唤-3D捕鱼",
			tag = 8,
		},
		[110]=
		{
			id = 110,
			item_id = 110,
			item_key = "obj_fish_3d_time_free_power_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "hqyd_imgf_8",
			is_show_bag = 1,
			order = 26,
			name = "免费超级火力-3D捕鱼",
			desc = "免费超级火力-3D捕鱼",
			tag = 8,
		},
		[111]=
		{
			id = 111,
			item_id = 111,
			item_key = "obj_fish_3d_laser_bullet",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_icon_jg",
			is_show_bag = 1,
			order = 26,
			name = "激光炮-3D捕鱼",
			desc = "激光炮-3D捕鱼",
			tag = 8,
		},
		[112]=
		{
			id = 112,
			item_id = 112,
			item_key = "fake12",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift136_jlygm",
			is_show_bag = 0,
			order = 100,
			name = "金龙鱼挂面",
			desc = "国庆福利赛比赛奖励",
		},
		[113]=
		{
			id = 113,
			item_id = 113,
			item_key = "prop_npca_hb",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_money",
			is_show_bag = 0,
			order = 100,
			name = "支付宝红包",
			desc = "支付宝红包可提现",
		},
		[114]=
		{
			id = 114,
			item_id = 114,
			item_key = "prop_3d_fish_frozen",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_btn_bd",
			is_show_bag = 1,
			order = 26,
			name = "冰冻-3D捕鱼",
			desc = "冰冻全场鱼-3D捕鱼",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[115]=
		{
			id = 115,
			item_id = 115,
			item_key = "prop_3d_fish_lock",
			lose_time = -1,
			is_local_icon = 1,
			image = "3dby_btn_sd",
			is_show_bag = 1,
			order = 26,
			name = "锁定-3D捕鱼",
			desc = "锁定攻击鱼-3D捕鱼",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[116]=
		{
			id = 116,
			item_id = 116,
			item_key = "prop_mfcjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "免费抽奖券",
			desc = "免费抽奖券",
		},
		[117]=
		{
			id = 117,
			item_id = 117,
			item_key = "prop_sunshine",
			lose_time = -1,
			is_local_icon = 1,
			image = "xycd_icon_ty",
			is_show_bag = 0,
			order = 100,
			name = "阳光值",
			desc = "阳光值",
		},
		[118]=
		{
			id = 118,
			item_id = 118,
			item_key = "prop_carnation",
			lose_time = -1,
			is_local_icon = 1,
			image = "mqjth_icon_knx",
			is_show_bag = 0,
			order = 100,
			name = "康乃馨",
			desc = "康乃馨",
		},
		[119]=
		{
			id = 119,
			item_id = 119,
			item_key = "prop_shovel",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_chanz1",
			is_show_bag = 0,
			order = 100,
			name = "铲子",
			desc = "铲子",
		},
		[120]=
		{
			id = 120,
			item_id = 120,
			item_key = "fake13",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift152_shrmj",
			is_show_bag = 0,
			order = 100,
			name = "珊瑚绒毛巾",
			desc = "月末福利赛奖励",
		},
		[121]=
		{
			id = 121,
			item_id = 121,
			item_key = "prop_love",
			lose_time = -1,
			is_local_icon = 1,
			image = "lmlh_icon_ax",
			is_show_bag = 0,
			order = 100,
			name = "爱心",
			desc = "爱心",
		},
		[122]=
		{
			id = 122,
			item_id = 122,
			item_key = "prop_hfdhq",
			lose_time = -1,
			is_local_icon = 1,
			image = "bs20hf_icon_hfq",
			is_show_bag = 0,
			order = 100,
			name = "话费券",
			desc = "用于在兑换话费活动中进行话费兑换",
		},
		[123]=
		{
			id = 123,
			item_id = 123,
			item_key = "prop_guess_apple_bet_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_shui",
			is_show_bag = 1,
			order = 100,
			name = "水滴",
			desc = "用于苹果大战种植",
			use_parm = {"game_ZPG",},
		},
		[124]=
		{
			id = 124,
			item_id = 124,
			item_key = "prop_guess_apple_bet_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_yg",
			is_show_bag = 1,
			order = 100,
			name = "太阳",
			desc = "用于苹果大战种植",
			use_parm = {"game_ZPG",},
		},
		[125]=
		{
			id = 125,
			item_id = 125,
			item_key = "prop_guess_apple_bet_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_cc",
			is_show_bag = 1,
			order = 100,
			name = "铲子",
			desc = "用于苹果大战种植",
			use_parm = {"game_ZPG",},
		},
		[126]=
		{
			id = 126,
			item_id = 126,
			item_key = "prop_guess_apple_bet_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_sc",
			is_show_bag = 1,
			order = 100,
			name = "除虫剂",
			desc = "用于苹果大战种植",
			use_parm = {"game_ZPG",},
		},
		[127]=
		{
			id = 127,
			item_id = 127,
			item_key = "prop_guess_apple_bet_5",
			lose_time = -1,
			is_local_icon = 1,
			image = "zpg_icon_fl",
			is_show_bag = 1,
			order = 100,
			name = "肥料",
			desc = "用于苹果大战种植",
			use_parm = {"game_ZPG",},
		},
		[128]=
		{
			id = 128,
			item_id = 128,
			item_key = "fake14",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift166_htgt",
			is_show_bag = 0,
			order = 100,
			name = "黄桃",
			desc = "月末福利赛奖励",
		},
		[129]=
		{
			id = 129,
			item_id = 129,
			item_key = "fake15",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift162_kt",
			is_show_bag = 0,
			order = 100,
			name = "美的空调",
			desc = "美的空调赛奖励",
		},
		[130]=
		{
			id = 130,
			item_id = 130,
			item_key = "fake16",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift167_mddfb",
			is_show_bag = 0,
			order = 100,
			name = "美的电饭锅",
			desc = "美的空调赛奖励",
		},
		[131]=
		{
			id = 131,
			item_id = 131,
			item_key = "fake17",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift153_fs",
			is_show_bag = 0,
			order = 100,
			name = "美的风扇",
			desc = "月末福利赛奖励",
		},
		[132]=
		{
			id = 132,
			item_id = 132,
			item_key = "prop_mfcjq_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "免费抽奖券",
			desc = "免费抽奖券",
		},
		[133]=
		{
			id = 133,
			item_id = 133,
			item_key = "prop_cjlb_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包白银宝箱（V1-V3）",
		},
		[134]=
		{
			id = 134,
			item_id = 134,
			item_key = "prop_cjlb_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包黄金宝箱（V1-V3）",
		},
		[135]=
		{
			id = 135,
			item_id = 135,
			item_key = "prop_cjlb_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包钻石宝箱（V1-V3）",
		},
		[136]=
		{
			id = 136,
			item_id = 136,
			item_key = "prop_cjlb_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包白银宝箱（V4-V7）",
		},
		[137]=
		{
			id = 137,
			item_id = 137,
			item_key = "prop_cjlb_5",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包黄金宝箱（V4-V7）",
		},
		[138]=
		{
			id = 138,
			item_id = 138,
			item_key = "prop_cjlb_6",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包钻石宝箱（V4-V7）",
		},
		[139]=
		{
			id = 139,
			item_id = 139,
			item_key = "prop_cjlb_7",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包白银宝箱（V8-V12）",
		},
		[140]=
		{
			id = 140,
			item_id = 140,
			item_key = "prop_cjlb_8",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包黄金宝箱（V8-V12）",
		},
		[141]=
		{
			id = 141,
			item_id = 141,
			item_key = "prop_cjlb_9",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖礼包抽奖券",
			desc = "抽奖礼包钻石宝箱（V8-V12）",
		},
		[142]=
		{
			id = 142,
			item_id = 142,
			item_key = "prop_zongzi_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_icon_jzz",
			is_show_bag = 0,
			order = 100,
			name = "粽子",
			desc = "端午福利任务获得",
		},
		[143]=
		{
			id = 143,
			item_id = 143,
			item_key = "fake18",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift191_xmh",
			is_show_bag = 0,
			order = 100,
			name = "小麻花",
			desc = "美的冰箱品牌赛奖励",
		},
		[144]=
		{
			id = 144,
			item_id = 144,
			item_key = "fake19",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift192_bx",
			is_show_bag = 0,
			order = 100,
			name = "冰箱",
			desc = "美的冰箱品牌赛奖励",
		},
		[145]=
		{
			id = 145,
			item_id = 145,
			item_key = "fake20",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift193_wbl",
			is_show_bag = 0,
			order = 100,
			name = "微波炉",
			desc = "美的冰箱品牌赛奖励",
		},
		[146]=
		{
			id = 146,
			item_id = 146,
			item_key = "fake21",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift194_zzj",
			is_show_bag = 0,
			order = 100,
			name = "榨汁机",
			desc = "美的冰箱品牌赛奖励",
		},
		[147]=
		{
			id = 147,
			item_id = 147,
			item_key = "prop_brass_hammer_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz2",
			is_show_bag = 0,
			order = 100,
			name = "铜锤",
			desc = "欢乐敲金蛋铜锤（V1-V3）",
		},
		[148]=
		{
			id = 148,
			item_id = 148,
			item_key = "prop_silver_hammer_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz3",
			is_show_bag = 0,
			order = 100,
			name = "银锤",
			desc = "欢乐敲金蛋银锤（V1-V3）",
		},
		[149]=
		{
			id = 149,
			item_id = 149,
			item_key = "prop_gold_hammer_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz4",
			is_show_bag = 0,
			order = 100,
			name = "金锤",
			desc = "欢乐敲金蛋金锤（V1-V3）",
		},
		[150]=
		{
			id = 150,
			item_id = 150,
			item_key = "prop_brass_hammer_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz2",
			is_show_bag = 0,
			order = 100,
			name = "铜锤",
			desc = "欢乐敲金蛋铜锤（V4-V7）",
		},
		[151]=
		{
			id = 151,
			item_id = 151,
			item_key = "prop_silver_hammer_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz3",
			is_show_bag = 0,
			order = 100,
			name = "银锤",
			desc = "欢乐敲金蛋银锤（V4-V7）",
		},
		[152]=
		{
			id = 152,
			item_id = 152,
			item_key = "prop_gold_hammer_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz4",
			is_show_bag = 0,
			order = 100,
			name = "金锤",
			desc = "欢乐敲金蛋金锤（V4-V7）",
		},
		[153]=
		{
			id = 153,
			item_id = 153,
			item_key = "prop_brass_hammer_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz2",
			is_show_bag = 0,
			order = 100,
			name = "铜锤",
			desc = "欢乐敲金蛋铜锤（v8-v12)",
		},
		[154]=
		{
			id = 154,
			item_id = 154,
			item_key = "prop_silver_hammer_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz3",
			is_show_bag = 0,
			order = 100,
			name = "银锤",
			desc = "欢乐敲金蛋银锤（v8-v12)",
		},
		[155]=
		{
			id = 155,
			item_id = 155,
			item_key = "prop_gold_hammer_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cz4",
			is_show_bag = 0,
			order = 100,
			name = "金锤",
			desc = "欢乐敲金蛋金锤（v8-v12)",
		},
		[156]=
		{
			id = 156,
			item_id = 156,
			item_key = "prop_double_card_brass",
			lose_time = -1,
			is_local_icon = 1,
			image = "sxlb_icon_tk",
			is_show_bag = 0,
			order = 100,
			name = "翻倍铜卡",
			desc = "盛夏礼包购买获得",
		},
		[157]=
		{
			id = 157,
			item_id = 157,
			item_key = "prop_double_card_silver",
			lose_time = -1,
			is_local_icon = 1,
			image = "sxlb_icon_yk",
			is_show_bag = 0,
			order = 100,
			name = "翻倍银卡",
			desc = "盛夏礼包购买获得",
		},
		[158]=
		{
			id = 158,
			item_id = 158,
			item_key = "prop_double_card_gold",
			lose_time = -1,
			is_local_icon = 1,
			image = "sxlb_icon_jk",
			is_show_bag = 0,
			order = 100,
			name = "翻倍金卡",
			desc = "盛夏礼包购买获得",
		},
		[159]=
		{
			id = 159,
			item_id = 159,
			item_key = "fake22",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift200_wz",
			is_show_bag = 0,
			order = 100,
			name = "夏日短袜",
			desc = "美的空调品牌赛奖励",
		},
		[160]=
		{
			id = 160,
			item_id = 160,
			item_key = "prop_grade",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_f",
			is_show_bag = 0,
			order = 100,
			name = "积分",
			desc = "用于积分榜单排名",
		},
		[161]=
		{
			id = 161,
			item_id = 161,
			item_key = "prop_double_card_ppc",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_fb",
			is_show_bag = 1,
			order = 100,
			name = "翻倍卡",
			desc = "翻倍卡只在斗地主新手场生效（不包含二人斗地主），每次胜利自动使用，结算福卡兑换不享受翻倍。",
		},
		[162]=
		{
			id = 162,
			item_id = 162,
			item_key = "prop_fish_drop_act_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "jfbd_icon_yb1",
			is_show_bag = 0,
			order = 100,
			name = "蛋黄月饼",
			desc = "用于好礼兑换活动兑换奖励",
		},
		[163]=
		{
			id = 163,
			item_id = 163,
			item_key = "prop_fish_drop_act_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "jfbd_icon_yb2",
			is_show_bag = 0,
			order = 100,
			name = "水果月饼",
			desc = "用于好礼兑换活动兑换奖励",
		},
		[164]=
		{
			id = 164,
			item_id = 164,
			item_key = "prop_fish_drop_act_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "jfbd_icon_yb3",
			is_show_bag = 0,
			order = 100,
			name = "豆沙月饼",
			desc = "用于好礼兑换活动兑换奖励",
		},
		[165]=
		{
			id = 165,
			item_id = 165,
			item_key = "prop_fish_drop_act_4",
			lose_time = -1,
			is_local_icon = 1,
			image = "jfbd_icon_yb4",
			is_show_bag = 0,
			order = 100,
			name = "五仁月饼",
			desc = "用于好礼兑换活动兑换奖励",
		},
		[166]=
		{
			id = 166,
			item_id = 166,
			item_key = "prop_fish_drop_act_0",
			lose_time = -1,
			is_local_icon = 1,
			image = "act_ty_by_drop_7",
			is_show_bag = 0,
			order = 100,
			name = "气球",
			desc = "用于参加好礼兑换活动",
		},
		[167]=
		{
			id = 167,
			item_id = 167,
			item_key = "prop_imperial",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_hg",
			is_show_bag = 0,
			order = 100,
			name = "皇冠",
			desc = "收集领好礼活动累计赢金获得",
		},
		[168]=
		{
			id = 168,
			item_id = 168,
			item_key = "prop_rare_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "ad_76_1",
			is_show_bag = 1,
			order = 1,
			name = "稀有宝箱",
			desc = "周年庆期间开启，最高可得5元福卡！",
			use_parm = {"open_box_new","prop_rare_box"},
			box_id = 55,
		},
		[169]=
		{
			id = 169,
			item_id = 169,
			item_key = "prop_epic_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "ad_76_2",
			is_show_bag = 1,
			order = 1,
			name = "史诗宝箱",
			desc = "周年庆期间开启，最高可得10元福卡！",
			use_parm = {"open_box_new","prop_epic_box"},
			box_id = 56,
		},
		[170]=
		{
			id = 170,
			item_id = 170,
			item_key = "prop_legend_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "ad_76_3",
			is_show_bag = 1,
			order = 1,
			name = "传说宝箱",
			desc = "周年庆期间开启，最高可得20元福卡！",
			use_parm = {"open_box_new","prop_legend_box"},
			box_id = 57,
		},
		[171]=
		{
			id = 171,
			item_id = 171,
			item_key = "fake23",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift213_hwsj",
			is_show_bag = 0,
			order = 100,
			name = "华为手机",
			desc = "国庆福利赛比赛奖励",
		},
		[172]=
		{
			id = 172,
			item_id = 172,
			item_key = "fake24",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift211_hwpb",
			is_show_bag = 0,
			order = 100,
			name = "华为平板",
			desc = "国庆福利赛比赛奖励",
		},
		[173]=
		{
			id = 173,
			item_id = 173,
			item_key = "fake25",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift212_hwsh",
			is_show_bag = 0,
			order = 100,
			name = "华为手环",
			desc = "国庆福利赛比赛奖励",
		},
		[174]=
		{
			id = 174,
			item_id = 174,
			item_key = "fake26",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift214_yg",
			is_show_bag = 0,
			order = 100,
			name = "佳洁士牙膏",
			desc = "华为手机品牌赛预约奖励",
		},
		[175]=
		{
			id = 175,
			item_id = 175,
			item_key = "prop_2year_jinianbi1",
			lose_time = -1,
			is_local_icon = 1,
			image = "yjlqjnb_icon_jnb",
			is_show_bag = 1,
			order = 100,
			name = "纪念币",
			desc = "2周年活动一期纪念币",
		},
		[176]=
		{
			id = 176,
			item_id = 176,
			item_key = "prop_2year_jinianbi2",
			lose_time = -1,
			is_local_icon = 1,
			image = "yjlqjnb_icon_jnb",
			is_show_bag = 1,
			order = 100,
			name = "纪念币",
			desc = "2周年活动二期纪念币",
		},
		[177]=
		{
			id = 177,
			item_id = 177,
			item_key = "prop_2year_jinianbi3",
			lose_time = -1,
			is_local_icon = 1,
			image = "yjlqjnb_icon_jnb",
			is_show_bag = 1,
			order = 100,
			name = "纪念币",
			desc = "2周年活动三期纪念币",
		},
		[178]=
		{
			id = 178,
			item_id = 178,
			item_key = "obj_5_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq1",
			is_show_bag = 1,
			order = 8,
			name = "5元优惠券",
			desc = "充值商城中购买50元档次鲸币时使用，可抵扣5元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[179]=
		{
			id = 179,
			item_id = 179,
			item_key = "obj_10_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq2",
			is_show_bag = 1,
			order = 7,
			name = "10元优惠券",
			desc = "充值商城中购买98元档次鲸币时使用，可抵扣10元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[180]=
		{
			id = 180,
			item_id = 180,
			item_key = "obj_20_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq3",
			is_show_bag = 1,
			order = 6,
			name = "20元优惠券",
			desc = "充值商城中购买198元档次鲸币时使用，可抵扣20元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[181]=
		{
			id = 181,
			item_id = 181,
			item_key = "obj_50_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq4",
			is_show_bag = 1,
			order = 5,
			name = "50元优惠券",
			desc = "充值商城中购买498元档次鲸币时使用，可抵扣50元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[182]=
		{
			id = 182,
			item_id = 182,
			item_key = "obj_100_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq5",
			is_show_bag = 1,
			order = 4,
			name = "100元优惠券",
			desc = "充值商城中购买998元档次鲸币时使用，可抵扣100元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[183]=
		{
			id = 183,
			item_id = 183,
			item_key = "obj_200_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_czyhq6",
			is_show_bag = 1,
			order = 3,
			name = "200元优惠券",
			desc = "充值商城中购买2498元档次鲸币时使用，可抵扣200元（有首冲加赠时无法使用）",
			desc_extra = "充值商城中可使用",
			use_parm = {"shop_bay","jing_bi"},
		},
		[184]=
		{
			id = 184,
			item_id = 184,
			item_key = "prop_2year_zhou",
			lose_time = -1,
			is_local_icon = 1,
			image = "djjzhhl_icon_znqd1",
			is_show_bag = 1,
			order = 100,
			name = "周",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[185]=
		{
			id = 185,
			item_id = 185,
			item_key = "prop_2year_nian",
			lose_time = -1,
			is_local_icon = 1,
			image = "djjzhhl_icon_znqd2",
			is_show_bag = 1,
			order = 100,
			name = "年",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[186]=
		{
			id = 186,
			item_id = 186,
			item_key = "prop_2year_qing",
			lose_time = -1,
			is_local_icon = 1,
			image = "djjzhhl_icon_znqd3",
			is_show_bag = 1,
			order = 100,
			name = "庆",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[187]=
		{
			id = 187,
			item_id = 187,
			item_key = "prop_2year_dian",
			lose_time = -1,
			is_local_icon = 1,
			image = "djjzhhl_icon_znqd4",
			is_show_bag = 1,
			order = 100,
			name = "典",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[188]=
		{
			id = 188,
			item_id = 188,
			item_key = "prop_2year_wan",
			lose_time = -1,
			is_local_icon = 1,
			image = "djjzhhl_icon_znqd5",
			is_show_bag = 1,
			order = 100,
			name = "万",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[189]=
		{
			id = 189,
			item_id = 189,
			item_key = "prop_2year_gift1",
			lose_time = -1,
			is_local_icon = 1,
			image = "eznhk_icon_1",
			is_show_bag = 1,
			order = 100,
			name = "鲸币礼包",
			desc = "最高可获得10万鲸币！",
			use_parm = {"open_box_new","prop_2year_gift1"},
			box_id = 60,
		},
		[190]=
		{
			id = 190,
			item_id = 190,
			item_key = "prop_2year_gift2",
			lose_time = -1,
			is_local_icon = 1,
			image = "eznhk_icon_2",
			is_show_bag = 1,
			order = 100,
			name = "鲸币宝箱",
			desc = "最高可获得50万鲸币！",
			use_parm = {"open_box_new","prop_2year_gift2"},
			box_id = 61,
		},
		[191]=
		{
			id = 191,
			item_id = 191,
			item_key = "prop_2year_gift3",
			lose_time = -1,
			is_local_icon = 1,
			image = "eznhk_icon_3",
			is_show_bag = 1,
			order = 100,
			name = "大额鲸币宝箱",
			desc = "最高可获得200万鲸币！",
			use_parm = {"open_box_new","prop_2year_gift3"},
			box_id = 62,
		},
		[192]=
		{
			id = 192,
			item_id = 192,
			item_key = "prop_2year_gift4",
			lose_time = -1,
			is_local_icon = 1,
			image = "eznhk_icon_4",
			is_show_bag = 1,
			order = 100,
			name = "巨额鲸币宝箱",
			desc = "最高可获得500万鲸币！",
			use_parm = {"open_box_new","prop_2year_gift4"},
			box_id = 63,
		},
		[193]=
		{
			id = 193,
			item_id = 193,
			item_key = "prop_2year_gift5",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift201_dlb",
			is_show_bag = 0,
			order = 100,
			name = "回馈大礼包",
			desc = "回馈大礼包：保温杯，自动雨伞，笔记本和签字笔",
		},
		[194]=
		{
			id = 194,
			item_id = 194,
			item_key = "prop_2year_silvercoin",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift203_jnb",
			is_show_bag = 0,
			order = 100,
			name = "纯银纪念币",
			desc = "纯银纪念币：鲸鱼新家园专属纪念币",
		},
		[195]=
		{
			id = 195,
			item_id = 195,
			item_key = "prop_2year_goldbeads",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift202_zyz",
			is_show_bag = 0,
			order = 100,
			name = "黄金转运珠",
			desc = "黄金转运珠：12生肖黄金转运珠",
		},
		[196]=
		{
			id = 196,
			item_id = 196,
			item_key = "prop_2year_pintu1",
			lose_time = -1,
			is_local_icon = 1,
			image = "djpt_icon_1",
			is_show_bag = 1,
			order = 100,
			name = "图1",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[197]=
		{
			id = 197,
			item_id = 197,
			item_key = "prop_2year_pintu2",
			lose_time = -1,
			is_local_icon = 1,
			image = "djpt_icon_2",
			is_show_bag = 1,
			order = 100,
			name = "图2",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[198]=
		{
			id = 198,
			item_id = 198,
			item_key = "prop_2year_pintu3",
			lose_time = -1,
			is_local_icon = 1,
			image = "djpt_icon_3",
			is_show_bag = 1,
			order = 100,
			name = "图3",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[199]=
		{
			id = 199,
			item_id = 199,
			item_key = "prop_2year_pintu4",
			lose_time = -1,
			is_local_icon = 1,
			image = "djpt_icon_4",
			is_show_bag = 1,
			order = 100,
			name = "图4",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[200]=
		{
			id = 200,
			item_id = 200,
			item_key = "prop_2year_pintu5",
			lose_time = -1,
			is_local_icon = 1,
			image = "djpt_icon_wnt",
			is_show_bag = 1,
			order = 100,
			name = "万能图",
			desc = "周年庆典，兑换2周年纪念币",
		},
		[201]=
		{
			id = 201,
			item_id = 201,
			item_key = "_common_rank_anniversary_celebration_score_rank",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jf",
			is_show_bag = 1,
			order = 100,
			name = "积分",
			desc = "周年庆典，积分达人榜排行标准",
		},
		[202]=
		{
			id = 202,
			item_id = 202,
			item_key = "prop_brass_key_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_6",
			is_show_bag = 0,
			order = 100,
			name = "铜钥匙",
			desc = "欢乐开宝箱铜钥匙",
		},
		[203]=
		{
			id = 203,
			item_id = 203,
			item_key = "prop_silver_key_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_5",
			is_show_bag = 0,
			order = 100,
			name = "银钥匙",
			desc = "欢乐开宝箱银钥匙",
		},
		[204]=
		{
			id = 204,
			item_id = 204,
			item_key = "prop_gold_key_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_4",
			is_show_bag = 0,
			order = 100,
			name = "金钥匙",
			desc = "欢乐开宝箱金钥匙",
		},
		[205]=
		{
			id = 205,
			item_id = 205,
			item_key = "prop_brass_key_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_6",
			is_show_bag = 0,
			order = 100,
			name = "铜钥匙",
			desc = "欢乐开宝箱铜钥匙",
		},
		[206]=
		{
			id = 206,
			item_id = 206,
			item_key = "prop_silver_key_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_5",
			is_show_bag = 0,
			order = 100,
			name = "银钥匙",
			desc = "欢乐开宝箱银钥匙",
		},
		[207]=
		{
			id = 207,
			item_id = 207,
			item_key = "prop_gold_key_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_4",
			is_show_bag = 0,
			order = 100,
			name = "金钥匙",
			desc = "欢乐开宝箱金钥匙",
		},
		[208]=
		{
			id = 208,
			item_id = 208,
			item_key = "prop_brass_key_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_6",
			is_show_bag = 0,
			order = 100,
			name = "铜钥匙",
			desc = "欢乐开宝箱铜钥匙",
		},
		[209]=
		{
			id = 209,
			item_id = 209,
			item_key = "prop_silver_key_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_5",
			is_show_bag = 0,
			order = 100,
			name = "银钥匙",
			desc = "欢乐开宝箱银钥匙",
		},
		[210]=
		{
			id = 210,
			item_id = 210,
			item_key = "prop_gold_key_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "hlkbx_icon_4",
			is_show_bag = 0,
			order = 100,
			name = "金钥匙",
			desc = "欢乐开宝箱金钥匙",
		},
		[211]=
		{
			id = 211,
			item_id = 211,
			item_key = "prop_031_aster",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_icon_xx2",
			is_show_bag = 0,
			order = 100,
			name = "星星",
			desc = "国庆快乐活动获得道具",
		},
		[212]=
		{
			id = 212,
			item_id = 212,
			item_key = "_common_rank_happy_guoqing_aster_rank",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_icon_xx2",
			is_show_bag = 0,
			order = 100,
			name = "积分",
			desc = "国庆快乐活动获得道具",
		},
		[213]=
		{
			id = 213,
			item_id = 213,
			item_key = "prop_new_1y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_1yhf",
			is_show_bag = 1,
			order = 24,
			name = "1福卡赛门票",
			desc = "用于参加1福卡赛",
			use_parm = {"match_hall","fls"},
		},
		[214]=
		{
			id = 214,
			item_id = 214,
			item_key = "prop_new_10y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_10fks",
			is_show_bag = 1,
			order = 24,
			name = "10福卡赛门票",
			desc = "用于参加10福卡赛",
			use_parm = {"match_hall","fks"},
		},
		[215]=
		{
			id = 215,
			item_id = 215,
			item_key = "prop_new_50y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50yhf",
			is_show_bag = 1,
			order = 24,
			name = "50元话费赛门票",
			desc = "用于参加50元话费赛",
			use_parm = {"match_hall","fls"},
		},
		[216]=
		{
			id = 216,
			item_id = 216,
			item_key = "prop_new_100y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100fks",
			is_show_bag = 1,
			order = 24,
			name = "100福卡赛门票",
			desc = "用于参加100元话费赛",
			use_parm = {"match_hall","fls"},
		},
		[217]=
		{
			id = 217,
			item_id = 217,
			item_key = "prop_new_200y_before_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_200jdkys",
			is_show_bag = 1,
			order = 24,
			name = "<size=28>200元JD卡预赛门票</size>",
			desc = "用于参加200元JD卡预赛",
			use_parm = {"match_hall","fls"},
		},
		[218]=
		{
			id = 218,
			item_id = 218,
			item_key = "prop_new_200y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_200jdkjs",
			is_show_bag = 1,
			order = 24,
			name = "<size=28>200元JD卡决赛门票</size>",
			desc = "用于参加200元JD卡决赛",
			use_parm = {"match_hall","djs"},
		},
		[219]=
		{
			id = 219,
			item_id = 219,
			item_key = "obj_prop_new_1y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_1yhf",
			is_show_bag = 1,
			order = 24,
			name = "1福卡赛门票",
			desc = "用于参加1福卡赛",
			use_parm = {"match_hall","fls"},
		},
		[220]=
		{
			id = 220,
			item_id = 220,
			item_key = "obj_prop_new_10y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_10fks",
			is_show_bag = 1,
			order = 24,
			name = "10福卡赛门票",
			desc = "用于参加10福卡赛",
			use_parm = {"match_hall","fks"},
		},
		[221]=
		{
			id = 221,
			item_id = 221,
			item_key = "obj_prop_new_50y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_50yhf",
			is_show_bag = 1,
			order = 24,
			name = "50元话费赛门票",
			desc = "用于参加50元话费赛",
			use_parm = {"match_hall","fls"},
		},
		[222]=
		{
			id = 222,
			item_id = 222,
			item_key = "obj_prop_new_100y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_100fks",
			is_show_bag = 1,
			order = 24,
			name = "100福卡赛门票",
			desc = "用于参加100元话费赛",
			use_parm = {"match_hall","fls"},
		},
		[223]=
		{
			id = 223,
			item_id = 223,
			item_key = "obj_prop_new_200y_before_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_200jdkys",
			is_show_bag = 1,
			order = 24,
			name = "<size=28>200元JD卡预赛门票</size>",
			desc = "用于参加200元JD卡预赛",
			use_parm = {"match_hall","fls"},
		},
		[224]=
		{
			id = 224,
			item_id = 224,
			item_key = "obj_prop_new_200y_ticket",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_200jdkjs",
			is_show_bag = 1,
			order = 24,
			name = "<size=28>200元JD卡决赛门票</size>",
			desc = "用于参加200元JD卡决赛",
			use_parm = {"match_hall","djs"},
		},
		[225]=
		{
			id = 225,
			item_id = 225,
			item_key = "fake27",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift230_bscz",
			is_show_bag = 0,
			order = 100,
			name = "本色抽纸",
			desc = "华为P40比赛预约奖励",
		},
		[226]=
		{
			id = 226,
			item_id = 226,
			item_key = "prop_sgxxl_apple",
			lose_time = -1,
			is_local_icon = 1,
			image = "xxl_iconnew_7",
			is_show_bag = 0,
			order = 100,
			name = "苹果",
			desc = "水果消消乐",
		},
		[227]=
		{
			id = 227,
			item_id = 227,
			item_key = "prop_sgxxl_bell",
			lose_time = -1,
			is_local_icon = 1,
			image = "xxl_iconnew_8",
			is_show_bag = 0,
			order = 100,
			name = "铃铛",
			desc = "水果消消乐",
		},
		[228]=
		{
			id = 228,
			item_id = 228,
			item_key = "prop_sgxxl_watermelon",
			lose_time = -1,
			is_local_icon = 1,
			image = "xxl_iconnew_9",
			is_show_bag = 0,
			order = 100,
			name = "西瓜",
			desc = "水果消消乐",
		},
		[229]=
		{
			id = 229,
			item_id = 229,
			item_key = "prop_sgxxl_redseven",
			lose_time = -1,
			is_local_icon = 1,
			image = "xxl_iconnew_10",
			is_show_bag = 0,
			order = 100,
			name = "红7",
			desc = "水果消消乐",
		},
		[230]=
		{
			id = 230,
			item_id = 230,
			item_key = "prop_sgxxl_bar",
			lose_time = -1,
			is_local_icon = 1,
			image = "xxl_iconnew_11",
			is_show_bag = 0,
			order = 100,
			name = "BAR",
			desc = "水果消消乐",
		},
		[231]=
		{
			id = 231,
			item_id = 231,
			item_key = "prop_shxxl_bowl",
			lose_time = -1,
			is_local_icon = 1,
			image = "shxxl_iconnew_1",
			is_show_bag = 0,
			order = 100,
			name = "酒碗",
			desc = "水浒消消乐",
		},
		[232]=
		{
			id = 232,
			item_id = 232,
			item_key = "prop_shxxl_winejar",
			lose_time = -1,
			is_local_icon = 1,
			image = "shxxl_iconnew_2",
			is_show_bag = 0,
			order = 100,
			name = "酒坛",
			desc = "水浒消消乐",
		},
		[233]=
		{
			id = 233,
			item_id = 233,
			item_key = "prop_shxxl_coin",
			lose_time = -1,
			is_local_icon = 1,
			image = "shxxl_iconnew_3",
			is_show_bag = 0,
			order = 100,
			name = "铜钱",
			desc = "水浒消消乐",
		},
		[234]=
		{
			id = 234,
			item_id = 234,
			item_key = "prop_shxxl_ingot",
			lose_time = -1,
			is_local_icon = 1,
			image = "shxxl_iconnew_4",
			is_show_bag = 0,
			order = 100,
			name = "元宝",
			desc = "水浒消消乐",
		},
		[235]=
		{
			id = 235,
			item_id = 235,
			item_key = "prop_shxxl_axe",
			lose_time = -1,
			is_local_icon = 1,
			image = "shxxl_iconnew_5",
			is_show_bag = 0,
			order = 100,
			name = "斧头",
			desc = "水浒消消乐",
		},
		[236]=
		{
			id = 236,
			item_id = 236,
			item_key = "prop_csxxl_coin",
			lose_time = -1,
			is_local_icon = 1,
			image = "csxxl_iconnew_1",
			is_show_bag = 0,
			order = 100,
			name = "铜钱",
			desc = "财神消消乐",
		},
		[237]=
		{
			id = 237,
			item_id = 237,
			item_key = "prop_csxxl_gemstone",
			lose_time = -1,
			is_local_icon = 1,
			image = "csxxl_iconnew_2",
			is_show_bag = 0,
			order = 100,
			name = "宝石",
			desc = "财神消消乐",
		},
		[238]=
		{
			id = 238,
			item_id = 238,
			item_key = "prop_csxxl_ruyi",
			lose_time = -1,
			is_local_icon = 1,
			image = "csxxl_iconnew_3",
			is_show_bag = 0,
			order = 100,
			name = "如意",
			desc = "财神消消乐",
		},
		[239]=
		{
			id = 239,
			item_id = 239,
			item_key = "prop_csxxl_goldpig",
			lose_time = -1,
			is_local_icon = 1,
			image = "csxxl_iconnew_4",
			is_show_bag = 0,
			order = 100,
			name = "金猪",
			desc = "财神消消乐",
		},
		[240]=
		{
			id = 240,
			item_id = 240,
			item_key = "prop_csxxl_mammon",
			lose_time = -1,
			is_local_icon = 1,
			image = "csxxl_iconnew_5",
			is_show_bag = 0,
			order = 100,
			name = "财神",
			desc = "财神消消乐",
		},
		[241]=
		{
			id = 241,
			item_id = 241,
			item_key = "prop_xyxxl_kasaya",
			lose_time = -1,
			is_local_icon = 1,
			image = "sdbgj_iconnew_1",
			is_show_bag = 0,
			order = 100,
			name = "袈裟",
			desc = "西游消消乐",
		},
		[242]=
		{
			id = 242,
			item_id = 242,
			item_key = "prop_xyxxl_goldbowl",
			lose_time = -1,
			is_local_icon = 1,
			image = "sdbgj_iconnew_2",
			is_show_bag = 0,
			order = 100,
			name = "金钵",
			desc = "西游消消乐",
		},
		[243]=
		{
			id = 243,
			item_id = 243,
			item_key = "prop_xyxxl_jadevase",
			lose_time = -1,
			is_local_icon = 1,
			image = "sdbgj_iconnew_3",
			is_show_bag = 0,
			order = 100,
			name = "玉瓶",
			desc = "西游消消乐",
		},
		[244]=
		{
			id = 244,
			item_id = 244,
			item_key = "prop_xyxxl_sapodilla",
			lose_time = -1,
			is_local_icon = 1,
			image = "sdbgj_iconnew_4",
			is_show_bag = 0,
			order = 100,
			name = "人参果",
			desc = "西游消消乐",
		},
		[245]=
		{
			id = 245,
			item_id = 245,
			item_key = "prop_xyxxl_scripture",
			lose_time = -1,
			is_local_icon = 1,
			image = "sdbgj_iconnew_5",
			is_show_bag = 0,
			order = 100,
			name = "经文",
			desc = "西游消消乐",
		},
		[246]=
		{
			id = 246,
			item_id = 246,
			item_key = "_common_rank_xiaoxiaolezb_031_rank",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jf",
			is_show_bag = 0,
			order = 100,
			name = "积分",
			desc = "消消乐争霸活动积分",
		},
		[247]=
		{
			id = 247,
			item_id = 247,
			item_key = "prop_chongyang_chrysanthemum",
			lose_time = -1,
			is_local_icon = 1,
			image = "cyhhl_icon_jh",
			is_show_bag = 0,
			order = 100,
			name = "菊花",
			desc = "九九重阳活动获得",
		},
		[248]=
		{
			id = 248,
			item_id = 248,
			item_key = "fake_28",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift236_qlys",
			is_show_bag = 0,
			order = 100,
			name = "情侣牙刷",
			desc = "小米电视比赛奖励",
		},
		[249]=
		{
			id = 249,
			item_id = 249,
			item_key = "fake_29",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift237_xmds",
			is_show_bag = 0,
			order = 100,
			name = "小米电视",
			desc = "小米电视比赛奖励",
		},
		[250]=
		{
			id = 250,
			item_id = 250,
			item_key = "fake_30",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift238_xmxlx",
			is_show_bag = 0,
			order = 100,
			name = "小米行李箱",
			desc = "小米电视比赛奖励",
		},
		[251]=
		{
			id = 251,
			item_id = 251,
			item_key = "fake_31",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift239_xmsb",
			is_show_bag = 0,
			order = 100,
			name = "小米手表",
			desc = "小米电视比赛奖励",
		},
		[252]=
		{
			id = 252,
			item_id = 252,
			item_key = "prop_bzth_coupon",
			lose_time = -1,
			is_local_icon = 1,
			image = "bzth_iocn_xfq",
			is_show_bag = 0,
			order = 100,
			name = "消费券",
			desc = "备战双11活动奖励",
		},
		[253]=
		{
			id = 253,
			item_id = 253,
			item_key = "prop_double11_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "ad_76_2",
			is_show_bag = 1,
			order = 100,
			name = "双11宝箱",
			desc = "11月10日7:30~11月16日23:59:59期间可开启。",
			use_parm = {"open_box_new","prop_double11_box"},
			box_id = 111,
		},
		[254]=
		{
			id = 254,
			item_id = 254,
			item_key = "prop_double11_cjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖券",
			desc = "双十一礼包购买获得",
		},
		[255]=
		{
			id = 255,
			item_id = 255,
			item_key = "prop_double11_giftbox",
			lose_time = -1,
			is_local_icon = 1,
			image = "ty_icon_lh",
			is_show_bag = 0,
			order = 100,
			name = "礼盒",
			desc = "疯狂双十一活动鱼掉落道具",
		},
		[256]=
		{
			id = 256,
			item_id = 256,
			item_key = "prop_gnyl_drumstick",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_icon_jt",
			is_show_bag = 0,
			order = 100,
			name = "鸡腿",
			desc = "感恩有礼活动鱼掉落道具",
		},
		[257]=
		{
			id = 257,
			item_id = 257,
			item_key = "fake_32",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift241_reno",
			is_show_bag = 0,
			order = 100,
			name = "Reno4 SE",
			desc = "OPPO手机比赛奖励",
		},
		[258]=
		{
			id = 258,
			item_id = 258,
			item_key = "fake_33",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift242_oppowatch",
			is_show_bag = 0,
			order = 100,
			name = "OPPO Watch",
			desc = "OPPO手机比赛奖励",
		},
		[259]=
		{
			id = 259,
			item_id = 259,
			item_key = "fake_34",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift244_opposh",
			is_show_bag = 0,
			order = 100,
			name = "OPPO手环",
			desc = "OPPO手机比赛奖励",
		},
		[260]=
		{
			id = 260,
			item_id = 260,
			item_key = "fake_35",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift243_cmcw",
			is_show_bag = 0,
			order = 100,
			name = "纯棉长袜",
			desc = "OPPO手机比赛奖励",
		},
		[261]=
		{
			id = 261,
			item_id = 261,
			item_key = "prop_040_snowball",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_icon_xq",
			is_show_bag = 0,
			order = 100,
			name = "雪球",
			desc = "雪球大战活动鱼掉落道具",
		},
		[262]=
		{
			id = 262,
			item_id = 262,
			item_key = "prop_zhshe_giftbox",
			lose_time = -1,
			is_local_icon = 1,
			image = "ty_icon_lh",
			is_show_bag = 0,
			order = 100,
			name = "礼物",
			desc = "再惠双十二活动鱼掉落道具",
		},
		[263]=
		{
			id = 263,
			item_id = 263,
			item_key = "prop_xyzzl_cjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "幸运转转乐抽奖券",
			desc = "可用于参加幸运转转乐活动",
		},
		[264]=
		{
			id = 264,
			item_id = 264,
			item_key = "prop_sdcdj_cjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "圣诞抽大奖抽奖券",
			desc = "可用于参加圣诞抽大奖活动",
		},
		[265]=
		{
			id = 265,
			item_id = 265,
			item_key = "fake_36",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift253_kt",
			is_show_bag = 0,
			order = 100,
			name = "美的空调",
			desc = "美的空调赛奖励",
		},
		[266]=
		{
			id = 266,
			item_id = 266,
			item_key = "fake_37",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift254_xcq",
			is_show_bag = 0,
			order = 100,
			name = "吸尘器",
			desc = "开年福利赛奖励",
		},
		[267]=
		{
			id = 267,
			item_id = 267,
			item_key = "fake_38",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift255_drt",
			is_show_bag = 0,
			order = 100,
			name = "电热毯",
			desc = "开年福利赛奖励",
		},
		[268]=
		{
			id = 268,
			item_id = 268,
			item_key = "prop_fishingmedal",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_cjd",
			is_show_bag = 0,
			order = 100,
			name = "捕鱼勋章",
			desc = "可用于参加捕鱼宝库抽奖",
		},
		[269]=
		{
			id = 269,
			item_id = 269,
			item_key = "prop_bybk_xhy",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_xhy",
			is_show_bag = 0,
			order = 100,
			name = "小黄鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[270]=
		{
			id = 270,
			item_id = 270,
			item_key = "prop_bybk_xly",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_xly",
			is_show_bag = 0,
			order = 100,
			name = "小蓝鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[271]=
		{
			id = 271,
			item_id = 271,
			item_key = "prop_bybk_cwy",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_cwy",
			is_show_bag = 0,
			order = 100,
			name = "彩纹鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[272]=
		{
			id = 272,
			item_id = 272,
			item_key = "prop_bybk_lht",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_lht",
			is_show_bag = 0,
			order = 100,
			name = "蓝河豚图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[273]=
		{
			id = 273,
			item_id = 273,
			item_key = "prop_bybk_xcy",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_xcy",
			is_show_bag = 0,
			order = 100,
			name = "小丑鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[274]=
		{
			id = 274,
			item_id = 274,
			item_key = "prop_bybk_ldy",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_ldy",
			is_show_bag = 0,
			order = 100,
			name = "蓝灯鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[275]=
		{
			id = 275,
			item_id = 275,
			item_key = "prop_bybk_hsy",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_hsy",
			is_show_bag = 0,
			order = 100,
			name = "红杉鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[276]=
		{
			id = 276,
			item_id = 276,
			item_key = "prop_bybk_hg",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_hg",
			is_show_bag = 0,
			order = 100,
			name = "海龟图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[277]=
		{
			id = 277,
			item_id = 277,
			item_key = "prop_bybk_dly",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_dly",
			is_show_bag = 0,
			order = 100,
			name = "灯笼鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[278]=
		{
			id = 278,
			item_id = 278,
			item_key = "prop_bybk_mgy",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_mgy",
			is_show_bag = 0,
			order = 100,
			name = "魔鬼鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[279]=
		{
			id = 279,
			item_id = 279,
			item_key = "prop_bybk_dbs",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_dbs",
			is_show_bag = 0,
			order = 100,
			name = "大白鲨图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[280]=
		{
			id = 280,
			item_id = 280,
			item_key = "prop_bybk_cts",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_cts",
			is_show_bag = 0,
			order = 100,
			name = "锤头鲨图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[281]=
		{
			id = 281,
			item_id = 281,
			item_key = "prop_bybk_hjhg",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_hjhg",
			is_show_bag = 0,
			order = 100,
			name = "黄金海龟图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[282]=
		{
			id = 282,
			item_id = 282,
			item_key = "prop_bybk_hjdly",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_hjdly",
			is_show_bag = 0,
			order = 100,
			name = "黄金灯笼鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[283]=
		{
			id = 283,
			item_id = 283,
			item_key = "prop_bybk_hjmgy",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_hjmgy",
			is_show_bag = 0,
			order = 100,
			name = "黄金魔鬼鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[284]=
		{
			id = 284,
			item_id = 284,
			item_key = "prop_bybk_hjdbs",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_hjdbs",
			is_show_bag = 0,
			order = 100,
			name = "黄金大白鲨图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[285]=
		{
			id = 285,
			item_id = 285,
			item_key = "prop_bybk_ppy",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_ppy_activity_act_046_bybk",
			is_show_bag = 0,
			order = 100,
			name = "胖胖鱼图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[286]=
		{
			id = 286,
			item_id = 286,
			item_key = "prop_bybk_hjcts",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_hjcts",
			is_show_bag = 0,
			order = 100,
			name = "黄金锤头鲨图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[287]=
		{
			id = 287,
			item_id = 287,
			item_key = "prop_bybk_cs",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_cs_activity_act_046_bybk",
			is_show_bag = 0,
			order = 100,
			name = "财神图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[288]=
		{
			id = 288,
			item_id = 288,
			item_key = "prop_bybk_hjl",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_hjl",
			is_show_bag = 0,
			order = 100,
			name = "黄金龙图鉴",
			desc = "用于狂欢图鉴兑换奖励",
		},
		[289]=
		{
			id = 289,
			item_id = 289,
			item_key = "prop_random_goldcoin_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "khtj_bx_2",
			is_show_bag = 1,
			order = 100,
			name = "随机鲸币宝箱",
			desc = "打开可随机获得10万~100万鲸币！",
			use_parm = {"open_box_new","prop_random_goldcoin_box"},
			box_id = 151,
		},
		[290]=
		{
			id = 290,
			item_id = 290,
			item_key = "prop_sjlb_v0_chun",
			lose_time = -1,
			is_local_icon = 1,
			image = "collect_words_1",
			is_show_bag = 0,
			order = 100,
			name = "春灵珠",
			desc = "用于兑换四季灵珠返利",
		},
		[291]=
		{
			id = 291,
			item_id = 291,
			item_key = "prop_sjlb_v0_xia",
			lose_time = -1,
			is_local_icon = 1,
			image = "collect_words_2",
			is_show_bag = 0,
			order = 100,
			name = "夏灵珠",
			desc = "用于兑换四季灵珠返利",
		},
		[292]=
		{
			id = 292,
			item_id = 292,
			item_key = "prop_sjlb_v0_qiu",
			lose_time = -1,
			is_local_icon = 1,
			image = "collect_words_3",
			is_show_bag = 0,
			order = 100,
			name = "秋灵珠",
			desc = "用于兑换四季灵珠返利",
		},
		[293]=
		{
			id = 293,
			item_id = 293,
			item_key = "prop_sjlb_v0_dong",
			lose_time = -1,
			is_local_icon = 1,
			image = "collect_words_4",
			is_show_bag = 0,
			order = 100,
			name = "冬灵珠",
			desc = "用于兑换四季灵珠返利",
		},
		[294]=
		{
			id = 294,
			item_id = 294,
			item_key = "fake_39",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift257_bwh",
			is_show_bag = 0,
			order = 100,
			name = "美的取暖器",
			desc = "美的空调赛奖励",
		},
		[295]=
		{
			id = 295,
			item_id = 295,
			item_key = "prop_048_xxlqd_sunshine",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_ty",
			is_show_bag = 0,
			order = 100,
			name = "阳光 ",
			desc = "消消乐庆典活动掉落道具",
		},
		[296]=
		{
			id = 296,
			item_id = 296,
			item_key = "prop_new_year_red_packet",
			lose_time = -1,
			is_local_icon = 1,
			image = "wflb_icon_xnhb",
			is_show_bag = 1,
			order = 100,
			name = "新年红包",
			desc = "新年红包：2021年2月11日后可拆开，有概率获得最高2万鲸币或2福卡或200话费碎片。",
			use_parm = {"open_box_new","prop_new_year_red_packet"},
			box_id = 152,
		},
		[297]=
		{
			id = 297,
			item_id = 297,
			item_key = "prop_050_mtcjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "xnsmt_img_cjq",
			is_show_bag = 0,
			order = 100,
			name = "茅台抽奖券",
			desc = "茅台抽奖券：可参与“新年送茅台”活动",
		},
		[298]=
		{
			id = 298,
			item_id = 298,
			item_key = "prop_maotai_suipian",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_mtsp",
			is_show_bag = 0,
			order = 100,
			name = "茅台碎片",
			desc = "可用于兑换飞天茅台奖励",
		},
		[299]=
		{
			id = 299,
			item_id = 299,
			item_key = "prop_051_gold_yuanbao",
			lose_time = -1,
			is_local_icon = 1,
			image = "cssl_iocn_jyb",
			is_show_bag = 0,
			order = 100,
			name = "金元宝",
			desc = "可参与财神送礼抽奖",
		},
		[300]=
		{
			id = 300,
			item_id = 300,
			item_key = "prop_grade_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_jf2",
			is_show_bag = 0,
			order = 100,
			name = "积分",
			desc = "用于参加积分达人排行榜",
		},
		[301]=
		{
			id = 301,
			item_id = 301,
			item_key = "prop_nyx_mouse",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_zs",
			is_show_bag = 0,
			order = 100,
			name = "鼠窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[302]=
		{
			id = 302,
			item_id = 302,
			item_key = "prop_nyx_cattle",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_cn",
			is_show_bag = 0,
			order = 100,
			name = "牛窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[303]=
		{
			id = 303,
			item_id = 303,
			item_key = "prop_nyx_tiger",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_yh",
			is_show_bag = 0,
			order = 100,
			name = "虎窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[304]=
		{
			id = 304,
			item_id = 304,
			item_key = "prop_nyx_rabbit",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_mt",
			is_show_bag = 0,
			order = 100,
			name = "兔窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[305]=
		{
			id = 305,
			item_id = 305,
			item_key = "prop_nyx_dragon",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_cl",
			is_show_bag = 0,
			order = 100,
			name = "龙窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[306]=
		{
			id = 306,
			item_id = 306,
			item_key = "prop_nyx_snake",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_ss",
			is_show_bag = 0,
			order = 100,
			name = "蛇窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[307]=
		{
			id = 307,
			item_id = 307,
			item_key = "prop_nyx_horse",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_wm",
			is_show_bag = 0,
			order = 100,
			name = "马窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[308]=
		{
			id = 308,
			item_id = 308,
			item_key = "prop_nyx_sheep",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_my",
			is_show_bag = 0,
			order = 100,
			name = "羊窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[309]=
		{
			id = 309,
			item_id = 309,
			item_key = "prop_nyx_monkey",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_sh",
			is_show_bag = 0,
			order = 100,
			name = "猴窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[310]=
		{
			id = 310,
			item_id = 310,
			item_key = "prop_nyx_chicken",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_yj",
			is_show_bag = 0,
			order = 100,
			name = "鸡窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[311]=
		{
			id = 311,
			item_id = 311,
			item_key = "prop_nyx_dog",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_qg",
			is_show_bag = 0,
			order = 100,
			name = "狗窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[312]=
		{
			id = 312,
			item_id = 312,
			item_key = "prop_nyx_pig",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_hz",
			is_show_bag = 0,
			order = 100,
			name = "猪窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[313]=
		{
			id = 313,
			item_id = 313,
			item_key = "prop_nyx_yuan",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_y",
			is_show_bag = 0,
			order = 100,
			name = "元窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[314]=
		{
			id = 314,
			item_id = 314,
			item_key = "prop_nyx_xiao",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_x",
			is_show_bag = 0,
			order = 100,
			name = "宵窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[315]=
		{
			id = 315,
			item_id = 315,
			item_key = "prop_nyx_kuai",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_k",
			is_show_bag = 0,
			order = 100,
			name = "快窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[316]=
		{
			id = 316,
			item_id = 316,
			item_key = "prop_nyx_le",
			lose_time = -1,
			is_local_icon = 1,
			image = "bk_icon_l",
			is_show_bag = 0,
			order = 100,
			name = "乐窗花",
			desc = "用于元宵图鉴兑换奖励",
		},
		[317]=
		{
			id = 317,
			item_id = 317,
			item_key = "fake_40",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift266_sqm",
			is_show_bag = 0,
			order = 100,
			name = "沙琪玛小零食",
			desc = "小米电视比赛奖励",
		},
		[318]=
		{
			id = 318,
			item_id = 318,
			item_key = "prop_new_player_red_bag",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_moeny2",
			is_show_bag = 0,
			order = 100,
			name = "红包券",
			desc = "活动中的一种道具，非游戏货币",
		},
		[319]=
		{
			id = 319,
			item_id = 319,
			item_key = "obj_next_day_box",
			lose_time = -1,
			is_local_icon = 1,
			image = "mrlb_icon_2",
			is_show_bag = 0,
			order = 100,
			name = "明日宝箱",
			desc = "次日可开启，有机会获得10元现金或10元话费或千元赛门票1张",
		},
		[320]=
		{
			id = 320,
			item_id = 320,
			item_key = "fake_41",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift223_jlyjdm",
			is_show_bag = 0,
			order = 100,
			name = "鸡蛋挂面",
			desc = "美的空调赛奖励",
		},
		[321]=
		{
			id = 321,
			item_id = 321,
			item_key = "prop_qmjz_xiang",
			lose_time = -1,
			is_local_icon = 1,
			image = "jzqf_icon_xiang",
			is_show_bag = 0,
			order = 100,
			name = "香",
			desc = "永远参加祭祖祈福活动",
		},
		[322]=
		{
			id = 322,
			item_id = 322,
			item_key = "prop_fish_accelerate",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_js2",
			is_show_bag = 1,
			order = 30,
			name = "加速卡",
			desc = "以1.5倍的速度进行发炮，持续15秒。",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[323]=
		{
			id = 323,
			item_id = 323,
			item_key = "prop_fish_doubled",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_jb2",
			is_show_bag = 1,
			order = 30,
			name = "双倍卡",
			desc = "捕鱼将获得双倍奖励，同时会提升消耗，持续15秒。",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[324]=
		{
			id = 324,
			item_id = 324,
			item_key = "prop_fish_wild",
			lose_time = -1,
			is_local_icon = 1,
			image = "by_btn_kb2",
			is_show_bag = 1,
			order = 30,
			name = "狂暴卡",
			desc = "子弹获得双倍威力，同时会提升消耗，持续15秒。",
			use_parm = {"game_FishingHall",},
			tag = 1,
		},
		[325]=
		{
			id = 325,
			item_id = 325,
			item_key = "fake_42",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift250_dbc",
			is_show_bag = 0,
			order = 100,
			name = "美的电饼铛",
			desc = "五一福利赛奖励",
		},
		[326]=
		{
			id = 326,
			item_id = 326,
			item_key = "fake_43",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift226_xmh",
			is_show_bag = 0,
			order = 100,
			name = "小麻花",
			desc = "五一福利赛奖励",
		},
		[327]=
		{
			id = 327,
			item_id = 327,
			item_key = "fake_44",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift164",
			is_show_bag = 0,
			order = 100,
			name = "迷你冰箱",
			desc = "月末福利赛奖励",
		},
		[328]=
		{
			id = 328,
			item_id = 328,
			item_key = "fake_45",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift277_mnfs",
			is_show_bag = 0,
			order = 100,
			name = "迷你风扇",
			desc = "夏日狂欢赛奖励",
		},
		[329]=
		{
			id = 329,
			item_id = 329,
			item_key = "fake_46",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift278_mdysj",
			is_show_bag = 0,
			order = 100,
			name = "美的饮水机",
			desc = "夏日狂欢赛奖励",
		},
		[330]=
		{
			id = 330,
			item_id = 330,
			item_key = "fake_47",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift181_ktb",
			is_show_bag = 0,
			order = 100,
			name = "空调被",
			desc = "夏日狂欢赛奖励",
		},
		[331]=
		{
			id = 331,
			item_id = 331,
			item_key = "prop_xxl_shuiguo_card_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_mcxxl_1",
			is_show_bag = 1,
			order = 13,
			name = "萌宠消消乐游戏卡",
			desc = "使用后可触发‘萌宠消消乐’500档次的特殊玩法",
			use_parm = {"game_Eliminate",},
		},
		[332]=
		{
			id = 332,
			item_id = 332,
			item_key = "prop_xxl_shuihu_card_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_shxxl_1",
			is_show_bag = 1,
			order = 13,
			name = "水浒消消乐游戏卡",
			desc = "使用后可触发‘水浒消消乐’500档次的特殊玩法",
			use_parm = {"game_EliminateSH",},
		},
		[333]=
		{
			id = 333,
			item_id = 333,
			item_key = "prop_xxl_caishen_card_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_csxxl_1",
			is_show_bag = 1,
			order = 13,
			name = "财神消消乐游戏卡",
			desc = "使用后可触发‘财神消消乐’500档次的特殊玩法",
			use_parm = {"game_EliminateCS",},
		},
		[334]=
		{
			id = 334,
			item_id = 334,
			item_key = "prop_xxl_xiyou_card_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_xyxxl_1",
			is_show_bag = 1,
			order = 13,
			name = "西游消消乐游戏卡",
			desc = "使用后可触发‘西游消消乐’500档次的特殊玩法",
			use_parm = {"game_EliminateXY",},
		},
		[335]=
		{
			id = 335,
			item_id = 335,
			item_key = "prop_xxl_chaoji_card_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_cjxxl_1",
			is_show_bag = 1,
			order = 13,
			name = "超级消消乐游戏卡",
			desc = "使用后可触发‘超级消消乐’500档次的特殊玩法",
			use_parm = {"game_EliminateCJ",},
		},
		[336]=
		{
			id = 336,
			item_id = 336,
			item_key = "prop_xxl_sanguo_card_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_sgxxl_11",
			is_show_bag = 1,
			order = 13,
			name = "三国消消乐游戏卡",
			desc = "使用后可触发‘三国消消乐’500档次的特殊玩法",
			use_parm = {"game_EliminateSG",},
		},
		[337]=
		{
			id = 337,
			item_id = 337,
			item_key = "prop_xxl_shuiguo_card_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_mcxxl_2",
			is_show_bag = 1,
			order = 12,
			name = "萌宠消消乐游戏卡",
			desc = "使用后可触发‘萌宠消消乐’2000档次的特殊玩法",
			use_parm = {"game_Eliminate",},
		},
		[338]=
		{
			id = 338,
			item_id = 338,
			item_key = "prop_xxl_shuihu_card_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_shxxl_2",
			is_show_bag = 1,
			order = 12,
			name = "水浒消消乐游戏卡",
			desc = "使用后可触发‘水浒消消乐’2000档次的特殊玩法",
			use_parm = {"game_EliminateSH",},
		},
		[339]=
		{
			id = 339,
			item_id = 339,
			item_key = "prop_xxl_caishen_card_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_csxxl_2",
			is_show_bag = 1,
			order = 12,
			name = "财神消消乐游戏卡",
			desc = "使用后可触发‘财神消消乐’2000档次的特殊玩法",
			use_parm = {"game_EliminateCS",},
		},
		[340]=
		{
			id = 340,
			item_id = 340,
			item_key = "prop_xxl_xiyou_card_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_xyxxl_2",
			is_show_bag = 1,
			order = 12,
			name = "西游消消乐游戏卡",
			desc = "使用后可触发‘西游消消乐’2000档次的特殊玩法",
			use_parm = {"game_EliminateXY",},
		},
		[341]=
		{
			id = 341,
			item_id = 341,
			item_key = "prop_xxl_chaoji_card_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_cjxxl_2",
			is_show_bag = 1,
			order = 12,
			name = "超级消消乐游戏卡",
			desc = "使用后可触发‘超级消消乐’2000档次的特殊玩法",
			use_parm = {"game_EliminateCJ",},
		},
		[342]=
		{
			id = 342,
			item_id = 342,
			item_key = "prop_xxl_sanguo_card_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_sgxxl_12",
			is_show_bag = 1,
			order = 12,
			name = "三国消消乐游戏卡",
			desc = "使用后可触发‘三国消消乐’2000档次的特殊玩法",
			use_parm = {"game_EliminateSG",},
		},
		[343]=
		{
			id = 343,
			item_id = 343,
			item_key = "prop_xxl_shuiguo_card_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_mcxxl_3",
			is_show_bag = 1,
			order = 11,
			name = "萌宠消消乐游戏卡",
			desc = "使用后可触发‘萌宠消消乐’8000档次的特殊玩法",
			use_parm = {"game_Eliminate",},
		},
		[344]=
		{
			id = 344,
			item_id = 344,
			item_key = "prop_xxl_shuihu_card_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_shxxl_3",
			is_show_bag = 1,
			order = 11,
			name = "水浒消消乐游戏卡",
			desc = "使用后可触发‘水浒消消乐’8000档次的特殊玩法",
			use_parm = {"game_EliminateSH",},
		},
		[345]=
		{
			id = 345,
			item_id = 345,
			item_key = "prop_xxl_caishen_card_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_csxxl_3",
			is_show_bag = 1,
			order = 11,
			name = "财神消消乐游戏卡",
			desc = "使用后可触发‘财神消消乐’8000档次的特殊玩法",
			use_parm = {"game_EliminateCS",},
		},
		[346]=
		{
			id = 346,
			item_id = 346,
			item_key = "prop_xxl_xiyou_card_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_xyxxl_3",
			is_show_bag = 1,
			order = 11,
			name = "西游消消乐游戏卡",
			desc = "使用后可触发‘西游消消乐’8000档次的特殊玩法",
			use_parm = {"game_EliminateXY",},
		},
		[347]=
		{
			id = 347,
			item_id = 347,
			item_key = "prop_xxl_chaoji_card_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_cjxxl_3",
			is_show_bag = 1,
			order = 11,
			name = "超级消消乐游戏卡",
			desc = "使用后可触发‘超级消消乐’8000档次的特殊玩法",
			use_parm = {"game_EliminateCJ",},
		},
		[348]=
		{
			id = 348,
			item_id = 348,
			item_key = "prop_xxl_sanguo_card_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "bb_sgxxl_13",
			is_show_bag = 1,
			order = 11,
			name = "三国消消乐游戏卡",
			desc = "使用后可触发‘三国消消乐’8000档次的特殊玩法",
			use_parm = {"game_EliminateSG",},
		},
		[349]=
		{
			id = 349,
			item_id = 349,
			item_key = "prop_xxl_card_chip_1",
			lose_time = -1,
			is_local_icon = 1,
			image = "sp_icon_dj1",
			is_show_bag = 1,
			order = 16,
			name = "初级游戏卡碎片",
			desc = "消耗20个可合成初级游戏卡",
			use_parm = {"yxcard_compose","prop_xxl_card_chip_1"},
		},
		[350]=
		{
			id = 350,
			item_id = 350,
			item_key = "prop_xxl_card_chip_2",
			lose_time = -1,
			is_local_icon = 1,
			image = "sp_icon_dj2",
			is_show_bag = 1,
			order = 15,
			name = "中级游戏卡碎片",
			desc = "消耗20个可合成中级游戏卡",
			use_parm = {"yxcard_compose","prop_xxl_card_chip_2"},
		},
		[351]=
		{
			id = 351,
			item_id = 351,
			item_key = "prop_xxl_card_chip_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "sp_icon_dj3",
			is_show_bag = 1,
			order = 14,
			name = "高级游戏卡碎片",
			desc = "消耗20个可合成高级游戏卡",
			use_parm = {"yxcard_compose","prop_xxl_card_chip_3"},
		},
		[352]=
		{
			id = 352,
			item_id = 352,
			item_key = "obj_recharge_bonus_card_3",
			lose_time = -1,
			is_local_icon = 1,
			image = "czk_icon_l",
			is_show_bag = 1,
			order = 10,
			name = "普通充值加成卡",
			desc = "充值加成卡：使用后在充值商城中购买部分商品可获得额外加成，限时1小时。（不能和首冲加赠、充值优惠券同时使用）",
			use_parm = {"sys_czjc","obj_recharge_bonus_card_3"},
		},
		[353]=
		{
			id = 353,
			item_id = 353,
			item_key = "obj_recharge_bonus_card_5",
			lose_time = -1,
			is_local_icon = 1,
			image = "czk_icon_h",
			is_show_bag = 1,
			order = 9,
			name = "黄金充值加成卡",
			desc = "充值加成卡：使用后在充值商城中购买部分商品可获得额外加成，限时1小时。（不能和首冲加赠、充值优惠券同时使用）",
			use_parm = {"sys_czjc","obj_recharge_bonus_card_5"},
		},
		[354]=
		{
			id = 354,
			item_id = 354,
			item_key = "prop_kssql_icecream",
			lose_time = -1,
			is_local_icon = 1,
			image = "fkcdj_icon_bjl",
			is_show_bag = 0,
			order = 100,
			name = "冰淇淋",
			desc = "用于参加疯狂抽大奖活动",
		},
		[355]=
		{
			id = 355,
			item_id = 355,
			item_key = "fake_48",
			lose_time = -1,
			is_local_icon = 1,
			image = "byjnl_icon_hj",
			is_show_bag = 0,
			order = 100,
			name = "黄金纪念卡",
			desc = "周年庆典赛奖励",
		},
		[356]=
		{
			id = 356,
			item_id = 356,
			item_key = "fake_49",
			lose_time = -1,
			is_local_icon = 1,
			image = "byjnl_icon_by",
			is_show_bag = 0,
			order = 100,
			name = "白银纪念卡",
			desc = "周年庆典赛奖励",
		},
		[357]=
		{
			id = 357,
			item_id = 357,
			item_key = "prop_3year_gift1",
			lose_time = -1,
			is_local_icon = 1,
			image = "eznhk_icon_1",
			is_show_bag = 1,
			order = 100,
			name = "鲸币礼包",
			desc = "最高可获得10万鲸币！",
			use_parm = {"open_box_new","prop_3year_gift1"},
			box_id = 186,
		},
		[358]=
		{
			id = 358,
			item_id = 358,
			item_key = "prop_3year_gift2",
			lose_time = -1,
			is_local_icon = 1,
			image = "xyznq_icon_hjbx",
			is_show_bag = 1,
			order = 100,
			name = "黄金宝箱",
			desc = "最高可获得50万鲸币！",
			use_parm = {"open_box_new","prop_3year_gift2"},
			box_id = 187,
		},
		[359]=
		{
			id = 359,
			item_id = 359,
			item_key = "prop_3year_gift3",
			lose_time = -1,
			is_local_icon = 1,
			image = "xyznq_icon_bjbx",
			is_show_bag = 1,
			order = 100,
			name = "铂金宝箱",
			desc = "最高可获得100万鲸币！",
			use_parm = {"open_box_new","prop_3year_gift3"},
			box_id = 188,
		},
		[360]=
		{
			id = 360,
			item_id = 360,
			item_key = "prop_3year_gift4",
			lose_time = -1,
			is_local_icon = 1,
			image = "xyznq_icon_zsbx",
			is_show_bag = 1,
			order = 100,
			name = "钻石宝箱",
			desc = "最高可获得200万鲸币！",
			use_parm = {"open_box_new","prop_3year_gift4"},
			box_id = 189,
		},
		[361]=
		{
			id = 361,
			item_id = 361,
			item_key = "prop_3year_gift5",
			lose_time = -1,
			is_local_icon = 1,
			image = "xyznq_icon_wzbx",
			is_show_bag = 1,
			order = 100,
			name = "王者宝箱",
			desc = "最高可获得500万鲸币！",
			use_parm = {"open_box_new","prop_3year_gift5"},
			box_id = 190,
		},
		[362]=
		{
			id = 362,
			item_id = 362,
			item_key = "prop_wys_ticket_resurrection",
			lose_time = -1,
			is_local_icon = 1,
			image = "fhsmp_icon_hfmp",
			is_show_bag = 1,
			order = 19,
			name = "万元赛复活门票",
			desc = "万元赛预赛期间被淘汰，可使用复活门票复活",
			use_parm = {"match_hall","hks",},
		},
		[363]=
		{
			id = 363,
			item_id = 363,
			item_key = "prop_3rdyear_cjq",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_dhq",
			is_show_bag = 0,
			order = 100,
			name = "抽奖券",
			desc = "用于周年抽大奖活动抽奖使用",
		},
		[364]=
		{
			id = 364,
			item_id = 364,
			item_key = "expression_59",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_xq",
			is_show_bag = 0,
			order = 100,
			name = "雪球表情",
			desc = "雪球表情",
		},
		[365]=
		{
			id = 365,
			item_id = 365,
			item_key = "fake_50",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift310_jhdz",
			is_show_bag = 0,
			order = 100,
			name = " 金虎吊坠",
			desc = "元旦狂欢赛奖励",
		},
		[366]=
		{
			id = 366,
			item_id = 366,
			item_key = "fake_51",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift311_jhsl",
			is_show_bag = 0,
			order = 100,
			name = "金虎手链",
			desc = "元旦狂欢赛奖励",
		},
		[367]=
		{
			id = 367,
			item_id = 367,
			item_key = "fake_52",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift312_yhxl",
			is_show_bag = 0,
			order = 100,
			name = "银虎项链",
			desc = "元旦狂欢赛奖励",
		},
		[368]=
		{
			id = 368,
			item_id = 368,
			item_key = "fake_53",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift313_dbhss",
			is_show_bag = 0,
			order = 100,
			name = "大宝护手霜",
			desc = "元旦狂欢赛奖励",
		},
		[369]=
		{
			id = 369,
			item_id = 369,
			item_key = "prop_gift_bag_nor",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_pthb",
			is_show_bag = 1,
			order = 1,
			name = "普通红包",
			desc = "大年初一可开启，随机获得0.1~1福卡",
			use_parm = {"open_box_new","prop_gift_bag_nor"},
			box_id = 202,
		},
		[370]=
		{
			id = 370,
			item_id = 370,
			item_key = "prop_gift_bag_high",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_gjhb",
			is_show_bag = 1,
			order = 1,
			name = "高级红包",
			desc = "大年初一可开启，随机获得0.5~2福卡",
			use_parm = {"open_box_new","prop_gift_bag_high"},
			box_id = 203,
		},
		[371]=
		{
			id = 371,
			item_id = 371,
			item_key = "prop_gift_bag_spec",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_tjhb",
			is_show_bag = 1,
			order = 1,
			name = "特级红包",
			desc = "大年初一可开启，随机获得3~15福卡",
			use_parm = {"open_box_new","prop_gift_bag_spec"},
			box_id = 204,
		},
		[372]=
		{
			id = 372,
			item_id = 372,
			item_key = "prop_gift_bag_prime",
			lose_time = -1,
			is_local_icon = 1,
			image = "com_award_icon_zzhb",
			is_show_bag = 1,
			order = 1,
			name = "至尊红包",
			desc = "大年初一可开启，随机获得8~30福卡",
			use_parm = {"open_box_new","prop_gift_bag_prime"},
			box_id = 205,
		},
		[373]=
		{
			id = 373,
			item_id = 373,
			item_key = "expression_60",
			lose_time = -1,
			is_local_icon = 1,
			image = "ddz_game_ui_bp",
			is_show_bag = 0,
			order = 100,
			name = "鞭炮表情",
			desc = "鞭炮表情",
		},
		[374]=
		{
			id = 374,
			item_id = 374,
			item_key = "prop_nianshou_firecrackers_down",
			lose_time = -1,
			is_local_icon = 1,
			image = "dns_icon_djbp",
			is_show_bag = 0,
			order = 100,
			name = "鞭炮",
		},
		[375]=
		{
			id = 375,
			item_id = 375,
			item_key = "prop_nianshou_firecrackers_high",
			lose_time = -1,
			is_local_icon = 1,
			image = "dns_icon_gjbp",
			is_show_bag = 0,
			order = 100,
			name = "鞭炮",
		},
		[376]=
		{
			id = 376,
			item_id = 376,
			item_key = "prop_word_spring",
			lose_time = -1,
			is_local_icon = 1,
			image = "tcxb_icon_c",
			is_show_bag = 0,
			order = 100,
			name = "春字",
			desc = "每轮开启不同数量的“春”字，可获得不同数量的奖励。",
		},
		[377]=
		{
			id = 377,
			item_id = 377,
			item_key = "fake_54",
			lose_time = -1,
			is_local_icon = 1,
			image = "activity_icon_gift321_OPPOsj",
			is_show_bag = 0,
			order = 100,
			name = "OPPO手机",
			desc = "OPPO手机比赛奖励",
		},
	},
}