return {
	game=
	{
		[1]=
		{
			id = 1,
			game_tag = "hbs",
			game_name = "全天福利赛",
			game_type = {"game_DdzMatch","game_MjXzMatch3D"},
			order = 1,
			is_tj = 1,
			is_show = 1,
			is_on = 1,
			is_time = 0,
			content_type = 2,
			tge_prefab = "MatchHallTgeItem",
			content_prefab = "MatchHallContent",
			tge_mini_prefab = "MatchHallTgeMiniItem",
			tge_mini_desc = {"斗地主","血战到底",},
			not_begin_ui = {"match_bg_qdbg","match_imgf_bsjjkq","match_imgfj_qd","",},
		},
		[2]=
		{
			id = 2,
			game_tag = "djs",
			game_name = "大奖赛",
			game_type = "game_DdzMillion",
			order = 7,
			is_tj = 1,
			is_show = 0,
			is_on = 0,
			is_time = 0,
			content_type = 1,
			tge_prefab = "MatchHallTgeItem",
			content_prefab = "MatchHallContent",
			not_begin_ui = {"match_bg_qdbg","match_imgf_bsjjkq","match_imgfj_qd","",},
		},
		[3]=
		{
			id = 3,
			game_tag = "jyb",
			game_name = "全国鲸鱼杯",
			game_type = "game_CityMatch",
			order = 5,
			is_tj = 0,
			is_show = 0,
			is_on = 0,
			is_time = 1,
			content_type = 3,
			tge_prefab = "MatchHallTgeItem",
			content_prefab = "MatchHallContent",
			not_begin_ui = {"match_bg_qdbg","match_imgf_bsjjkq","match_imgfj_qd","",},
			begin_goto_ui = {"match_bg_dj",},
		},
		[4]=
		{
			id = 4,
			game_tag = "fps",
			game_name = "公益扶贫赛",
			game_type = "game_DdzMatch",
			order = 9,
			is_tj = 0,
			is_show = 0,
			is_on = 0,
			is_time = 0,
			content_type = 1,
			tge_prefab = "MatchHallTgeItem",
			content_prefab = "MatchHallContent",
			not_begin_ui = {"match_bg_qdbg","match_imgf_bsjjkq","match_imgfj_qd","",},
		},
		[5]=
		{
			id = 5,
			game_tag = "gms",
			game_name = "福利大奖赛",
			game_type = "game_DdzMatchNaming",
			order = 2,
			is_tj = 0,
			is_show = 0,
			is_on = 1,
			is_time = 1,
			content_type = 1,
			tge_prefab = "MatchHallTgeItem",
			content_prefab = "MatchHallContent",
			not_begin_ui = {"match_bg_qdbg","match_imgf_bsjjkq","match_imgfj_qd","",},
		},
		[6]=
		{
			id = 6,
			game_tag = "qys",
			game_name = "企业大奖赛",
			game_type = "game_DdzMatchNaming",
			order = 8,
			is_tj = 0,
			is_show = 0,
			is_on = 1,
			is_time = 0,
			content_type = 1,
			tge_prefab = "MatchHallTgeItem",
			content_prefab = "MatchHallContent",
			not_begin_ui = {"match_bg_qdbg","match_imgf_bsjjkq","match_imgfj_qd","",},
		},
		[7]=
		{
			id = 7,
			game_tag = "sws",
			game_name = "实物大奖赛",
			game_type = "game_DdzMatch",
			order = 6,
			is_tj = 0,
			is_show = 0,
			is_on = 0,
			is_time = 1,
			content_type = 1,
			tge_prefab = "MatchHallTgeItem",
			content_prefab = "MatchHallContent",
			not_begin_ui = {"match_bg_qdbg","match_imgf_bsjjkq","match_imgfj_qd","",},
		},
		[8]=
		{
			id = 8,
			game_tag = "mxb",
			game_name = "VIP4回馈赛",
			game_type = "game_DdzMatchNaming",
			order = 4,
			is_tj = 0,
			is_show = 0,
			is_on = 1,
			is_time = 1,
			content_type = 1,
			tge_prefab = "MatchHallTgeItem",
			content_prefab = "MatchHallContent",
			not_begin_ui = {"match_bg_qdbg","match_imgf_bsjjkq","match_imgfj_qd","",},
		},
		[9]=
		{
			id = 9,
			game_tag = "ges",
			game_name = "月末福利赛",
			game_type = "game_DdzMatchNaming",
			order = 3,
			is_tj = 0,
			is_show = 0,
			is_on = 1,
			is_time = 0,
			content_type = 1,
			tge_prefab = "MatchHallTgeItem",
			content_prefab = "MatchHallContent",
			not_begin_ui = {"match_bg_qdbg","match_imgf_bsjjkq","match_imgfj_qd","",},
		},
	},
}