return {
	config=
	{
		[1]=
		{
			id = 1,
			ID = 1,
			noCloseUI = 0,
			order = 4,
			type = "activity",
			title = "打比赛赢福卡！",
			showType = "image",
			parmData = "ad_1",
			gotoUI = "match_hall",
			beginTime = -1,
			endTime = -1,
			isOnOff = 0,
		},
		[2]=
		{
			id = 2,
			ID = 2,
			noCloseUI = 0,
			order = 1,
			type = "activity",
			title = "双11礼物独宠一人！",
			showType = "image",
			parmData = "ad_7",
			tag = "new",
			beginTime = -1,
			endTime = -1,
			isOnOff = 0,
		},
		[3]=
		{
			id = 3,
			ID = 3,
			noCloseUI = 0,
			order = 0,
			type = "notice",
			title = "不删号内测公告",
			showType = "notice",
			parmData = "亲爱的玩家朋友们：\n\n【鲸鱼斗地主】在9月15日（周六）上午10:00开启不删档内测，安卓和IOS版本同步上线！\n登录【鲸鱼斗地主】即赠送1福卡+6000鲸币+10张房卡+1天记牌器！如遇到任何问题或建议在【鲸鱼新家园】公众号反馈即可。\n\n温馨提示：因苹果商店政策原因，苹果用户钻石充值比例为1:66（公众号充值比例1:100），请用苹果手机的玩家在官方公众号【鲸鱼新家园】进行充值。充值方法：点击个人中心→充值中心。\n\n                                                                     《鲸鱼斗地主》运营团队\n                                                                                2018年9月15日",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
			isOnOff = 1,
		},
		[4]=
		{
			id = 4,
			ID = 4,
			noCloseUI = 0,
			order = 0,
			type = "activity",
			title = "鲸鱼杯大奖赛",
			showType = "image",
			parmData = "ad_5",
			gotoUI = "citymatch_hall",
			tag = "hot",
			beginTime = -1,
			endTime = -1,
			isOnOff = 0,
		},
		[5]=
		{
			id = 5,
			ID = 5,
			noCloseUI = 1,
			order = 3,
			type = "activity",
			title = "2元超值礼包",
			showType = "image",
			parmData = "ad_4",
			gotoUI = "2_gift_bag",
			tag = "hot",
			beginTime = -1,
			endTime = -1,
			isOnOff = 0,
		},
		[6]=
		{
			id = 6,
			ID = 6,
			noCloseUI = 0,
			order = 0,
			type = "notice",
			title = "官方微信群",
			showType = "notice",
			parmData = "亲爱的玩家朋友们：\n\n鲸鱼斗地主官方微信群正式上线啦，请添加客服微信号：JYDDZ05，由客服拉您进群，群里不定时福卡雨，还有漂亮的小姐姐小哥哥可以聊天哦，期待您的加入！\n感谢您对鲸鱼斗地主的热爱和支持！\n\n                                                                     鲸鱼斗地主运营团队敬上\n                                                                                2018年10月12日",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
			isOnOff = 1,
		},
		[7]=
		{
			id = 7,
			ID = 7,
			noCloseUI = 0,
			order = 2,
			type = "activity",
			title = "现金奖池来袭！",
			showType = "image",
			parmData = "ad_6",
			gotoUI = "free_hall",
			tag = "normal",
			beginTime = -1,
			endTime = -1,
			isOnOff = 0,
		},
	},
}