return {
	ranks=
	{
		[1]=
		{
			index = 1,
			act_rank_key = "rank_qdphb",
			act_rank_name = "庆典排行榜",
			start_time = 1610407800,
			end_time = 1610985599,
			rank_type = "khqd_046_qdphb_rank",
			type = 1,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
		},
		[2]=
		{
			index = 2,
			act_rank_key = "rank_bydr",
			act_rank_name = "捕鱼达人",
			start_time = 1611012600,
			end_time = 1611590399,
			rank_type = "bysd_047_bydr_rank",
			permission_key = "actp_rank_bysd_047_bydr_rank",
			type = 1,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
		},
		[3]=
		{
			index = 3,
			act_rank_key = "rank_xxlbd",
			act_rank_name = "消消乐榜单",
			start_time = 1611617400,
			end_time = 1612195199,
			rank_type = "xxlqd_048_xxlbd",
			type = 1,
			item_type = 2,
			item_name = "倍数",
			isOnOff = 0,
		},
		[4]=
		{
			index = 4,
			act_rank_key = "rank_fqdr",
			act_rank_name = "福气达人",
			start_time = 1612222200,
			end_time = 1612799999,
			rank_type = "cjs_049_fqdr_rank",
			type = 1,
			item_type = 1,
			item_name = "福气值",
			isOnOff = 0,
		},
		[5]=
		{
			index = 5,
			act_rank_key = "rank_ysqbd",
			act_rank_name = "压岁钱榜单",
			start_time = 1612827000,
			end_time = 1613404799,
			rank_type = "gdn_050_ysqbd_rank",
			permission_key = "actp_rank_gdn_050_ysqbd_rank",
			type = 1,
			item_type = 1,
			item_name = "压岁钱",
			isOnOff = 0,
		},
		[6]=
		{
			index = 6,
			act_rank_key = "rank_cqbd",
			act_rank_name = "财气榜单",
			start_time = 1613431800,
			end_time = 1614009599,
			rank_type = "ycs_051_cqbd_rank",
			type = 1,
			item_type = 1,
			item_name = "财气总数",
			isOnOff = 0,
		},
		[7]=
		{
			index = 7,
			act_rank_key = "rank_nyx_jfdr",
			style_key = "act_007_nyx_jfdr",
			act_rank_name = "积分达人",
			start_time = 1614036600,
			end_time = 1614614399,
			rank_type = "nyx_052_jfdr_rank",
			type = 1,
			item_type = 1,
			item_name = "积分",
			gotoUI = "game_FishingHall",
			isOnOff = 0,
		},
		[8]=
		{
			index = 8,
			act_rank_key = "rank_ltqf_fqdr",
			style_key = "act_008_fqdr",
			act_rank_name = "福气达人",
			start_time = 1615246200,
			end_time = 1615823999,
			rank_type = "ltfl_054_fqdr",
			type = 3,
			item_type = 1,
			item_name = "福气值",
			isOnOff = 0,
		},
		[9]=
		{
			index = 9,
			act_rank_key = "rank_chdd_jfphb",
			style_key = "act_009_chdd_jfphb",
			act_rank_name = "积分排行榜",
			start_time = 1615851000,
			end_time = 1616428799,
			rank_type = "chdd_055_jfphb_rank",
			type = 3,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
		},
		[10]=
		{
			index = 10,
			act_rank_key = "rank_hljnh_yxdr",
			style_key = "act_010_jfdr",
			act_rank_name = "游戏达人",
			start_time = 1616455800,
			end_time = 1617033599,
			rank_type = "hljnh_056_yxdr_rank",
			type = 3,
			item_type = 3,
			item_name = "财力",
			isOnOff = 0,
		},
		[11]=
		{
			index = 11,
			act_rank_key = "rank_qmjz_jfbd",
			style_key = "act_011_jfbd",
			act_rank_name = "积分榜单",
			start_time = 1617060600,
			end_time = 1617638399,
			rank_type = "qmjz_057_jfbd_rank",
			type = 3,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
		},
		[12]=
		{
			index = 12,
			act_rank_key = "rank_khqd_qdbd",
			style_key = "act_012_qdbd",
			act_rank_name = "庆典榜单",
			start_time = 1617665400,
			end_time = 1618243199,
			rank_type = "khqd_058_qdbd_rank",
			type = 3,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
		},
		[13]=
		{
			index = 13,
			act_rank_key = "rank_hljnh_yxdr_02",
			style_key = "act_010_jfdr",
			act_rank_name = "游戏达人",
			start_time = 1618270200,
			end_time = 1618847999,
			rank_type = "hljnh_059_yxdr_rank",
			type = 3,
			item_type = 3,
			item_name = "财力",
			isOnOff = 0,
		},
		[14]=
		{
			index = 14,
			act_rank_key = "rank_fkxxl_xxldr",
			style_key = "act_011_xxldr",
			act_rank_name = "消消乐达人",
			start_time = 1618875000,
			end_time = 1619452799,
			rank_type = "fkxxl_060_xxldr_rank",
			type = 3,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
		},
		[15]=
		{
			index = 15,
			act_rank_key = "rank_wykl_ldmf",
			style_key = "act_013_ldmf",
			act_rank_name = "劳动模范",
			start_time = 1619479800,
			end_time = 1620662399,
			rank_type = "wykl_061_ldmf_rank",
			type = 3,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
		},
		[16]=
		{
			index = 16,
			act_rank_key = "rank_hljnh_yxdr_03",
			style_key = "act_037_yxdr",
			act_rank_name = "游戏达人",
			start_time = 1641857400,
			end_time = 1643039999,
			rank_type = "hljnh_062_yxdr_rank",
			type = 3,
			item_type = 3,
			item_name = "财力",
			gotoUI = "game_MiniGame",
			isOnOff = 0,
			gift_key = "gift_wykl_jflb",
		},
		[17]=
		{
			index = 17,
			act_rank_key = "rank_khqd_qdbd_02",
			style_key = "act_015_qdbd",
			act_rank_name = "庆典榜单",
			start_time = 1621294200,
			end_time = 1621871999,
			rank_type = "khqd_063_qdbd_rank",
			type = 3,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
		},
		[18]=
		{
			index = 18,
			act_rank_key = "rank_ymkh_jfphb",
			style_key = "act_016_ymkh_jfphb",
			act_rank_name = "积分排行榜",
			start_time = 1621899000,
			end_time = 1622476799,
			rank_type = "ymkh_064_jfphb_rank",
			type = 3,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
		},
		[19]=
		{
			index = 19,
			act_rank_key = "rank_etjkl_jfphb",
			style_key = "act_046_fqbd",
			act_rank_name = "福气榜单",
			start_time = 1649115000,
			end_time = 1649692799,
			rank_type = "etjkl_065_jfphb_rank",
			type = 3,
			item_type = 1,
			item_name = "福气",
			isOnOff = 1,
			gift_key = "gift_wykl_jflb",
		},
		[20]=
		{
			index = 20,
			act_rank_key = "rank_ymkh_jfphb",
			style_key = "act_016_ymkh_jfphb",
			act_rank_name = "庆典榜单",
			start_time = 1621899000,
			end_time = 1622476799,
			rank_type = "znqd_3rd_qdbd_rank",
			type = 3,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
		},
		[21]=
		{
			index = 21,
			act_rank_key = "rank_khqd_zcbd",
			style_key = "act_034_zqbd",
			act_rank_name = "朱雀榜单",
			start_time = 1639438200,
			end_time = 1640015999,
			rank_type = "khqd_066_zcbd_rank",
			type = 1,
			item_type = 2,
			item_name = "火羽",
			isOnOff = 0,
		},
		[22]=
		{
			index = 22,
			act_rank_key = "rank_drop_act",
			style_key = "act_035_jfbd",
			act_rank_name = "积分榜单",
			start_time = 1640043000,
			end_time = 1640620799,
			rank_type = "drop_act_allgame_rank",
			type = 3,
			item_type = 2,
			item_name = "积分",
			isOnOff = 0,
			gift_key = "gift_wykl_jflb",
		},
		[23]=
		{
			index = 23,
			act_rank_key = "rank_grade_nianshou",
			style_key = "act_038_jfphb",
			act_rank_name = "积分排行榜",
			start_time = 1643067000,
			end_time = 1644854399,
			rank_type = "cjyx_nianshou_grade_rank",
			type = 3,
			item_type = 1,
			item_name = "积分",
			isOnOff = 0,
			gift_key = "gift_wykl_jflb",
		},
	},
	others=
	{
		award=
		{
			cfg = {500,200,100,50,50,50,30,30,30,30,20,20,20,20,20,10,10,10,10,10},
		},
		rank_win_icon=
		{
			cfg = {"localpop_icon_1","localpop_icon_2","localpop_icon_3",},
		},
	},
	ext_award_cfg=
	{
		[1]=
		{
			index = 1,
			base_award = 400,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_5"},
			ext_award_num = {600,1},
			ext_award_condi = 30000,
			ext_award_condi_txt = "积分达到3万",
		},
		[2]=
		{
			index = 2,
			base_award = 150,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_5"},
			ext_award_num = {150,1},
			ext_award_condi = 20000,
			ext_award_condi_txt = "积分达到2万",
		},
		[3]=
		{
			index = 3,
			base_award = 50,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_5"},
			ext_award_num = {50,1},
			ext_award_condi = 10000,
			ext_award_condi_txt = "积分达到1万",
		},
		[4]=
		{
			index = 4,
			base_award = 22,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_5"},
			ext_award_num = {8,1},
			ext_award_condi = 5000,
			ext_award_condi_txt = "积分达到5000",
		},
		[5]=
		{
			index = 5,
			base_award = 22,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_5"},
			ext_award_num = {8,1},
			ext_award_condi = 5000,
			ext_award_condi_txt = "积分达到5000",
		},
		[6]=
		{
			index = 6,
			base_award = 22,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_5"},
			ext_award_num = {8,1},
			ext_award_condi = 5000,
			ext_award_condi_txt = "积分达到5000",
		},
		[7]=
		{
			index = 7,
			base_award = 12,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_5"},
			ext_award_num = {8,1},
			ext_award_condi = 3000,
			ext_award_condi_txt = "积分达到3000",
		},
		[8]=
		{
			index = 8,
			base_award = 12,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_5"},
			ext_award_num = {8,1},
			ext_award_condi = 3000,
			ext_award_condi_txt = "积分达到3000",
		},
		[9]=
		{
			index = 9,
			base_award = 12,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_5"},
			ext_award_num = {8,1},
			ext_award_condi = 3000,
			ext_award_condi_txt = "积分达到3000",
		},
		[10]=
		{
			index = 10,
			base_award = 12,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_5"},
			ext_award_num = {8,1},
			ext_award_condi = 3000,
			ext_award_condi_txt = "积分达到3000",
		},
		[11]=
		{
			index = 11,
			base_award = 6,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_3"},
			ext_award_num = {4,1},
			ext_award_condi = 2000,
			ext_award_condi_txt = "积分达到2000",
		},
		[12]=
		{
			index = 12,
			base_award = 6,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_3"},
			ext_award_num = {4,1},
			ext_award_condi = 2000,
			ext_award_condi_txt = "积分达到2000",
		},
		[13]=
		{
			index = 13,
			base_award = 6,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_3"},
			ext_award_num = {4,1},
			ext_award_condi = 2000,
			ext_award_condi_txt = "积分达到2000",
		},
		[14]=
		{
			index = 14,
			base_award = 6,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_3"},
			ext_award_num = {4,1},
			ext_award_condi = 2000,
			ext_award_condi_txt = "积分达到2000",
		},
		[15]=
		{
			index = 15,
			base_award = 6,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_3"},
			ext_award_num = {4,1},
			ext_award_condi = 2000,
			ext_award_condi_txt = "积分达到2000",
		},
		[16]=
		{
			index = 16,
			base_award = 3,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_3"},
			ext_award_num = {2,1},
			ext_award_condi = 1000,
			ext_award_condi_txt = "积分达到1000",
		},
		[17]=
		{
			index = 17,
			base_award = 3,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_3"},
			ext_award_num = {2,1},
			ext_award_condi = 1000,
			ext_award_condi_txt = "积分达到1000",
		},
		[18]=
		{
			index = 18,
			base_award = 3,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_3"},
			ext_award_num = {2,1},
			ext_award_condi = 1000,
			ext_award_condi_txt = "积分达到1000",
		},
		[19]=
		{
			index = 19,
			base_award = 3,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_3"},
			ext_award_num = {2,1},
			ext_award_condi = 1000,
			ext_award_condi_txt = "积分达到1000",
		},
		[20]=
		{
			index = 20,
			base_award = 3,
			ext_award = {"shop_gold_sum","obj_recharge_bonus_card_3"},
			ext_award_num = {2,1},
			ext_award_condi = 1000,
			ext_award_condi_txt = "积分达到1000",
		},
	},
}