return {
	base=
	{
		[1]=
		{
			index = 1,
			award = "0.1元奖励金",
			cost = 0.1,
			task_id = 21578,
			task_txt = "任意游戏累计赢金1000",
			show_permission = "actp_own_task_p_xshb_042_nor",
			limit = "终身1次",
			unlock_id = 1,
			tag = "新人",
			goto_ui = "game_MiniGame",
			is_on = 1,
		},
		[2]=
		{
			index = 2,
			award = "2元奖励金",
			cost = 2,
			task_id = 21579,
			task_txt = "拥有20000鲸币",
			show_permission = "actp_own_task_p_xshb_042_guanfang",
			limit = "终身1次",
			unlock_id = 2,
			tag = "新人",
			goto_ui = "shop",
			is_on = 0,
		},
		[3]=
		{
			index = 3,
			award = "2元奖励金",
			cost = 2,
			task_id = 21580,
			task_txt = "匹配场三星及以上场次对局10局",
			show_permission = "actp_own_task_p_xshb_042_cpl",
			limit = "终身1次",
			unlock_id = 3,
			tag = "新人",
			goto_ui = "game_Free",
			is_on = 1,
		},
		[4]=
		{
			index = 4,
			award = "3元奖励金",
			cost = 3,
			task_id = 21581,
			task_txt = "单笔充值≥6元",
			limit = "终身3次",
			unlock_id = 4,
			tag = "新人",
			goto_ui = "shop",
			is_on = 0,
		},
		[5]=
		{
			index = 5,
			award = "1元奖励金",
			cost = 1,
			task_id = 21582,
			task_txt = "匹配场三星及以上场次对局6局",
			limit = "每天1次",
			unlock_id = 5,
			unlock_permission = "xshb_042_deblocking_v1",
			tag = "VIP1",
			goto_ui = "game_Free",
			is_on = 1,
		},
		[6]=
		{
			index = 6,
			award = "3元奖励金",
			cost = 3,
			task_id = 21583,
			task_txt = "匹配场四星及以上场次对局10局",
			limit = "每天1次",
			unlock_id = 6,
			unlock_permission = "xshb_042_deblocking_v2",
			tag = "VIP2",
			goto_ui = "game_Free",
			is_on = 0,
		},
		[7]=
		{
			index = 7,
			award = "10元奖励金",
			cost = 10,
			task_id = 21584,
			task_txt = "任意游戏累计赢金1000",
			show_permission = "actp_own_task_p_xshb_042_nor",
			limit = "终身1次",
			unlock_id = 7,
			unlock_permission = "xshb_042_deblocking_v1",
			tag = "VIP1",
			goto_ui = "game_MiniGame",
			is_on = 0,
		},
		[8]=
		{
			index = 8,
			award = "100元奖励金",
			cost = 110,
			task_id = 21585,
			task_txt = "任意游戏累计赢金300万",
			show_permission = "actp_xshb_show_vip4_nor",
			limit = "每天1次",
			unlock_id = 8,
			unlock_permission = "xshb_042_deblocking_v6",
			tag = "VIP6",
			goto_ui = "game_MiniGame",
			is_on = 0,
		},
		[9]=
		{
			index = 9,
			award = "200元奖励金",
			cost = 200,
			task_id = 21586,
			task_txt = "任意游戏累计赢金300万",
			show_permission = "actp_xshb_show_vip8_nor",
			limit = "每天1次",
			unlock_id = 9,
			unlock_permission = "xshb_042_deblocking_v10",
			tag = "VIP10",
			goto_ui = "game_MiniGame",
			is_on = 0,
		},
		[10]=
		{
			index = 10,
			award = "100元奖励金",
			cost = 100,
			task_id = 21587,
			task_txt = "任意游戏累计赢金500万",
			limit = "每天1次",
			unlock_id = 10,
			unlock_permission = "xshb_042_deblocking_v8",
			tag = "VIP8",
			goto_ui = "game_MiniGame",
			is_on = 0,
		},
	},
}